--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.pb_common_pb')

PBRESULT = protobuf.Descriptor();
PBRESULT_RESULT_FIELD = protobuf.FieldDescriptor();
PBID32 = protobuf.Descriptor();
PBID32_ID_FIELD = protobuf.FieldDescriptor();
PBID32R = protobuf.Descriptor();
PBID32R_ID_FIELD = protobuf.FieldDescriptor();
PBID64 = protobuf.Descriptor();
PBID64_ID_FIELD = protobuf.FieldDescriptor();
PBID64R = protobuf.Descriptor();
PBID64R_IDS_FIELD = protobuf.FieldDescriptor();
PBIDSTRING = protobuf.Descriptor();
PBIDSTRING_ID_FIELD = protobuf.FieldDescriptor();

PBRESULT_RESULT_FIELD.name = "result"
PBRESULT_RESULT_FIELD.full_name = ".pb_common.pbResult.result"
PBRESULT_RESULT_FIELD.number = 1
PBRESULT_RESULT_FIELD.index = 0
PBRESULT_RESULT_FIELD.label = 1
PBRESULT_RESULT_FIELD.has_default_value = false
PBRESULT_RESULT_FIELD.default_value = 0
PBRESULT_RESULT_FIELD.type = 5
PBRESULT_RESULT_FIELD.cpp_type = 1

PBRESULT.name = "pbResult"
PBRESULT.full_name = ".pb_common.pbResult"
PBRESULT.nested_types = {}
PBRESULT.enum_types = {}
PBRESULT.fields = {PBRESULT_RESULT_FIELD}
PBRESULT.is_extendable = false
PBRESULT.extensions = {}
PBID32_ID_FIELD.name = "id"
PBID32_ID_FIELD.full_name = ".pb_common.pbId32.id"
PBID32_ID_FIELD.number = 1
PBID32_ID_FIELD.index = 0
PBID32_ID_FIELD.label = 1
PBID32_ID_FIELD.has_default_value = false
PBID32_ID_FIELD.default_value = 0
PBID32_ID_FIELD.type = 5
PBID32_ID_FIELD.cpp_type = 1

PBID32.name = "pbId32"
PBID32.full_name = ".pb_common.pbId32"
PBID32.nested_types = {}
PBID32.enum_types = {}
PBID32.fields = {PBID32_ID_FIELD}
PBID32.is_extendable = false
PBID32.extensions = {}
PBID32R_ID_FIELD.name = "id"
PBID32R_ID_FIELD.full_name = ".pb_common.pbId32R.id"
PBID32R_ID_FIELD.number = 1
PBID32R_ID_FIELD.index = 0
PBID32R_ID_FIELD.label = 3
PBID32R_ID_FIELD.has_default_value = false
PBID32R_ID_FIELD.default_value = {}
PBID32R_ID_FIELD.type = 5
PBID32R_ID_FIELD.cpp_type = 1

PBID32R.name = "pbId32R"
PBID32R.full_name = ".pb_common.pbId32R"
PBID32R.nested_types = {}
PBID32R.enum_types = {}
PBID32R.fields = {PBID32R_ID_FIELD}
PBID32R.is_extendable = false
PBID32R.extensions = {}
PBID64_ID_FIELD.name = "id"
PBID64_ID_FIELD.full_name = ".pb_common.pbId64.id"
PBID64_ID_FIELD.number = 1
PBID64_ID_FIELD.index = 0
PBID64_ID_FIELD.label = 1
PBID64_ID_FIELD.has_default_value = false
PBID64_ID_FIELD.default_value = 0
PBID64_ID_FIELD.type = 3
PBID64_ID_FIELD.cpp_type = 2

PBID64.name = "pbId64"
PBID64.full_name = ".pb_common.pbId64"
PBID64.nested_types = {}
PBID64.enum_types = {}
PBID64.fields = {PBID64_ID_FIELD}
PBID64.is_extendable = false
PBID64.extensions = {}
PBID64R_IDS_FIELD.name = "ids"
PBID64R_IDS_FIELD.full_name = ".pb_common.pbId64R.ids"
PBID64R_IDS_FIELD.number = 1
PBID64R_IDS_FIELD.index = 0
PBID64R_IDS_FIELD.label = 3
PBID64R_IDS_FIELD.has_default_value = false
PBID64R_IDS_FIELD.default_value = {}
PBID64R_IDS_FIELD.type = 3
PBID64R_IDS_FIELD.cpp_type = 2

PBID64R.name = "pbId64R"
PBID64R.full_name = ".pb_common.pbId64R"
PBID64R.nested_types = {}
PBID64R.enum_types = {}
PBID64R.fields = {PBID64R_IDS_FIELD}
PBID64R.is_extendable = false
PBID64R.extensions = {}
PBIDSTRING_ID_FIELD.name = "id"
PBIDSTRING_ID_FIELD.full_name = ".pb_common.pbIdString.id"
PBIDSTRING_ID_FIELD.number = 1
PBIDSTRING_ID_FIELD.index = 0
PBIDSTRING_ID_FIELD.label = 1
PBIDSTRING_ID_FIELD.has_default_value = false
PBIDSTRING_ID_FIELD.default_value = ""
PBIDSTRING_ID_FIELD.type = 9
PBIDSTRING_ID_FIELD.cpp_type = 9

PBIDSTRING.name = "pbIdString"
PBIDSTRING.full_name = ".pb_common.pbIdString"
PBIDSTRING.nested_types = {}
PBIDSTRING.enum_types = {}
PBIDSTRING.fields = {PBIDSTRING_ID_FIELD}
PBIDSTRING.is_extendable = false
PBIDSTRING.extensions = {}

pbId32 = protobuf.Message(PBID32)
pbId32R = protobuf.Message(PBID32R)
pbId64 = protobuf.Message(PBID64)
pbId64R = protobuf.Message(PBID64R)
pbIdString = protobuf.Message(PBIDSTRING)
pbResult = protobuf.Message(PBRESULT)

