
local ConfigSyschild_star_exp={
              [1] = {
                      star_lv = 1,
                      exp = 426,
                      property1 = {
                              20,
                              10,
                              100,
                              10,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              10,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              10,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              10,
                            },
                    },
              [2] = {
                      star_lv = 2,
                      exp = 522,
                      property1 = {
                              20,
                              10,
                              100,
                              11,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              11,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              11,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              11,
                            },
                    },
              [3] = {
                      star_lv = 3,
                      exp = 612,
                      property1 = {
                              20,
                              10,
                              100,
                              12,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              12,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              12,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              12,
                            },
                    },
              [4] = {
                      star_lv = 4,
                      exp = 702,
                      property1 = {
                              20,
                              10,
                              100,
                              13,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              13,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              13,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              13,
                            },
                    },
              [5] = {
                      star_lv = 5,
                      exp = 798,
                      property1 = {
                              20,
                              10,
                              100,
                              14,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              14,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              14,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              14,
                            },
                    },
              [6] = {
                      star_lv = 6,
                      exp = 888,
                      property1 = {
                              20,
                              10,
                              100,
                              15,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              15,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              15,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              15,
                            },
                    },
              [7] = {
                      star_lv = 7,
                      exp = 984,
                      property1 = {
                              20,
                              10,
                              100,
                              16,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              16,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              16,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              16,
                            },
                    },
              [8] = {
                      star_lv = 8,
                      exp = 1428,
                      property1 = {
                              20,
                              10,
                              100,
                              17,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              17,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              17,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              17,
                            },
                    },
              [9] = {
                      star_lv = 9,
                      exp = 1776,
                      property1 = {
                              20,
                              10,
                              100,
                              18,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              18,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              18,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              18,
                            },
                    },
              [10] = {
                      star_lv = 10,
                      exp = 2208,
                      property1 = {
                              20,
                              10,
                              100,
                              19,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              19,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              19,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              19,
                            },
                    },
              [11] = {
                      star_lv = 11,
                      exp = 2748,
                      property1 = {
                              20,
                              10,
                              100,
                              20,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              20,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              20,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              20,
                            },
                    },
              [12] = {
                      star_lv = 12,
                      exp = 3420,
                      property1 = {
                              20,
                              10,
                              100,
                              21,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              21,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              21,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              21,
                            },
                    },
              [13] = {
                      star_lv = 13,
                      exp = 4254,
                      property1 = {
                              20,
                              10,
                              100,
                              22,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              22,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              22,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              22,
                            },
                    },
              [14] = {
                      star_lv = 14,
                      exp = 5298,
                      property1 = {
                              20,
                              10,
                              100,
                              23,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              23,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              23,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              23,
                            },
                    },
              [15] = {
                      star_lv = 15,
                      exp = 6588,
                      property1 = {
                              20,
                              10,
                              100,
                              24,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              24,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              24,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              24,
                            },
                    },
              [16] = {
                      star_lv = 16,
                      exp = 8196,
                      property1 = {
                              20,
                              10,
                              100,
                              25,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              25,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              25,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              25,
                            },
                    },
              [17] = {
                      star_lv = 17,
                      exp = 10194,
                      property1 = {
                              20,
                              10,
                              100,
                              26,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              26,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              26,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              26,
                            },
                    },
              [18] = {
                      star_lv = 18,
                      exp = 12684,
                      property1 = {
                              20,
                              10,
                              100,
                              27,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              27,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              27,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              27,
                            },
                    },
              [19] = {
                      star_lv = 19,
                      exp = 15780,
                      property1 = {
                              20,
                              10,
                              100,
                              28,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              28,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              28,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              28,
                            },
                    },
              [20] = {
                      star_lv = 20,
                      exp = 0,
                      property1 = {
                              20,
                              10,
                              100,
                              29,
                            },
                      property2 = {
                              20,
                              10,
                              100,
                              29,
                            },
                      property3 = {
                              20,
                              10,
                              100,
                              29,
                            },
                      property4 = {
                              20,
                              10,
                              100,
                              29,
                            },
                    },
            }
return ConfigSyschild_star_exp;