--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.pb_8_pb')

PBPAYTOC = protobuf.Descriptor();
PBPAYTOC_ORDER_ID_FIELD = protobuf.FieldDescriptor();
PBPAYTOC_CHARGE_FIELD = protobuf.FieldDescriptor();
PBPAYTOS = protobuf.Descriptor();
PBPAYTOS_ORDER_ID_FIELD = protobuf.FieldDescriptor();
PBPAYTOS_RECEIPT_FIELD = protobuf.FieldDescriptor();
PBPAYTOS_CHARGE_FIELD = protobuf.FieldDescriptor();
PBPAYTOS_PAY_WAY_FIELD = protobuf.FieldDescriptor();
PBPAYFIRST = protobuf.Descriptor();
PBPAYFIRST_CHARGE_STATE_FIELD = protobuf.FieldDescriptor();

PBPAYTOC_ORDER_ID_FIELD.name = "order_id"
PBPAYTOC_ORDER_ID_FIELD.full_name = ".pbPayToC.order_id"
PBPAYTOC_ORDER_ID_FIELD.number = 1
PBPAYTOC_ORDER_ID_FIELD.index = 0
PBPAYTOC_ORDER_ID_FIELD.label = 1
PBPAYTOC_ORDER_ID_FIELD.has_default_value = false
PBPAYTOC_ORDER_ID_FIELD.default_value = ""
PBPAYTOC_ORDER_ID_FIELD.type = 9
PBPAYTOC_ORDER_ID_FIELD.cpp_type = 9

PBPAYTOC_CHARGE_FIELD.name = "charge"
PBPAYTOC_CHARGE_FIELD.full_name = ".pbPayToC.charge"
PBPAYTOC_CHARGE_FIELD.number = 2
PBPAYTOC_CHARGE_FIELD.index = 1
PBPAYTOC_CHARGE_FIELD.label = 1
PBPAYTOC_CHARGE_FIELD.has_default_value = false
PBPAYTOC_CHARGE_FIELD.default_value = ""
PBPAYTOC_CHARGE_FIELD.type = 9
PBPAYTOC_CHARGE_FIELD.cpp_type = 9

PBPAYTOC.name = "pbPayToC"
PBPAYTOC.full_name = ".pbPayToC"
PBPAYTOC.nested_types = {}
PBPAYTOC.enum_types = {}
PBPAYTOC.fields = {PBPAYTOC_ORDER_ID_FIELD, PBPAYTOC_CHARGE_FIELD}
PBPAYTOC.is_extendable = false
PBPAYTOC.extensions = {}
PBPAYTOS_ORDER_ID_FIELD.name = "order_id"
PBPAYTOS_ORDER_ID_FIELD.full_name = ".pbPayToS.order_id"
PBPAYTOS_ORDER_ID_FIELD.number = 1
PBPAYTOS_ORDER_ID_FIELD.index = 0
PBPAYTOS_ORDER_ID_FIELD.label = 1
PBPAYTOS_ORDER_ID_FIELD.has_default_value = false
PBPAYTOS_ORDER_ID_FIELD.default_value = ""
PBPAYTOS_ORDER_ID_FIELD.type = 9
PBPAYTOS_ORDER_ID_FIELD.cpp_type = 9

PBPAYTOS_RECEIPT_FIELD.name = "receipt"
PBPAYTOS_RECEIPT_FIELD.full_name = ".pbPayToS.receipt"
PBPAYTOS_RECEIPT_FIELD.number = 2
PBPAYTOS_RECEIPT_FIELD.index = 1
PBPAYTOS_RECEIPT_FIELD.label = 1
PBPAYTOS_RECEIPT_FIELD.has_default_value = false
PBPAYTOS_RECEIPT_FIELD.default_value = ""
PBPAYTOS_RECEIPT_FIELD.type = 9
PBPAYTOS_RECEIPT_FIELD.cpp_type = 9

PBPAYTOS_CHARGE_FIELD.name = "charge"
PBPAYTOS_CHARGE_FIELD.full_name = ".pbPayToS.charge"
PBPAYTOS_CHARGE_FIELD.number = 3
PBPAYTOS_CHARGE_FIELD.index = 2
PBPAYTOS_CHARGE_FIELD.label = 1
PBPAYTOS_CHARGE_FIELD.has_default_value = false
PBPAYTOS_CHARGE_FIELD.default_value = ""
PBPAYTOS_CHARGE_FIELD.type = 9
PBPAYTOS_CHARGE_FIELD.cpp_type = 9

PBPAYTOS_PAY_WAY_FIELD.name = "pay_way"
PBPAYTOS_PAY_WAY_FIELD.full_name = ".pbPayToS.pay_way"
PBPAYTOS_PAY_WAY_FIELD.number = 4
PBPAYTOS_PAY_WAY_FIELD.index = 3
PBPAYTOS_PAY_WAY_FIELD.label = 1
PBPAYTOS_PAY_WAY_FIELD.has_default_value = false
PBPAYTOS_PAY_WAY_FIELD.default_value = ""
PBPAYTOS_PAY_WAY_FIELD.type = 9
PBPAYTOS_PAY_WAY_FIELD.cpp_type = 9

PBPAYTOS.name = "pbPayToS"
PBPAYTOS.full_name = ".pbPayToS"
PBPAYTOS.nested_types = {}
PBPAYTOS.enum_types = {}
PBPAYTOS.fields = {PBPAYTOS_ORDER_ID_FIELD, PBPAYTOS_RECEIPT_FIELD, PBPAYTOS_CHARGE_FIELD, PBPAYTOS_PAY_WAY_FIELD}
PBPAYTOS.is_extendable = false
PBPAYTOS.extensions = {}
PBPAYFIRST_CHARGE_STATE_FIELD.name = "charge_state"
PBPAYFIRST_CHARGE_STATE_FIELD.full_name = ".pbPayFirst.charge_state"
PBPAYFIRST_CHARGE_STATE_FIELD.number = 1
PBPAYFIRST_CHARGE_STATE_FIELD.index = 0
PBPAYFIRST_CHARGE_STATE_FIELD.label = 1
PBPAYFIRST_CHARGE_STATE_FIELD.has_default_value = false
PBPAYFIRST_CHARGE_STATE_FIELD.default_value = 0
PBPAYFIRST_CHARGE_STATE_FIELD.type = 5
PBPAYFIRST_CHARGE_STATE_FIELD.cpp_type = 1

PBPAYFIRST.name = "pbPayFirst"
PBPAYFIRST.full_name = ".pbPayFirst"
PBPAYFIRST.nested_types = {}
PBPAYFIRST.enum_types = {}
PBPAYFIRST.fields = {PBPAYFIRST_CHARGE_STATE_FIELD}
PBPAYFIRST.is_extendable = false
PBPAYFIRST.extensions = {}

pbPayFirst = protobuf.Message(PBPAYFIRST)
pbPayToC = protobuf.Message(PBPAYTOC)
pbPayToS = protobuf.Message(PBPAYTOS)

