local NotifyDef = {
	NEW_ACTIVITY_NOTIFY = 11;
	NEW_LADN_REWARD_NOTICE = 21;
	NEW_GROW_FUND_NOTICE = 22;
	NEW_FIRST_RECHARGE_REWARD = 23;
	NEW_ACTIVITY_OPEN_SERVER_REWARD = 25;
	};
	
return NotifyDef;