--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local pb_common_pb = require("Protol.pb_common_pb")
module('Protol.pb_35_pb')

PBTIMESPENERGY = protobuf.Descriptor();
PBTIMESPENERGY_TIME_SP_FIELD = protobuf.FieldDescriptor();
PBTIMESPENERGY_TIME_ENERGY_FIELD = protobuf.FieldDescriptor();

PBTIMESPENERGY_TIME_SP_FIELD.name = "time_sp"
PBTIMESPENERGY_TIME_SP_FIELD.full_name = ".pbTimeSpEnergy.time_sp"
PBTIMESPENERGY_TIME_SP_FIELD.number = 1
PBTIMESPENERGY_TIME_SP_FIELD.index = 0
PBTIMESPENERGY_TIME_SP_FIELD.label = 2
PBTIMESPENERGY_TIME_SP_FIELD.has_default_value = false
PBTIMESPENERGY_TIME_SP_FIELD.default_value = 0
PBTIMESPENERGY_TIME_SP_FIELD.type = 5
PBTIMESPENERGY_TIME_SP_FIELD.cpp_type = 1

PBTIMESPENERGY_TIME_ENERGY_FIELD.name = "time_energy"
PBTIMESPENERGY_TIME_ENERGY_FIELD.full_name = ".pbTimeSpEnergy.time_energy"
PBTIMESPENERGY_TIME_ENERGY_FIELD.number = 2
PBTIMESPENERGY_TIME_ENERGY_FIELD.index = 1
PBTIMESPENERGY_TIME_ENERGY_FIELD.label = 2
PBTIMESPENERGY_TIME_ENERGY_FIELD.has_default_value = false
PBTIMESPENERGY_TIME_ENERGY_FIELD.default_value = 0
PBTIMESPENERGY_TIME_ENERGY_FIELD.type = 5
PBTIMESPENERGY_TIME_ENERGY_FIELD.cpp_type = 1

PBTIMESPENERGY.name = "pbTimeSpEnergy"
PBTIMESPENERGY.full_name = ".pbTimeSpEnergy"
PBTIMESPENERGY.nested_types = {}
PBTIMESPENERGY.enum_types = {}
PBTIMESPENERGY.fields = {PBTIMESPENERGY_TIME_SP_FIELD, PBTIMESPENERGY_TIME_ENERGY_FIELD}
PBTIMESPENERGY.is_extendable = false
PBTIMESPENERGY.extensions = {}

pbTimeSpEnergy = protobuf.Message(PBTIMESPENERGY)

