--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local pb_common_pb = require("Protol.pb_common_pb")
module('Protol.pb_25_pb')

PBTASK = protobuf.Descriptor();
PBTASK_ID_FIELD = protobuf.FieldDescriptor();
PBTASK_PROGRESS_FIELD = protobuf.FieldDescriptor();
PBTASK_STATUS_FIELD = protobuf.FieldDescriptor();
PBTASK_TIME_REMAIN_FIELD = protobuf.FieldDescriptor();
PBTASKLIST = protobuf.Descriptor();
PBTASKLIST_LIST_FIELD = protobuf.FieldDescriptor();

PBTASK_ID_FIELD.name = "id"
PBTASK_ID_FIELD.full_name = ".pbTask.id"
PBTASK_ID_FIELD.number = 1
PBTASK_ID_FIELD.index = 0
PBTASK_ID_FIELD.label = 2
PBTASK_ID_FIELD.has_default_value = false
PBTASK_ID_FIELD.default_value = 0
PBTASK_ID_FIELD.type = 5
PBTASK_ID_FIELD.cpp_type = 1

PBTASK_PROGRESS_FIELD.name = "progress"
PBTASK_PROGRESS_FIELD.full_name = ".pbTask.progress"
PBTASK_PROGRESS_FIELD.number = 2
PBTASK_PROGRESS_FIELD.index = 1
PBTASK_PROGRESS_FIELD.label = 2
PBTASK_PROGRESS_FIELD.has_default_value = false
PBTASK_PROGRESS_FIELD.default_value = 0
PBTASK_PROGRESS_FIELD.type = 5
PBTASK_PROGRESS_FIELD.cpp_type = 1

PBTASK_STATUS_FIELD.name = "status"
PBTASK_STATUS_FIELD.full_name = ".pbTask.status"
PBTASK_STATUS_FIELD.number = 3
PBTASK_STATUS_FIELD.index = 2
PBTASK_STATUS_FIELD.label = 2
PBTASK_STATUS_FIELD.has_default_value = false
PBTASK_STATUS_FIELD.default_value = 0
PBTASK_STATUS_FIELD.type = 5
PBTASK_STATUS_FIELD.cpp_type = 1

PBTASK_TIME_REMAIN_FIELD.name = "time_remain"
PBTASK_TIME_REMAIN_FIELD.full_name = ".pbTask.time_remain"
PBTASK_TIME_REMAIN_FIELD.number = 4
PBTASK_TIME_REMAIN_FIELD.index = 3
PBTASK_TIME_REMAIN_FIELD.label = 1
PBTASK_TIME_REMAIN_FIELD.has_default_value = false
PBTASK_TIME_REMAIN_FIELD.default_value = 0
PBTASK_TIME_REMAIN_FIELD.type = 5
PBTASK_TIME_REMAIN_FIELD.cpp_type = 1

PBTASK.name = "pbTask"
PBTASK.full_name = ".pbTask"
PBTASK.nested_types = {}
PBTASK.enum_types = {}
PBTASK.fields = {PBTASK_ID_FIELD, PBTASK_PROGRESS_FIELD, PBTASK_STATUS_FIELD, PBTASK_TIME_REMAIN_FIELD}
PBTASK.is_extendable = false
PBTASK.extensions = {}
PBTASKLIST_LIST_FIELD.name = "list"
PBTASKLIST_LIST_FIELD.full_name = ".pbTaskList.list"
PBTASKLIST_LIST_FIELD.number = 1
PBTASKLIST_LIST_FIELD.index = 0
PBTASKLIST_LIST_FIELD.label = 3
PBTASKLIST_LIST_FIELD.has_default_value = false
PBTASKLIST_LIST_FIELD.default_value = {}
PBTASKLIST_LIST_FIELD.message_type = PBTASK
PBTASKLIST_LIST_FIELD.type = 11
PBTASKLIST_LIST_FIELD.cpp_type = 10

PBTASKLIST.name = "pbTaskList"
PBTASKLIST.full_name = ".pbTaskList"
PBTASKLIST.nested_types = {}
PBTASKLIST.enum_types = {}
PBTASKLIST.fields = {PBTASKLIST_LIST_FIELD}
PBTASKLIST.is_extendable = false
PBTASKLIST.extensions = {}

pbTask = protobuf.Message(PBTASK)
pbTaskList = protobuf.Message(PBTASKLIST)

