
local ConfigSyschild_partner={
              ["1_1_1"] = {
                      sex = 1,
                      character = 1,
                      camp = 1,
                      partner_id = 41011,
                    },
              ["1_1_2"] = {
                      sex = 1,
                      character = 1,
                      camp = 2,
                      partner_id = 41012,
                    },
              ["1_1_3"] = {
                      sex = 1,
                      character = 1,
                      camp = 3,
                      partner_id = 41013,
                    },
              ["1_1_4"] = {
                      sex = 1,
                      character = 1,
                      camp = 4,
                      partner_id = 41014,
                    },
              ["1_1_5"] = {
                      sex = 1,
                      character = 1,
                      camp = 5,
                      partner_id = 41015,
                    },
              ["1_2_1"] = {
                      sex = 1,
                      character = 2,
                      camp = 1,
                      partner_id = 41021,
                    },
              ["1_2_2"] = {
                      sex = 1,
                      character = 2,
                      camp = 2,
                      partner_id = 41022,
                    },
              ["1_2_3"] = {
                      sex = 1,
                      character = 2,
                      camp = 3,
                      partner_id = 41023,
                    },
              ["1_2_4"] = {
                      sex = 1,
                      character = 2,
                      camp = 4,
                      partner_id = 41024,
                    },
              ["1_2_5"] = {
                      sex = 1,
                      character = 2,
                      camp = 5,
                      partner_id = 41025,
                    },
              ["1_3_1"] = {
                      sex = 1,
                      character = 3,
                      camp = 1,
                      partner_id = 41031,
                    },
              ["1_3_2"] = {
                      sex = 1,
                      character = 3,
                      camp = 2,
                      partner_id = 41032,
                    },
              ["1_3_3"] = {
                      sex = 1,
                      character = 3,
                      camp = 3,
                      partner_id = 41033,
                    },
              ["1_3_4"] = {
                      sex = 1,
                      character = 3,
                      camp = 4,
                      partner_id = 41034,
                    },
              ["1_3_5"] = {
                      sex = 1,
                      character = 3,
                      camp = 5,
                      partner_id = 41035,
                    },
              ["1_4_1"] = {
                      sex = 1,
                      character = 4,
                      camp = 1,
                      partner_id = 41041,
                    },
              ["1_4_2"] = {
                      sex = 1,
                      character = 4,
                      camp = 2,
                      partner_id = 41042,
                    },
              ["1_4_3"] = {
                      sex = 1,
                      character = 4,
                      camp = 3,
                      partner_id = 41043,
                    },
              ["1_4_4"] = {
                      sex = 1,
                      character = 4,
                      camp = 4,
                      partner_id = 41044,
                    },
              ["1_4_5"] = {
                      sex = 1,
                      character = 4,
                      camp = 5,
                      partner_id = 41045,
                    },
              ["2_1_1"] = {
                      sex = 2,
                      character = 1,
                      camp = 1,
                      partner_id = 42011,
                    },
              ["2_1_2"] = {
                      sex = 2,
                      character = 1,
                      camp = 2,
                      partner_id = 42012,
                    },
              ["2_1_3"] = {
                      sex = 2,
                      character = 1,
                      camp = 3,
                      partner_id = 42013,
                    },
              ["2_1_4"] = {
                      sex = 2,
                      character = 1,
                      camp = 4,
                      partner_id = 42014,
                    },
              ["2_1_5"] = {
                      sex = 2,
                      character = 1,
                      camp = 5,
                      partner_id = 42015,
                    },
              ["2_2_1"] = {
                      sex = 2,
                      character = 2,
                      camp = 1,
                      partner_id = 42021,
                    },
              ["2_2_2"] = {
                      sex = 2,
                      character = 2,
                      camp = 2,
                      partner_id = 42022,
                    },
              ["2_2_3"] = {
                      sex = 2,
                      character = 2,
                      camp = 3,
                      partner_id = 42023,
                    },
              ["2_2_4"] = {
                      sex = 2,
                      character = 2,
                      camp = 4,
                      partner_id = 42024,
                    },
              ["2_2_5"] = {
                      sex = 2,
                      character = 2,
                      camp = 5,
                      partner_id = 42025,
                    },
              ["2_3_1"] = {
                      sex = 2,
                      character = 3,
                      camp = 1,
                      partner_id = 42031,
                    },
              ["2_3_2"] = {
                      sex = 2,
                      character = 3,
                      camp = 2,
                      partner_id = 42032,
                    },
              ["2_3_3"] = {
                      sex = 2,
                      character = 3,
                      camp = 3,
                      partner_id = 42033,
                    },
              ["2_3_4"] = {
                      sex = 2,
                      character = 3,
                      camp = 4,
                      partner_id = 42034,
                    },
              ["2_3_5"] = {
                      sex = 2,
                      character = 3,
                      camp = 5,
                      partner_id = 42035,
                    },
              ["2_4_1"] = {
                      sex = 2,
                      character = 4,
                      camp = 1,
                      partner_id = 42041,
                    },
              ["2_4_2"] = {
                      sex = 2,
                      character = 4,
                      camp = 2,
                      partner_id = 42042,
                    },
              ["2_4_3"] = {
                      sex = 2,
                      character = 4,
                      camp = 3,
                      partner_id = 42043,
                    },
              ["2_4_4"] = {
                      sex = 2,
                      character = 4,
                      camp = 4,
                      partner_id = 42044,
                    },
              ["2_4_5"] = {
                      sex = 2,
                      character = 4,
                      camp = 5,
                      partner_id = 42045,
                    },
            }
return ConfigSyschild_partner;