
local ConfigSysfashion_level_up={
              [0] = {
                      level = 0,
                      cost = 500,
                      succeed_rate = 10000,
                      attributes = {
                              0,
                              0,
                              0,
                              0.03,
                              0.08,
                              0.04,
                              0.04,
                              16,
                              0.18,
                              0.18,
                              0.18,
                            },
                    },
              [1] = {
                      level = 1,
                      cost = 1500,
                      succeed_rate = 10000,
                      attributes = {
                              0,
                              0,
                              0,
                              0.05,
                              0.13,
                              0.06,
                              0.06,
                              20,
                              0.23,
                              0.23,
                              0.23,
                            },
                    },
              [2] = {
                      level = 2,
                      cost = 2500,
                      succeed_rate = 10000,
                      attributes = {
                              0,
                              0,
                              0,
                              0.07,
                              0.18,
                              0.08,
                              0.08,
                              25,
                              0.27,
                              0.27,
                              0.27,
                            },
                    },
              [3] = {
                      level = 3,
                      cost = 5000,
                      succeed_rate = 5000,
                      attributes = {
                              0,
                              0,
                              0,
                              0.09,
                              0.23,
                              0.1,
                              0.1,
                              29,
                              0.32,
                              0.32,
                              0.32,
                            },
                    },
              [4] = {
                      level = 4,
                      cost = 7500,
                      succeed_rate = 3333,
                      attributes = {
                              0,
                              0,
                              0,
                              0.11,
                              0.28,
                              0.12,
                              0.12,
                              33,
                              0.37,
                              0.37,
                              0.37,
                            },
                    },
              [5] = {
                      level = 5,
                      cost = 10000,
                      succeed_rate = 2500,
                      attributes = {
                              0,
                              0,
                              0,
                              0.13,
                              0.33,
                              0.14,
                              0.14,
                              37,
                              0.42,
                              0.42,
                              0.42,
                            },
                    },
              [6] = {
                      level = 6,
                      cost = 15000,
                      succeed_rate = 2000,
                      attributes = {
                              0,
                              0,
                              0,
                              0.15,
                              0.38,
                              0.16,
                              0.16,
                              42,
                              0.46,
                              0.46,
                              0.46,
                            },
                    },
              [7] = {
                      level = 7,
                      cost = 20000,
                      succeed_rate = 1666,
                      attributes = {
                              0,
                              0,
                              0,
                              0.17,
                              0.43,
                              0.18,
                              0.18,
                              46,
                              0.51,
                              0.51,
                              0.51,
                            },
                    },
              [8] = {
                      level = 8,
                      cost = 25000,
                      succeed_rate = 1250,
                      attributes = {
                              0,
                              0,
                              0,
                              0.19,
                              0.48,
                              0.2,
                              0.2,
                              50,
                              0.56,
                              0.56,
                              0.56,
                            },
                    },
              [9] = {
                      level = 9,
                      cost = 30000,
                      succeed_rate = 1000,
                      attributes = {
                              0,
                              0,
                              0,
                              0.21,
                              0.53,
                              0.22,
                              0.22,
                              54,
                              0.6,
                              0.6,
                              0.6,
                            },
                    },
              [10] = {
                      level = 10,
                      cost = 35000,
                      succeed_rate = 833,
                      attributes = {
                              0,
                              0,
                              0,
                              0.23,
                              0.58,
                              0.24,
                              0.24,
                              59,
                              0.65,
                              0.65,
                              0.65,
                            },
                    },
              [11] = {
                      level = 11,
                      cost = 40000,
                      succeed_rate = 625,
                      attributes = {
                              0,
                              0,
                              0,
                              0.25,
                              0.63,
                              0.26,
                              0.26,
                              63,
                              0.7,
                              0.7,
                              0.7,
                            },
                    },
              [12] = {
                      level = 12,
                      cost = 45000,
                      succeed_rate = 500,
                      attributes = {
                              0,
                              0,
                              0,
                              0.27,
                              0.68,
                              0.28,
                              0.28,
                              67,
                              0.74,
                              0.74,
                              0.74,
                            },
                    },
              [13] = {
                      level = 13,
                      cost = 50000,
                      succeed_rate = 333,
                      attributes = {
                              0,
                              0,
                              0,
                              0.29,
                              0.73,
                              0.3,
                              0.3,
                              72,
                              0.79,
                              0.79,
                              0.79,
                            },
                    },
              [14] = {
                      level = 14,
                      cost = 55000,
                      succeed_rate = 250,
                      attributes = {
                              0,
                              0,
                              0,
                              0.31,
                              0.78,
                              0.32,
                              0.32,
                              76,
                              0.84,
                              0.84,
                              0.84,
                            },
                    },
              [15] = {
                      level = 15,
                      cost = 0,
                      succeed_rate = 0,
                      attributes = {
                              0,
                              0,
                              0,
                              0.33,
                              0.83,
                              0.34,
                              0.34,
                              80,
                              0.89,
                              0.89,
                              0.89,
                            },
                    },
            }
return ConfigSysfashion_level_up;