local npc1=[[r_200231]]
local npc2=[[r_201441]]
local npc3=[[r_201611]]
local npc4=[[纯妃]]
local npc5=[[r_204042]]
local npc6=[[r_200911]]
local npc7=[[皇上]]
local npc8=[[r_200251]]
local npc9=[[r_201531]]
local npc10=[[r_200241]]
local npc11=[[r_203611]]
local npc12=[[r_202331]]
local npc13=[[r_201051]]
local npc14=[[r_202311]]
local npc15=[[r_200351]]

local ConfigSysnpc={
              [201] = {
                      model = npc1,
                      name = [[宫女]],
                      position = {
                              -256,
                              -304,
                              0,
                              0,
                            },
                      scale = 1,
                    },
              [202] = {
                      model = [[r_200131]],
                      name = [[太监]],
                      position = {
                              -152,
                              -164,
                              0,
                              0,
                            },
                      scale = 0.8,
                    },
              [203] = {
                      model = npc2,
                      name = [[可岚]],
                      position = {
                              -26,
                              -304,
                              0,
                              0,
                            },
                      scale = 1,
                    },
              [204] = {
                      model = [[r_201931]],
                      name = [[小禄子]],
                      position = {
                              88,
                              -164,
                              0,
                              0,
                            },
                      scale = 0.8,
                    },
              [205] = {
                      model = npc3,
                      name = npc4,
                      position = {
                              244,
                              -304,
                              0,
                              0,
                            },
                      scale = 1,
                    },
              [206] = {
                      model = npc5,
                      name = [[皇后]],
                      position = {
                              308,
                              -164,
                              0,
                              0,
                            },
                      scale = 0.8,
                    },
              [100] = {
                      model = npc6,
                      name = npc7,
                      position = {
                              -208.6,
                              -261.6,
                              0,
                              0,
                            },
                      scale = 54,
                    },
              [101] = {
                      model = [[r_200151]],
                      name = [[内务府太监]],
                      position = {
                              -208.6,
                              -261.6,
                              0,
                              0,
                            },
                      scale = 54,
                    },
              [1] = {
                      model = npc8,
                      name = [[魏莹莹]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [2] = {
                      model = npc9,
                      name = [[梁子枫]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [3] = {
                      model = [[r_202341]],
                      name = [[崇华]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [4] = {
                      model = [[r_204051]],
                      name = [[高贵妃]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [5] = {
                      model = npc5,
                      name = [[富察皇后]],
                      position = {
                              -180,
                              -23,
                              0,
                              0,
                            },
                      scale = 30,
                    },
              [6] = {
                      model = npc6,
                      name = npc7,
                      position = {
                              -70,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [7] = {
                      model = [[r_202751]],
                      name = [[庆嫔]],
                      position = {
                              60,
                              -23,
                              0,
                              0,
                            },
                      scale = 30,
                    },
              [8] = {
                      model = [[r_203751]],
                      name = [[舒束儿]],
                      position = {
                              200,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [9] = {
                      model = [[r_202821]],
                      name = [[傅恒]],
                      position = {
                              280,
                              -23,
                              0,
                              0,
                            },
                      scale = 30,
                    },
              [10] = {
                      model = npc3,
                      name = npc4,
                      position = {
                              -108.6,
                              161.6,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [11] = {
                      model = npc2,
                      name = [[愉贵人]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [12] = {
                      model = npc1,
                      name = [[嘉嫔]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [13] = {
                      model = [[r_200111]],
                      name = [[小桂子]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [14] = {
                      model = [[r_201951]],
                      name = [[凌总管]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [15] = {
                      model = npc10,
                      name = [[青兰]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [16] = {
                      model = npc8,
                      name = [[蕊儿]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [17] = {
                      model = npc8,
                      name = [[素心]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [18] = {
                      model = npc8,
                      name = [[锦心]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [19] = {
                      model = npc8,
                      name = [[葵儿]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [20] = {
                      model = npc8,
                      name = [[沁儿]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [21] = {
                      model = [[r_204411]],
                      name = [[戴佳氏]],
                      position = {
                              -180,
                              -23,
                              0,
                              0,
                            },
                      scale = 30,
                    },
              [22] = {
                      model = [[r_203651]],
                      name = [[李太医]],
                      position = {
                              -70,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [23] = {
                      model = npc11,
                      name = [[江太医]],
                      position = {
                              60,
                              -23,
                              0,
                              0,
                            },
                      scale = 30,
                    },
              [24] = {
                      model = [[r_202911]],
                      name = [[侍卫统领]],
                      position = {
                              200,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [25] = {
                      model = npc12,
                      name = [[侍卫]],
                      position = {
                              280,
                              -23,
                              0,
                              0,
                            },
                      scale = 30,
                    },
              [26] = {
                      model = npc13,
                      name = [[管事嬷嬷]],
                      position = {
                              -208.6,
                              -261.6,
                              0,
                              0,
                            },
                      scale = 54,
                    },
              [27] = {
                      model = [[r_201521]],
                      name = [[太医]],
                      position = {
                              -208.6,
                              -261.6,
                              0,
                              0,
                            },
                      scale = 60,
                    },
              [28] = {
                      model = [[r_200221]],
                      name = [[小宫女]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [29] = {
                      model = [[r_200121]],
                      name = [[小太监]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [30] = {
                      model = npc13,
                      name = [[稳婆]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [31] = {
                      model = [[r_201311]],
                      name = [[太后]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [32] = {
                      model = npc2,
                      name = [[愉嫔]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [33] = {
                      model = [[r_200211]],
                      name = [[小翠]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [34] = {
                      model = npc8,
                      name = [[庆嫔侍女]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [35] = {
                      model = [[r_202531]],
                      name = [[少年]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [36] = {
                      model = [[r_204041]],
                      name = [[少年福康安]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [37] = {
                      model = npc1,
                      name = [[嘉嫔侍女]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [38] = {
                      model = npc1,
                      name = [[宫女小福]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [39] = {
                      model = npc1,
                      name = [[宫女小球]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [40] = {
                      model = [[r_203741]],
                      name = [[女人]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [41] = {
                      model = [[r_204421]],
                      name = [[若彤]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [42] = {
                      model = npc14,
                      name = [[弘时]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [43] = {
                      model = [[r_202831]],
                      name = [[古塔王子]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [44] = {
                      model = [[r_200831]],
                      name = [[涵香郡主]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [45] = {
                      model = [[r_201021]],
                      name = [[容晴]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [46] = {
                      model = [[r_204451]],
                      name = [[魏贵人]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [47] = {
                      model = [[r_204441]],
                      name = [[和敬公主]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [48] = {
                      model = npc14,
                      name = [[大阿哥]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [49] = {
                      model = [[r_201321]],
                      name = [[老疯妇]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [50] = {
                      model = [[r_202841]],
                      name = [[九门提督]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [51] = {
                      model = [[r_200931]],
                      name = [[纪昀]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [52] = {
                      model = [[r_204011]],
                      name = [[富察瑶依]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [53] = {
                      model = npc12,
                      name = [[异族武士甲]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [54] = {
                      model = npc12,
                      name = [[异族武士乙]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [55] = {
                      model = npc12,
                      name = [[异族武士丙]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [56] = {
                      model = npc10,
                      name = [[公主侍女]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [57] = {
                      model = npc11,
                      name = [[户部尚书]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [58] = {
                      model = [[r_203631]],
                      name = [[军机大臣]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [59] = {
                      model = [[r_203911]],
                      name = [[血滴子暗卫]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [60] = {
                      model = [[r_203941]],
                      name = [[神秘人]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [61] = {
                      model = [[r_200621]],
                      name = [[果子]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [62] = {
                      model = [[r_200331]],
                      name = [[考官]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [63] = {
                      model = npc15,
                      name = [[纨绔公子]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [64] = {
                      model = [[r_204031]],
                      name = [[景娴]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [65] = {
                      model = [[r_203621]],
                      name = [[富察大人]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [66] = {
                      model = [[r_200651]],
                      name = [[稳婆儿子]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [67] = {
                      model = [[r_200641]],
                      name = [[二阿哥]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [68] = {
                      model = [[r_200631]],
                      name = [[小二]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [69] = {
                      model = npc15,
                      name = [[高老板]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [70] = {
                      model = npc9,
                      name = [[刘太医]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [71] = {
                      model = npc15,
                      name = [[高斌]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [72] = {
                      model = npc14,
                      name = [[狱卒]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [73] = {
                      model = [[r_200941]],
                      name = [[萨满法师]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
              [74] = {
                      model = [[r_200611]],
                      name = [[大阿哥 ]],
                      position = {
                              -300,
                              -203,
                              0,
                              0,
                            },
                      scale = 42,
                    },
            }
return ConfigSysnpc;