
local ConfigSystalent_other_attribute={
              ["2_1_1"] = {
                      type = 2,
                      quality = 1,
                      attri = 1,
                      min = 30,
                      max = 44,
                    },
              ["2_2_1"] = {
                      type = 2,
                      quality = 2,
                      attri = 1,
                      min = 45,
                      max = 67,
                    },
              ["2_3_1"] = {
                      type = 2,
                      quality = 3,
                      attri = 1,
                      min = 60,
                      max = 90,
                    },
              ["2_4_1"] = {
                      type = 2,
                      quality = 4,
                      attri = 1,
                      min = 90,
                      max = 134,
                    },
              ["2_5_1"] = {
                      type = 2,
                      quality = 5,
                      attri = 1,
                      min = 119,
                      max = 179,
                    },
              ["2_6_1"] = {
                      type = 2,
                      quality = 6,
                      attri = 1,
                      min = 150,
                      max = 224,
                    },
              ["2_1_2"] = {
                      type = 2,
                      quality = 1,
                      attri = 2,
                      min = 3,
                      max = 5,
                    },
              ["2_2_2"] = {
                      type = 2,
                      quality = 2,
                      attri = 2,
                      min = 5,
                      max = 7,
                    },
              ["2_3_2"] = {
                      type = 2,
                      quality = 3,
                      attri = 2,
                      min = 6,
                      max = 8,
                    },
              ["2_4_2"] = {
                      type = 2,
                      quality = 4,
                      attri = 2,
                      min = 9,
                      max = 13,
                    },
              ["2_5_2"] = {
                      type = 2,
                      quality = 5,
                      attri = 2,
                      min = 12,
                      max = 18,
                    },
              ["2_6_2"] = {
                      type = 2,
                      quality = 6,
                      attri = 2,
                      min = 15,
                      max = 23,
                    },
              ["2_1_3"] = {
                      type = 2,
                      quality = 1,
                      attri = 3,
                      min = 3,
                      max = 5,
                    },
              ["2_2_3"] = {
                      type = 2,
                      quality = 2,
                      attri = 3,
                      min = 5,
                      max = 7,
                    },
              ["2_3_3"] = {
                      type = 2,
                      quality = 3,
                      attri = 3,
                      min = 6,
                      max = 8,
                    },
              ["2_4_3"] = {
                      type = 2,
                      quality = 4,
                      attri = 3,
                      min = 9,
                      max = 13,
                    },
              ["2_5_3"] = {
                      type = 2,
                      quality = 5,
                      attri = 3,
                      min = 12,
                      max = 18,
                    },
              ["2_6_3"] = {
                      type = 2,
                      quality = 6,
                      attri = 3,
                      min = 15,
                      max = 23,
                    },
              ["2_1_8"] = {
                      type = 2,
                      quality = 1,
                      attri = 8,
                      min = 1,
                      max = 1,
                    },
              ["2_2_8"] = {
                      type = 2,
                      quality = 2,
                      attri = 8,
                      min = 2,
                      max = 2,
                    },
              ["2_3_8"] = {
                      type = 2,
                      quality = 3,
                      attri = 8,
                      min = 2,
                      max = 4,
                    },
              ["2_4_8"] = {
                      type = 2,
                      quality = 4,
                      attri = 8,
                      min = 3,
                      max = 5,
                    },
              ["2_5_8"] = {
                      type = 2,
                      quality = 5,
                      attri = 8,
                      min = 5,
                      max = 7,
                    },
              ["2_6_8"] = {
                      type = 2,
                      quality = 6,
                      attri = 8,
                      min = 6,
                      max = 8,
                    },
              ["2_1_9"] = {
                      type = 2,
                      quality = 1,
                      attri = 9,
                      min = 0.01,
                      max = 0.02,
                    },
              ["2_2_9"] = {
                      type = 2,
                      quality = 2,
                      attri = 9,
                      min = 0.02,
                      max = 0.03,
                    },
              ["2_3_9"] = {
                      type = 2,
                      quality = 3,
                      attri = 9,
                      min = 0.02,
                      max = 0.03,
                    },
              ["2_4_9"] = {
                      type = 2,
                      quality = 4,
                      attri = 9,
                      min = 0.03,
                      max = 0.05,
                    },
              ["2_5_9"] = {
                      type = 2,
                      quality = 5,
                      attri = 9,
                      min = 0.04,
                      max = 0.07,
                    },
              ["2_6_9"] = {
                      type = 2,
                      quality = 6,
                      attri = 9,
                      min = 0.06,
                      max = 0.08,
                    },
              ["2_1_10"] = {
                      type = 2,
                      quality = 1,
                      attri = 10,
                      min = 0.01,
                      max = 0.02,
                    },
              ["2_2_10"] = {
                      type = 2,
                      quality = 2,
                      attri = 10,
                      min = 0.02,
                      max = 0.03,
                    },
              ["2_3_10"] = {
                      type = 2,
                      quality = 3,
                      attri = 10,
                      min = 0.02,
                      max = 0.03,
                    },
              ["2_4_10"] = {
                      type = 2,
                      quality = 4,
                      attri = 10,
                      min = 0.03,
                      max = 0.05,
                    },
              ["2_5_10"] = {
                      type = 2,
                      quality = 5,
                      attri = 10,
                      min = 0.04,
                      max = 0.07,
                    },
              ["2_6_10"] = {
                      type = 2,
                      quality = 6,
                      attri = 10,
                      min = 0.06,
                      max = 0.08,
                    },
              ["2_1_11"] = {
                      type = 2,
                      quality = 1,
                      attri = 11,
                      min = 0.01,
                      max = 0.02,
                    },
              ["2_2_11"] = {
                      type = 2,
                      quality = 2,
                      attri = 11,
                      min = 0.02,
                      max = 0.03,
                    },
              ["2_3_11"] = {
                      type = 2,
                      quality = 3,
                      attri = 11,
                      min = 0.02,
                      max = 0.03,
                    },
              ["2_4_11"] = {
                      type = 2,
                      quality = 4,
                      attri = 11,
                      min = 0.03,
                      max = 0.05,
                    },
              ["2_5_11"] = {
                      type = 2,
                      quality = 5,
                      attri = 11,
                      min = 0.04,
                      max = 0.07,
                    },
              ["2_6_11"] = {
                      type = 2,
                      quality = 6,
                      attri = 11,
                      min = 0.06,
                      max = 0.08,
                    },
              ["3_1_1"] = {
                      type = 3,
                      quality = 1,
                      attri = 1,
                      min = 45,
                      max = 132,
                    },
              ["3_2_1"] = {
                      type = 3,
                      quality = 2,
                      attri = 1,
                      min = 68,
                      max = 201,
                    },
              ["3_3_1"] = {
                      type = 3,
                      quality = 3,
                      attri = 1,
                      min = 90,
                      max = 270,
                    },
              ["3_4_1"] = {
                      type = 3,
                      quality = 4,
                      attri = 1,
                      min = 135,
                      max = 402,
                    },
              ["3_5_1"] = {
                      type = 3,
                      quality = 5,
                      attri = 1,
                      min = 179,
                      max = 537,
                    },
              ["3_6_1"] = {
                      type = 3,
                      quality = 6,
                      attri = 1,
                      min = 225,
                      max = 672,
                    },
              ["3_1_2"] = {
                      type = 3,
                      quality = 1,
                      attri = 2,
                      min = 5,
                      max = 15,
                    },
              ["3_2_2"] = {
                      type = 3,
                      quality = 2,
                      attri = 2,
                      min = 8,
                      max = 21,
                    },
              ["3_3_2"] = {
                      type = 3,
                      quality = 3,
                      attri = 2,
                      min = 9,
                      max = 24,
                    },
              ["3_4_2"] = {
                      type = 3,
                      quality = 4,
                      attri = 2,
                      min = 14,
                      max = 39,
                    },
              ["3_5_2"] = {
                      type = 3,
                      quality = 5,
                      attri = 2,
                      min = 18,
                      max = 54,
                    },
              ["3_6_2"] = {
                      type = 3,
                      quality = 6,
                      attri = 2,
                      min = 23,
                      max = 69,
                    },
              ["3_1_3"] = {
                      type = 3,
                      quality = 1,
                      attri = 3,
                      min = 5,
                      max = 15,
                    },
              ["3_2_3"] = {
                      type = 3,
                      quality = 2,
                      attri = 3,
                      min = 8,
                      max = 21,
                    },
              ["3_3_3"] = {
                      type = 3,
                      quality = 3,
                      attri = 3,
                      min = 9,
                      max = 24,
                    },
              ["3_4_3"] = {
                      type = 3,
                      quality = 4,
                      attri = 3,
                      min = 14,
                      max = 39,
                    },
              ["3_5_3"] = {
                      type = 3,
                      quality = 5,
                      attri = 3,
                      min = 18,
                      max = 54,
                    },
              ["3_6_3"] = {
                      type = 3,
                      quality = 6,
                      attri = 3,
                      min = 23,
                      max = 69,
                    },
              ["3_1_4"] = {
                      type = 3,
                      quality = 1,
                      attri = 4,
                      min = 0.02,
                      max = 0.03,
                    },
              ["3_2_4"] = {
                      type = 3,
                      quality = 2,
                      attri = 4,
                      min = 0.02,
                      max = 0.03,
                    },
              ["3_3_4"] = {
                      type = 3,
                      quality = 3,
                      attri = 4,
                      min = 0.02,
                      max = 0.06,
                    },
              ["3_4_4"] = {
                      type = 3,
                      quality = 4,
                      attri = 4,
                      min = 0.03,
                      max = 0.09,
                    },
              ["3_5_4"] = {
                      type = 3,
                      quality = 5,
                      attri = 4,
                      min = 0.05,
                      max = 0.12,
                    },
              ["3_6_4"] = {
                      type = 3,
                      quality = 6,
                      attri = 4,
                      min = 0.05,
                      max = 0.15,
                    },
              ["3_1_5"] = {
                      type = 3,
                      quality = 1,
                      attri = 5,
                      min = 0.02,
                      max = 0.03,
                    },
              ["3_2_5"] = {
                      type = 3,
                      quality = 2,
                      attri = 5,
                      min = 0.02,
                      max = 0.06,
                    },
              ["3_3_5"] = {
                      type = 3,
                      quality = 3,
                      attri = 5,
                      min = 0.03,
                      max = 0.09,
                    },
              ["3_4_5"] = {
                      type = 3,
                      quality = 4,
                      attri = 5,
                      min = 0.05,
                      max = 0.12,
                    },
              ["3_5_5"] = {
                      type = 3,
                      quality = 5,
                      attri = 5,
                      min = 0.06,
                      max = 0.15,
                    },
              ["3_6_5"] = {
                      type = 3,
                      quality = 6,
                      attri = 5,
                      min = 0.06,
                      max = 0.21,
                    },
              ["3_1_6"] = {
                      type = 3,
                      quality = 1,
                      attri = 6,
                      min = 0.02,
                      max = 0.03,
                    },
              ["3_2_6"] = {
                      type = 3,
                      quality = 2,
                      attri = 6,
                      min = 0.02,
                      max = 0.06,
                    },
              ["3_3_6"] = {
                      type = 3,
                      quality = 3,
                      attri = 6,
                      min = 0.03,
                      max = 0.06,
                    },
              ["3_4_6"] = {
                      type = 3,
                      quality = 4,
                      attri = 6,
                      min = 0.03,
                      max = 0.09,
                    },
              ["3_5_6"] = {
                      type = 3,
                      quality = 5,
                      attri = 6,
                      min = 0.05,
                      max = 0.12,
                    },
              ["3_6_6"] = {
                      type = 3,
                      quality = 6,
                      attri = 6,
                      min = 0.06,
                      max = 0.18,
                    },
              ["3_1_7"] = {
                      type = 3,
                      quality = 1,
                      attri = 7,
                      min = 0.02,
                      max = 0.03,
                    },
              ["3_2_7"] = {
                      type = 3,
                      quality = 2,
                      attri = 7,
                      min = 0.02,
                      max = 0.06,
                    },
              ["3_3_7"] = {
                      type = 3,
                      quality = 3,
                      attri = 7,
                      min = 0.03,
                      max = 0.06,
                    },
              ["3_4_7"] = {
                      type = 3,
                      quality = 4,
                      attri = 7,
                      min = 0.03,
                      max = 0.09,
                    },
              ["3_5_7"] = {
                      type = 3,
                      quality = 5,
                      attri = 7,
                      min = 0.05,
                      max = 0.12,
                    },
              ["3_6_7"] = {
                      type = 3,
                      quality = 6,
                      attri = 7,
                      min = 0.06,
                      max = 0.18,
                    },
              ["3_1_8"] = {
                      type = 3,
                      quality = 1,
                      attri = 8,
                      min = 1.5,
                      max = 3,
                    },
              ["3_2_8"] = {
                      type = 3,
                      quality = 2,
                      attri = 8,
                      min = 3,
                      max = 6,
                    },
              ["3_3_8"] = {
                      type = 3,
                      quality = 3,
                      attri = 8,
                      min = 3,
                      max = 12,
                    },
              ["3_4_8"] = {
                      type = 3,
                      quality = 4,
                      attri = 8,
                      min = 4.5,
                      max = 15,
                    },
              ["3_5_8"] = {
                      type = 3,
                      quality = 5,
                      attri = 8,
                      min = 7.5,
                      max = 21,
                    },
              ["3_6_8"] = {
                      type = 3,
                      quality = 6,
                      attri = 8,
                      min = 9,
                      max = 24,
                    },
              ["3_1_9"] = {
                      type = 3,
                      quality = 1,
                      attri = 9,
                      min = 0.02,
                      max = 0.06,
                    },
              ["3_2_9"] = {
                      type = 3,
                      quality = 2,
                      attri = 9,
                      min = 0.03,
                      max = 0.09,
                    },
              ["3_3_9"] = {
                      type = 3,
                      quality = 3,
                      attri = 9,
                      min = 0.03,
                      max = 0.09,
                    },
              ["3_4_9"] = {
                      type = 3,
                      quality = 4,
                      attri = 9,
                      min = 0.05,
                      max = 0.15,
                    },
              ["3_5_9"] = {
                      type = 3,
                      quality = 5,
                      attri = 9,
                      min = 0.06,
                      max = 0.21,
                    },
              ["3_6_9"] = {
                      type = 3,
                      quality = 6,
                      attri = 9,
                      min = 0.09,
                      max = 0.24,
                    },
              ["3_1_10"] = {
                      type = 3,
                      quality = 1,
                      attri = 10,
                      min = 0.02,
                      max = 0.06,
                    },
              ["3_2_10"] = {
                      type = 3,
                      quality = 2,
                      attri = 10,
                      min = 0.03,
                      max = 0.09,
                    },
              ["3_3_10"] = {
                      type = 3,
                      quality = 3,
                      attri = 10,
                      min = 0.03,
                      max = 0.09,
                    },
              ["3_4_10"] = {
                      type = 3,
                      quality = 4,
                      attri = 10,
                      min = 0.05,
                      max = 0.15,
                    },
              ["3_5_10"] = {
                      type = 3,
                      quality = 5,
                      attri = 10,
                      min = 0.06,
                      max = 0.21,
                    },
              ["3_6_10"] = {
                      type = 3,
                      quality = 6,
                      attri = 10,
                      min = 0.09,
                      max = 0.24,
                    },
              ["3_1_11"] = {
                      type = 3,
                      quality = 1,
                      attri = 11,
                      min = 0.02,
                      max = 0.06,
                    },
              ["3_2_11"] = {
                      type = 3,
                      quality = 2,
                      attri = 11,
                      min = 0.03,
                      max = 0.09,
                    },
              ["3_3_11"] = {
                      type = 3,
                      quality = 3,
                      attri = 11,
                      min = 0.03,
                      max = 0.09,
                    },
              ["3_4_11"] = {
                      type = 3,
                      quality = 4,
                      attri = 11,
                      min = 0.05,
                      max = 0.15,
                    },
              ["3_5_11"] = {
                      type = 3,
                      quality = 5,
                      attri = 11,
                      min = 0.06,
                      max = 0.21,
                    },
              ["3_6_11"] = {
                      type = 3,
                      quality = 6,
                      attri = 11,
                      min = 0.09,
                      max = 0.24,
                    },
            }
return ConfigSystalent_other_attribute;