
local ConfigSyspromote_arena_score_award={
              [1099] = {
                      score = 1099,
                      arena_coin = 5,
                      gold = 5,
                      arena_coin_lose = 2,
                      win_score = 10,
                    },
              [1199] = {
                      score = 1199,
                      arena_coin = 6,
                      gold = 10,
                      arena_coin_lose = 2,
                      win_score = 8,
                    },
              [1349] = {
                      score = 1349,
                      arena_coin = 7,
                      gold = 15,
                      arena_coin_lose = 2,
                      win_score = 6,
                    },
              [1499] = {
                      score = 1499,
                      arena_coin = 8,
                      gold = 20,
                      arena_coin_lose = 3,
                      win_score = 5,
                    },
              [1799] = {
                      score = 1799,
                      arena_coin = 9,
                      gold = 25,
                      arena_coin_lose = 3,
                      win_score = 4,
                    },
              [2399] = {
                      score = 2399,
                      arena_coin = 10,
                      gold = 30,
                      arena_coin_lose = 4,
                      win_score = 3,
                    },
              [2999] = {
                      score = 2999,
                      arena_coin = 10,
                      gold = 35,
                      arena_coin_lose = 4,
                      win_score = 2,
                    },
              [3599] = {
                      score = 3599,
                      arena_coin = 10,
                      gold = 40,
                      arena_coin_lose = 4,
                      win_score = 1,
                    },
              [4199] = {
                      score = 4199,
                      arena_coin = 10,
                      gold = 45,
                      arena_coin_lose = 4,
                      win_score = 1,
                    },
              [4799] = {
                      score = 4799,
                      arena_coin = 10,
                      gold = 50,
                      arena_coin_lose = 4,
                      win_score = 1,
                    },
              [5399] = {
                      score = 5399,
                      arena_coin = 10,
                      gold = 55,
                      arena_coin_lose = 4,
                      win_score = 1,
                    },
              [5999] = {
                      score = 5999,
                      arena_coin = 10,
                      gold = 60,
                      arena_coin_lose = 4,
                      win_score = 1,
                    },
              [9998] = {
                      score = 9998,
                      arena_coin = 10,
                      gold = 65,
                      arena_coin_lose = 4,
                      win_score = 1,
                    },
            }
return ConfigSyspromote_arena_score_award;