local skill_bullet1=[[Bullet]]
local skill_bullet2=[[skill_1_fire_point]]
local skill_bullet3=[[]]
local skill_bullet4=[[skill_2_fire_point]]
local skill_bullet5=[[skill_3_fire_point]]
local skill_bullet6=[[skill_2_1_fire_point]]
local skill_bullet7=[[skill_2_2_fire_point]]
local skill_bullet8=[[skill_3_1_fire_point]]
local skill_bullet9=[[skill_3_2_fire_point]]
local skill_bullet10=[[skill_3_3_fire_point]]
local skill_bullet11=[[skill_3_4_fire_point]]
local skill_bullet12=[[EjectBullet]]

local ConfigSysskill_bullet={
              [10110] = {
                      cls = skill_bullet1,
                      speed = 10,
                      acceleration_y = 0,
                      fire_point = skill_bullet2,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10120] = {
                      cls = skill_bullet1,
                      speed = 10,
                      acceleration_y = 0,
                      fire_point = skill_bullet4,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10130] = {
                      cls = skill_bullet1,
                      speed = 10,
                      acceleration_y = 0,
                      fire_point = skill_bullet5,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10210] = {
                      cls = skill_bullet1,
                      speed = 10,
                      acceleration_y = 0.1,
                      fire_point = skill_bullet2,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10220] = {
                      cls = skill_bullet1,
                      speed = 10,
                      acceleration_y = 0.1,
                      fire_point = skill_bullet4,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10230] = {
                      cls = skill_bullet1,
                      speed = 10,
                      acceleration_y = 0.1,
                      fire_point = skill_bullet5,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10310] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet2,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10320] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet4,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10330] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet5,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10410] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0.1,
                      fire_point = skill_bullet2,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10420] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0.1,
                      fire_point = skill_bullet4,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10430] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0.1,
                      fire_point = skill_bullet5,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10511] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = [[skill_1_1_fire_point]],
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10512] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = [[skill_1_2_fire_point]],
                      hit_point = skill_bullet3,
                      effect = 22,
                    },
              [10521] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet6,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10522] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet7,
                      hit_point = skill_bullet3,
                      effect = 22,
                    },
              [10523] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = [[skill_2_3_fire_point]],
                      hit_point = skill_bullet3,
                      effect = 23,
                    },
              [10524] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = [[skill_2_4_fire_point]],
                      hit_point = skill_bullet3,
                      effect = 24,
                    },
              [10531] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet8,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10532] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet9,
                      hit_point = skill_bullet3,
                      effect = 22,
                    },
              [10533] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet10,
                      hit_point = skill_bullet3,
                      effect = 23,
                    },
              [10534] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet11,
                      hit_point = skill_bullet3,
                      effect = 24,
                    },
              [10621] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0.1,
                      fire_point = skill_bullet6,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10622] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0.1,
                      fire_point = skill_bullet7,
                      hit_point = skill_bullet3,
                      effect = 22,
                    },
              [10631] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0.1,
                      fire_point = skill_bullet8,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10632] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0.1,
                      fire_point = skill_bullet9,
                      hit_point = skill_bullet3,
                      effect = 22,
                    },
              [10633] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0.1,
                      fire_point = skill_bullet10,
                      hit_point = skill_bullet3,
                      effect = 23,
                    },
              [10634] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0.1,
                      fire_point = skill_bullet11,
                      hit_point = skill_bullet3,
                      effect = 24,
                    },
              [10724] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = [[skill_2_2_1_fire_point]],
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10725] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = [[skill_2_2_2_fire_point]],
                      hit_point = skill_bullet3,
                      effect = 22,
                    },
              [10810] = {
                      cls = skill_bullet12,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet2,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10820] = {
                      cls = skill_bullet12,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet4,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10830] = {
                      cls = skill_bullet12,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet5,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10931] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet8,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10932] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet9,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
              [10933] = {
                      cls = skill_bullet1,
                      speed = 20,
                      acceleration_y = 0,
                      fire_point = skill_bullet10,
                      hit_point = skill_bullet3,
                      effect = 21,
                    },
            }
return ConfigSysskill_bullet;