--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local pb_common_pb = require("Protol.pb_common_pb")
module('Protol.pb_29_pb')

PBGUIDEINFO = protobuf.Descriptor();
PBGUIDEINFO_INFO_FIELD = protobuf.FieldDescriptor();
PBGUIDE = protobuf.Descriptor();
PBGUIDE_ID_FIELD = protobuf.FieldDescriptor();
PBGUIDE_STEP_FIELD = protobuf.FieldDescriptor();

PBGUIDEINFO_INFO_FIELD.name = "info"
PBGUIDEINFO_INFO_FIELD.full_name = ".pbGuideInfo.info"
PBGUIDEINFO_INFO_FIELD.number = 1
PBGUIDEINFO_INFO_FIELD.index = 0
PBGUIDEINFO_INFO_FIELD.label = 3
PBGUIDEINFO_INFO_FIELD.has_default_value = false
PBGUIDEINFO_INFO_FIELD.default_value = {}
PBGUIDEINFO_INFO_FIELD.message_type = PBGUIDE
PBGUIDEINFO_INFO_FIELD.type = 11
PBGUIDEINFO_INFO_FIELD.cpp_type = 10

PBGUIDEINFO.name = "pbGuideInfo"
PBGUIDEINFO.full_name = ".pbGuideInfo"
PBGUIDEINFO.nested_types = {}
PBGUIDEINFO.enum_types = {}
PBGUIDEINFO.fields = {PBGUIDEINFO_INFO_FIELD}
PBGUIDEINFO.is_extendable = false
PBGUIDEINFO.extensions = {}
PBGUIDE_ID_FIELD.name = "id"
PBGUIDE_ID_FIELD.full_name = ".pbGuide.id"
PBGUIDE_ID_FIELD.number = 1
PBGUIDE_ID_FIELD.index = 0
PBGUIDE_ID_FIELD.label = 1
PBGUIDE_ID_FIELD.has_default_value = false
PBGUIDE_ID_FIELD.default_value = 0
PBGUIDE_ID_FIELD.type = 5
PBGUIDE_ID_FIELD.cpp_type = 1

PBGUIDE_STEP_FIELD.name = "step"
PBGUIDE_STEP_FIELD.full_name = ".pbGuide.step"
PBGUIDE_STEP_FIELD.number = 2
PBGUIDE_STEP_FIELD.index = 1
PBGUIDE_STEP_FIELD.label = 1
PBGUIDE_STEP_FIELD.has_default_value = false
PBGUIDE_STEP_FIELD.default_value = 0
PBGUIDE_STEP_FIELD.type = 5
PBGUIDE_STEP_FIELD.cpp_type = 1

PBGUIDE.name = "pbGuide"
PBGUIDE.full_name = ".pbGuide"
PBGUIDE.nested_types = {}
PBGUIDE.enum_types = {}
PBGUIDE.fields = {PBGUIDE_ID_FIELD, PBGUIDE_STEP_FIELD}
PBGUIDE.is_extendable = false
PBGUIDE.extensions = {}

pbGuide = protobuf.Message(PBGUIDE)
pbGuideInfo = protobuf.Message(PBGUIDEINFO)

