--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local pb_common_pb = require("Protol.pb_common_pb")
module('Protol.pb_23_pb')

PBSHOP = protobuf.Descriptor();
PBSHOP_ID_FIELD = protobuf.FieldDescriptor();
PBSHOP_PRICE_FIELD = protobuf.FieldDescriptor();
PBSHOP_REMAIN_COUNT_FIELD = protobuf.FieldDescriptor();
PBSHOP_SELL_START_TIME_FIELD = protobuf.FieldDescriptor();
PBSHOP_SELL_END_TIME_FIELD = protobuf.FieldDescriptor();
PBSHOP_REFRESH_TIME_FIELD = protobuf.FieldDescriptor();
PBSHOPLIST = protobuf.Descriptor();
PBSHOPLIST_FIRST_TYPE_FIELD = protobuf.FieldDescriptor();
PBSHOPLIST_SECOND_TYPE_FIELD = protobuf.FieldDescriptor();
PBSHOPLIST_LIST_FIELD = protobuf.FieldDescriptor();
PBSHOPGETLIST = protobuf.Descriptor();
PBSHOPGETLIST_FIRST_TYPE_FIELD = protobuf.FieldDescriptor();
PBSHOPGETLIST_SECOND_TYPE_FIELD = protobuf.FieldDescriptor();
PBSHOPBUY = protobuf.Descriptor();
PBSHOPBUY_FIRST_TYPE_FIELD = protobuf.FieldDescriptor();
PBSHOPBUY_SECOND_TYPE_FIELD = protobuf.FieldDescriptor();
PBSHOPBUY_ID_FIELD = protobuf.FieldDescriptor();
PBSHOPBUY_COUNT_FIELD = protobuf.FieldDescriptor();

PBSHOP_ID_FIELD.name = "id"
PBSHOP_ID_FIELD.full_name = ".pbShop.id"
PBSHOP_ID_FIELD.number = 1
PBSHOP_ID_FIELD.index = 0
PBSHOP_ID_FIELD.label = 2
PBSHOP_ID_FIELD.has_default_value = false
PBSHOP_ID_FIELD.default_value = 0
PBSHOP_ID_FIELD.type = 5
PBSHOP_ID_FIELD.cpp_type = 1

PBSHOP_PRICE_FIELD.name = "price"
PBSHOP_PRICE_FIELD.full_name = ".pbShop.price"
PBSHOP_PRICE_FIELD.number = 2
PBSHOP_PRICE_FIELD.index = 1
PBSHOP_PRICE_FIELD.label = 2
PBSHOP_PRICE_FIELD.has_default_value = false
PBSHOP_PRICE_FIELD.default_value = 0
PBSHOP_PRICE_FIELD.type = 5
PBSHOP_PRICE_FIELD.cpp_type = 1

PBSHOP_REMAIN_COUNT_FIELD.name = "remain_count"
PBSHOP_REMAIN_COUNT_FIELD.full_name = ".pbShop.remain_count"
PBSHOP_REMAIN_COUNT_FIELD.number = 3
PBSHOP_REMAIN_COUNT_FIELD.index = 2
PBSHOP_REMAIN_COUNT_FIELD.label = 1
PBSHOP_REMAIN_COUNT_FIELD.has_default_value = false
PBSHOP_REMAIN_COUNT_FIELD.default_value = 0
PBSHOP_REMAIN_COUNT_FIELD.type = 5
PBSHOP_REMAIN_COUNT_FIELD.cpp_type = 1

PBSHOP_SELL_START_TIME_FIELD.name = "sell_start_time"
PBSHOP_SELL_START_TIME_FIELD.full_name = ".pbShop.sell_start_time"
PBSHOP_SELL_START_TIME_FIELD.number = 4
PBSHOP_SELL_START_TIME_FIELD.index = 3
PBSHOP_SELL_START_TIME_FIELD.label = 1
PBSHOP_SELL_START_TIME_FIELD.has_default_value = false
PBSHOP_SELL_START_TIME_FIELD.default_value = 0
PBSHOP_SELL_START_TIME_FIELD.type = 5
PBSHOP_SELL_START_TIME_FIELD.cpp_type = 1

PBSHOP_SELL_END_TIME_FIELD.name = "sell_end_time"
PBSHOP_SELL_END_TIME_FIELD.full_name = ".pbShop.sell_end_time"
PBSHOP_SELL_END_TIME_FIELD.number = 5
PBSHOP_SELL_END_TIME_FIELD.index = 4
PBSHOP_SELL_END_TIME_FIELD.label = 1
PBSHOP_SELL_END_TIME_FIELD.has_default_value = false
PBSHOP_SELL_END_TIME_FIELD.default_value = 0
PBSHOP_SELL_END_TIME_FIELD.type = 5
PBSHOP_SELL_END_TIME_FIELD.cpp_type = 1

PBSHOP_REFRESH_TIME_FIELD.name = "refresh_time"
PBSHOP_REFRESH_TIME_FIELD.full_name = ".pbShop.refresh_time"
PBSHOP_REFRESH_TIME_FIELD.number = 6
PBSHOP_REFRESH_TIME_FIELD.index = 5
PBSHOP_REFRESH_TIME_FIELD.label = 1
PBSHOP_REFRESH_TIME_FIELD.has_default_value = false
PBSHOP_REFRESH_TIME_FIELD.default_value = 0
PBSHOP_REFRESH_TIME_FIELD.type = 5
PBSHOP_REFRESH_TIME_FIELD.cpp_type = 1

PBSHOP.name = "pbShop"
PBSHOP.full_name = ".pbShop"
PBSHOP.nested_types = {}
PBSHOP.enum_types = {}
PBSHOP.fields = {PBSHOP_ID_FIELD, PBSHOP_PRICE_FIELD, PBSHOP_REMAIN_COUNT_FIELD, PBSHOP_SELL_START_TIME_FIELD, PBSHOP_SELL_END_TIME_FIELD, PBSHOP_REFRESH_TIME_FIELD}
PBSHOP.is_extendable = false
PBSHOP.extensions = {}
PBSHOPLIST_FIRST_TYPE_FIELD.name = "first_type"
PBSHOPLIST_FIRST_TYPE_FIELD.full_name = ".pbShopList.first_type"
PBSHOPLIST_FIRST_TYPE_FIELD.number = 1
PBSHOPLIST_FIRST_TYPE_FIELD.index = 0
PBSHOPLIST_FIRST_TYPE_FIELD.label = 2
PBSHOPLIST_FIRST_TYPE_FIELD.has_default_value = false
PBSHOPLIST_FIRST_TYPE_FIELD.default_value = 0
PBSHOPLIST_FIRST_TYPE_FIELD.type = 5
PBSHOPLIST_FIRST_TYPE_FIELD.cpp_type = 1

PBSHOPLIST_SECOND_TYPE_FIELD.name = "second_type"
PBSHOPLIST_SECOND_TYPE_FIELD.full_name = ".pbShopList.second_type"
PBSHOPLIST_SECOND_TYPE_FIELD.number = 2
PBSHOPLIST_SECOND_TYPE_FIELD.index = 1
PBSHOPLIST_SECOND_TYPE_FIELD.label = 1
PBSHOPLIST_SECOND_TYPE_FIELD.has_default_value = false
PBSHOPLIST_SECOND_TYPE_FIELD.default_value = 0
PBSHOPLIST_SECOND_TYPE_FIELD.type = 5
PBSHOPLIST_SECOND_TYPE_FIELD.cpp_type = 1

PBSHOPLIST_LIST_FIELD.name = "list"
PBSHOPLIST_LIST_FIELD.full_name = ".pbShopList.list"
PBSHOPLIST_LIST_FIELD.number = 3
PBSHOPLIST_LIST_FIELD.index = 2
PBSHOPLIST_LIST_FIELD.label = 3
PBSHOPLIST_LIST_FIELD.has_default_value = false
PBSHOPLIST_LIST_FIELD.default_value = {}
PBSHOPLIST_LIST_FIELD.message_type = PBSHOP
PBSHOPLIST_LIST_FIELD.type = 11
PBSHOPLIST_LIST_FIELD.cpp_type = 10

PBSHOPLIST.name = "pbShopList"
PBSHOPLIST.full_name = ".pbShopList"
PBSHOPLIST.nested_types = {}
PBSHOPLIST.enum_types = {}
PBSHOPLIST.fields = {PBSHOPLIST_FIRST_TYPE_FIELD, PBSHOPLIST_SECOND_TYPE_FIELD, PBSHOPLIST_LIST_FIELD}
PBSHOPLIST.is_extendable = false
PBSHOPLIST.extensions = {}
PBSHOPGETLIST_FIRST_TYPE_FIELD.name = "first_type"
PBSHOPGETLIST_FIRST_TYPE_FIELD.full_name = ".pbShopGetList.first_type"
PBSHOPGETLIST_FIRST_TYPE_FIELD.number = 1
PBSHOPGETLIST_FIRST_TYPE_FIELD.index = 0
PBSHOPGETLIST_FIRST_TYPE_FIELD.label = 2
PBSHOPGETLIST_FIRST_TYPE_FIELD.has_default_value = false
PBSHOPGETLIST_FIRST_TYPE_FIELD.default_value = 0
PBSHOPGETLIST_FIRST_TYPE_FIELD.type = 5
PBSHOPGETLIST_FIRST_TYPE_FIELD.cpp_type = 1

PBSHOPGETLIST_SECOND_TYPE_FIELD.name = "second_type"
PBSHOPGETLIST_SECOND_TYPE_FIELD.full_name = ".pbShopGetList.second_type"
PBSHOPGETLIST_SECOND_TYPE_FIELD.number = 2
PBSHOPGETLIST_SECOND_TYPE_FIELD.index = 1
PBSHOPGETLIST_SECOND_TYPE_FIELD.label = 1
PBSHOPGETLIST_SECOND_TYPE_FIELD.has_default_value = false
PBSHOPGETLIST_SECOND_TYPE_FIELD.default_value = 0
PBSHOPGETLIST_SECOND_TYPE_FIELD.type = 5
PBSHOPGETLIST_SECOND_TYPE_FIELD.cpp_type = 1

PBSHOPGETLIST.name = "pbShopGetList"
PBSHOPGETLIST.full_name = ".pbShopGetList"
PBSHOPGETLIST.nested_types = {}
PBSHOPGETLIST.enum_types = {}
PBSHOPGETLIST.fields = {PBSHOPGETLIST_FIRST_TYPE_FIELD, PBSHOPGETLIST_SECOND_TYPE_FIELD}
PBSHOPGETLIST.is_extendable = false
PBSHOPGETLIST.extensions = {}
PBSHOPBUY_FIRST_TYPE_FIELD.name = "first_type"
PBSHOPBUY_FIRST_TYPE_FIELD.full_name = ".pbShopBuy.first_type"
PBSHOPBUY_FIRST_TYPE_FIELD.number = 1
PBSHOPBUY_FIRST_TYPE_FIELD.index = 0
PBSHOPBUY_FIRST_TYPE_FIELD.label = 2
PBSHOPBUY_FIRST_TYPE_FIELD.has_default_value = false
PBSHOPBUY_FIRST_TYPE_FIELD.default_value = 0
PBSHOPBUY_FIRST_TYPE_FIELD.type = 5
PBSHOPBUY_FIRST_TYPE_FIELD.cpp_type = 1

PBSHOPBUY_SECOND_TYPE_FIELD.name = "second_type"
PBSHOPBUY_SECOND_TYPE_FIELD.full_name = ".pbShopBuy.second_type"
PBSHOPBUY_SECOND_TYPE_FIELD.number = 2
PBSHOPBUY_SECOND_TYPE_FIELD.index = 1
PBSHOPBUY_SECOND_TYPE_FIELD.label = 1
PBSHOPBUY_SECOND_TYPE_FIELD.has_default_value = false
PBSHOPBUY_SECOND_TYPE_FIELD.default_value = 0
PBSHOPBUY_SECOND_TYPE_FIELD.type = 5
PBSHOPBUY_SECOND_TYPE_FIELD.cpp_type = 1

PBSHOPBUY_ID_FIELD.name = "id"
PBSHOPBUY_ID_FIELD.full_name = ".pbShopBuy.id"
PBSHOPBUY_ID_FIELD.number = 3
PBSHOPBUY_ID_FIELD.index = 2
PBSHOPBUY_ID_FIELD.label = 2
PBSHOPBUY_ID_FIELD.has_default_value = false
PBSHOPBUY_ID_FIELD.default_value = 0
PBSHOPBUY_ID_FIELD.type = 5
PBSHOPBUY_ID_FIELD.cpp_type = 1

PBSHOPBUY_COUNT_FIELD.name = "count"
PBSHOPBUY_COUNT_FIELD.full_name = ".pbShopBuy.count"
PBSHOPBUY_COUNT_FIELD.number = 4
PBSHOPBUY_COUNT_FIELD.index = 3
PBSHOPBUY_COUNT_FIELD.label = 2
PBSHOPBUY_COUNT_FIELD.has_default_value = false
PBSHOPBUY_COUNT_FIELD.default_value = 0
PBSHOPBUY_COUNT_FIELD.type = 5
PBSHOPBUY_COUNT_FIELD.cpp_type = 1

PBSHOPBUY.name = "pbShopBuy"
PBSHOPBUY.full_name = ".pbShopBuy"
PBSHOPBUY.nested_types = {}
PBSHOPBUY.enum_types = {}
PBSHOPBUY.fields = {PBSHOPBUY_FIRST_TYPE_FIELD, PBSHOPBUY_SECOND_TYPE_FIELD, PBSHOPBUY_ID_FIELD, PBSHOPBUY_COUNT_FIELD}
PBSHOPBUY.is_extendable = false
PBSHOPBUY.extensions = {}

pbShop = protobuf.Message(PBSHOP)
pbShopBuy = protobuf.Message(PBSHOPBUY)
pbShopGetList = protobuf.Message(PBSHOPGETLIST)
pbShopList = protobuf.Message(PBSHOPLIST)

