local ConfigSysvip={
              [0] = {
                      lv = 0,
                      desc = [[C]],
                      exp = 0,
                      dungeon_no_star = 0,
                      dungeon_sweep = 0,
                      bag_num = 5,
                      coin_num = 2,
                      tittle = 6,
                      player_skill_point_num = 2,
                      energy_num = 2,
                      skill_point_num = 2,
                      max_energy_auto = 100,
                      max_skill_point_auto = 20,
                      max_energy = 99999,
                      max_skill_point = 20,
                      super_dungeon = 2,
                      arena_num = 2,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = nil,
                      value = 0,
                      union_build_time = 5,
                      hell_times = 2,
                      peerage_num = 2,
                      escort_num = 2,
                      escort_rob_num = 2,
                      buy_trial_times = 2,
                      buy_grow_fund = 0,
                    },
              [1] = {
                      lv = 1,
                      desc = [[C]],
                      exp = 0,
                      dungeon_no_star = 0,
                      dungeon_sweep = 0,
                      bag_num = 5,
                      coin_num = 4,
                      tittle = 6,
                      player_skill_point_num = 3,
                      energy_num = 4,
                      skill_point_num = 4,
                      max_energy_auto = 105,
                      max_skill_point_auto = 21,
                      max_energy = 99999,
                      max_skill_point = 21,
                      super_dungeon = 4,
                      arena_num = 4,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 20,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 20000,
                                    },
                            },
                      value = 20,
                      union_build_time = 5,
                      hell_times = 2,
                      peerage_num = 4,
                      escort_num = 2,
                      escort_rob_num = 2,
                      buy_trial_times = 2,
                      buy_grow_fund = 0,
                    },
              [2] = {
                      lv = 2,
                      desc = [[C]],
                      exp = 0,
                      dungeon_no_star = 0,
                      dungeon_sweep = 0,
                      bag_num = 5,
                      coin_num = 5,
                      tittle = 6,
                      player_skill_point_num = 4,
                      energy_num = 5,
                      skill_point_num = 5,
                      max_energy_auto = 110,
                      max_skill_point_auto = 22,
                      max_energy = 99999,
                      max_skill_point = 22,
                      super_dungeon = 5,
                      arena_num = 5,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 20,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 40000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 100,
                                    },
                            },
                      value = 120,
                      union_build_time = 5,
                      hell_times = 2,
                      peerage_num = 5,
                      escort_num = 2,
                      escort_rob_num = 2,
                      buy_trial_times = 2,
                      buy_grow_fund = 0,
                    },
              [3] = {
                      lv = 3,
                      desc = [[C]],
                      exp = 0,
                      dungeon_no_star = 0,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 6,
                      tittle = 6,
                      player_skill_point_num = 5,
                      energy_num = 6,
                      skill_point_num = 6,
                      max_energy_auto = 115,
                      max_skill_point_auto = 23,
                      max_energy = 99999,
                      max_skill_point = 23,
                      super_dungeon = 6,
                      arena_num = 6,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 30,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 60000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 100,
                                    },
                            },
                      value = 135,
                      union_build_time = 6,
                      hell_times = 2,
                      peerage_num = 6,
                      escort_num = 3,
                      escort_rob_num = 3,
                      buy_trial_times = 3,
                      buy_grow_fund = 0,
                    },
              [4] = {
                      lv = 4,
                      desc = [[C]],
                      exp = 0,
                      dungeon_no_star = 0,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 8,
                      tittle = 6,
                      player_skill_point_num = 6,
                      energy_num = 8,
                      skill_point_num = 8,
                      max_energy_auto = 120,
                      max_skill_point_auto = 24,
                      max_energy = 99999,
                      max_skill_point = 24,
                      super_dungeon = 8,
                      arena_num = 8,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 30,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 80000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 200,
                                    },
                            },
                      value = 225,
                      union_build_time = 6,
                      hell_times = 2,
                      peerage_num = 8,
                      escort_num = 3,
                      escort_rob_num = 3,
                      buy_trial_times = 3,
                      buy_grow_fund = 0,
                    },
              [5] = {
                      lv = 5,
                      desc = [[C]],
                      exp = 0,
                      dungeon_no_star = 0,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 9,
                      tittle = 6,
                      player_skill_point_num = 7,
                      energy_num = 9,
                      skill_point_num = 9,
                      max_energy_auto = 125,
                      max_skill_point_auto = 25,
                      max_energy = 99999,
                      max_skill_point = 25,
                      super_dungeon = 9,
                      arena_num = 9,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 40,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 100000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 200,
                                    },
                            },
                      value = 275,
                      union_build_time = 7,
                      hell_times = 2,
                      peerage_num = 9,
                      escort_num = 3,
                      escort_rob_num = 3,
                      buy_trial_times = 3,
                      buy_grow_fund = 0,
                    },
              [6] = {
                      lv = 6,
                      desc = [[C]],
                      exp = 0,
                      dungeon_no_star = 0,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 10,
                      tittle = 6,
                      player_skill_point_num = 8,
                      energy_num = 10,
                      skill_point_num = 10,
                      max_energy_auto = 130,
                      max_skill_point_auto = 26,
                      max_energy = 99999,
                      max_skill_point = 26,
                      super_dungeon = 10,
                      arena_num = 10,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 40,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 120000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 200,
                                    },
                            },
                      value = 300,
                      union_build_time = 7,
                      hell_times = 2,
                      peerage_num = 10,
                      escort_num = 4,
                      escort_rob_num = 4,
                      buy_trial_times = 4,
                      buy_grow_fund = 0,
                    },
              [7] = {
                      lv = 7,
                      desc = [[C]],
                      exp = 10000,
                      dungeon_no_star = 0,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 11,
                      tittle = 6,
                      player_skill_point_num = 9,
                      energy_num = 11,
                      skill_point_num = 11,
                      max_energy_auto = 135,
                      max_skill_point_auto = 27,
                      max_energy = 99999,
                      max_skill_point = 27,
                      super_dungeon = 11,
                      arena_num = 11,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 50,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 140000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 200,
                                    },
                            },
                      value = 325,
                      union_build_time = 8,
                      hell_times = 2,
                      peerage_num = 11,
                      escort_num = 4,
                      escort_rob_num = 4,
                      buy_trial_times = 4,
                      buy_grow_fund = 0,
                    },
              [8] = {
                      lv = 8,
                      desc = [[C]],
                      exp = 20000,
                      dungeon_no_star = 0,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 12,
                      tittle = 6,
                      player_skill_point_num = 10,
                      energy_num = 12,
                      skill_point_num = 12,
                      max_energy_auto = 140,
                      max_skill_point_auto = 28,
                      max_energy = 99999,
                      max_skill_point = 28,
                      super_dungeon = 12,
                      arena_num = 12,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 50,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 160000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 200,
                                    },
                            },
                      value = 350,
                      union_build_time = 8,
                      hell_times = 2,
                      peerage_num = 12,
                      escort_num = 4,
                      escort_rob_num = 4,
                      buy_trial_times = 4,
                      buy_grow_fund = 1,
                    },
              [9] = {
                      lv = 9,
                      desc = [[C]],
                      exp = 60000,
                      dungeon_no_star = 0,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 13,
                      tittle = 6,
                      player_skill_point_num = 11,
                      energy_num = 13,
                      skill_point_num = 13,
                      max_energy_auto = 145,
                      max_skill_point_auto = 29,
                      max_energy = 99999,
                      max_skill_point = 29,
                      super_dungeon = 13,
                      arena_num = 13,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 60,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 180000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 300,
                                    },
                            },
                      value = 400,
                      union_build_time = 9,
                      hell_times = 2,
                      peerage_num = 13,
                      escort_num = 5,
                      escort_rob_num = 5,
                      buy_trial_times = 5,
                      buy_grow_fund = 1,
                    },
              [10] = {
                      lv = 10,
                      desc = [[C]],
                      exp = 100000,
                      dungeon_no_star = 1,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 15,
                      tittle = 6,
                      player_skill_point_num = 12,
                      energy_num = 15,
                      skill_point_num = 15,
                      max_energy_auto = 150,
                      max_skill_point_auto = 30,
                      max_energy = 99999,
                      max_skill_point = 30,
                      super_dungeon = 15,
                      arena_num = 15,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 60,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 200000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 300,
                                    },
                            },
                      value = 450,
                      union_build_time = 9,
                      hell_times = 2,
                      peerage_num = 15,
                      escort_num = 5,
                      escort_rob_num = 5,
                      buy_trial_times = 5,
                      buy_grow_fund = 1,
                    },
              [11] = {
                      lv = 11,
                      desc = [[C]],
                      exp = 200000,
                      dungeon_no_star = 1,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 16,
                      tittle = 6,
                      player_skill_point_num = 13,
                      energy_num = 16,
                      skill_point_num = 16,
                      max_energy_auto = 155,
                      max_skill_point_auto = 31,
                      max_energy = 99999,
                      max_skill_point = 31,
                      super_dungeon = 16,
                      arena_num = 16,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 70,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 220000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 300,
                                    },
                            },
                      value = 500,
                      union_build_time = 10,
                      hell_times = 2,
                      peerage_num = 16,
                      escort_num = 5,
                      escort_rob_num = 5,
                      buy_trial_times = 5,
                      buy_grow_fund = 1,
                    },
              [12] = {
                      lv = 12,
                      desc = [[C]],
                      exp = 400000,
                      dungeon_no_star = 1,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 17,
                      tittle = 6,
                      player_skill_point_num = 14,
                      energy_num = 17,
                      skill_point_num = 17,
                      max_energy_auto = 160,
                      max_skill_point_auto = 32,
                      max_energy = 99999,
                      max_skill_point = 32,
                      super_dungeon = 17,
                      arena_num = 17,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 80,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 240000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 300,
                                    },
                            },
                      value = 550,
                      union_build_time = 10,
                      hell_times = 2,
                      peerage_num = 17,
                      escort_num = 6,
                      escort_rob_num = 6,
                      buy_trial_times = 6,
                      buy_grow_fund = 1,
                    },
              [13] = {
                      lv = 13,
                      desc = [[C]],
                      exp = 600000,
                      dungeon_no_star = 1,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 18,
                      tittle = 6,
                      player_skill_point_num = 15,
                      energy_num = 18,
                      skill_point_num = 18,
                      max_energy_auto = 165,
                      max_skill_point_auto = 33,
                      max_energy = 99999,
                      max_skill_point = 33,
                      super_dungeon = 18,
                      arena_num = 18,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 90,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 260000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 300,
                                    },
                            },
                      value = 600,
                      union_build_time = 11,
                      hell_times = 2,
                      peerage_num = 18,
                      escort_num = 6,
                      escort_rob_num = 6,
                      buy_trial_times = 6,
                      buy_grow_fund = 1,
                    },
              [14] = {
                      lv = 14,
                      desc = [[C]],
                      exp = 1000000,
                      dungeon_no_star = 1,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 19,
                      tittle = 6,
                      player_skill_point_num = 16,
                      energy_num = 19,
                      skill_point_num = 19,
                      max_energy_auto = 170,
                      max_skill_point_auto = 34,
                      max_energy = 99999,
                      max_skill_point = 34,
                      super_dungeon = 19,
                      arena_num = 19,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 100,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 280000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 300,
                                    },
                            },
                      value = 650,
                      union_build_time = 11,
                      hell_times = 2,
                      peerage_num = 19,
                      escort_num = 6,
                      escort_rob_num = 6,
                      buy_trial_times = 6,
                      buy_grow_fund = 1,
                    },
              [15] = {
                      lv = 15,
                      desc = [[C]],
                      exp = 1000000,
                      dungeon_no_star = 1,
                      dungeon_sweep = 1,
                      bag_num = 5,
                      coin_num = 20,
                      tittle = 6,
                      player_skill_point_num = 17,
                      energy_num = 20,
                      skill_point_num = 20,
                      max_energy_auto = 175,
                      max_skill_point_auto = 35,
                      max_energy = 99999,
                      max_skill_point = 35,
                      super_dungeon = 20,
                      arena_num = 20,
                      marking_gold = 0,
                      marking_exp = 0,
                      award = {
                              {
                                      goods_id = 100014,
                                      goods_num = 120,
                                    },
                              {
                                      goods_id = 100027,
                                      goods_num = 300000,
                                    },
                              {
                                      goods_id = 177098,
                                      goods_num = 300,
                                    },
                            },
                      value = 700,
                      union_build_time = 12,
                      hell_times = 2,
                      peerage_num = 20,
                      escort_num = 7,
                      escort_rob_num = 7,
                      buy_trial_times = 7,
                      buy_grow_fund = 1,
                    },
            }
return ConfigSysvip;