
local ConfigSystalent_attribute={
              ["1_1"] = {
                      star = 1,
                      attri = 1,
                      base_value = 60,
                      strength_add = 23,
                      add_min = 38,
                      add_max = 58,
                      strength_add_min = 30,
                      strength_add_max = 44,
                    },
              ["2_1"] = {
                      star = 2,
                      attri = 1,
                      base_value = 90,
                      strength_add = 34,
                      add_min = 58,
                      add_max = 86,
                      strength_add_min = 45,
                      strength_add_max = 67,
                    },
              ["3_1"] = {
                      star = 3,
                      attri = 1,
                      base_value = 120,
                      strength_add = 45,
                      add_min = 77,
                      add_max = 115,
                      strength_add_min = 60,
                      strength_add_max = 90,
                    },
              ["4_1"] = {
                      star = 4,
                      attri = 1,
                      base_value = 180,
                      strength_add = 68,
                      add_min = 115,
                      add_max = 173,
                      strength_add_min = 90,
                      strength_add_max = 134,
                    },
              ["5_1"] = {
                      star = 5,
                      attri = 1,
                      base_value = 240,
                      strength_add = 91,
                      add_min = 154,
                      add_max = 230,
                      strength_add_min = 119,
                      strength_add_max = 179,
                    },
              ["6_1"] = {
                      star = 6,
                      attri = 1,
                      base_value = 300,
                      strength_add = 113,
                      add_min = 192,
                      add_max = 288,
                      strength_add_min = 150,
                      strength_add_max = 224,
                    },
              ["1_2"] = {
                      star = 1,
                      attri = 2,
                      base_value = 6,
                      strength_add = 2,
                      add_min = 4,
                      add_max = 6,
                      strength_add_min = 3,
                      strength_add_max = 5,
                    },
              ["2_2"] = {
                      star = 2,
                      attri = 2,
                      base_value = 9,
                      strength_add = 3,
                      add_min = 6,
                      add_max = 8,
                      strength_add_min = 5,
                      strength_add_max = 7,
                    },
              ["3_2"] = {
                      star = 3,
                      attri = 2,
                      base_value = 12,
                      strength_add = 5,
                      add_min = 8,
                      add_max = 12,
                      strength_add_min = 6,
                      strength_add_max = 8,
                    },
              ["4_2"] = {
                      star = 4,
                      attri = 2,
                      base_value = 18,
                      strength_add = 7,
                      add_min = 11,
                      add_max = 17,
                      strength_add_min = 9,
                      strength_add_max = 13,
                    },
              ["5_2"] = {
                      star = 5,
                      attri = 2,
                      base_value = 24,
                      strength_add = 9,
                      add_min = 15,
                      add_max = 23,
                      strength_add_min = 12,
                      strength_add_max = 18,
                    },
              ["6_2"] = {
                      star = 6,
                      attri = 2,
                      base_value = 30,
                      strength_add = 11,
                      add_min = 19,
                      add_max = 29,
                      strength_add_min = 15,
                      strength_add_max = 23,
                    },
              ["1_3"] = {
                      star = 1,
                      attri = 3,
                      base_value = 6,
                      strength_add = 2,
                      add_min = 4,
                      add_max = 6,
                      strength_add_min = 3,
                      strength_add_max = 5,
                    },
              ["2_3"] = {
                      star = 2,
                      attri = 3,
                      base_value = 9,
                      strength_add = 3,
                      add_min = 6,
                      add_max = 8,
                      strength_add_min = 5,
                      strength_add_max = 7,
                    },
              ["3_3"] = {
                      star = 3,
                      attri = 3,
                      base_value = 12,
                      strength_add = 5,
                      add_min = 8,
                      add_max = 12,
                      strength_add_min = 6,
                      strength_add_max = 8,
                    },
              ["4_3"] = {
                      star = 4,
                      attri = 3,
                      base_value = 18,
                      strength_add = 7,
                      add_min = 11,
                      add_max = 17,
                      strength_add_min = 9,
                      strength_add_max = 13,
                    },
              ["5_3"] = {
                      star = 5,
                      attri = 3,
                      base_value = 24,
                      strength_add = 9,
                      add_min = 15,
                      add_max = 23,
                      strength_add_min = 12,
                      strength_add_max = 18,
                    },
              ["6_3"] = {
                      star = 6,
                      attri = 3,
                      base_value = 30,
                      strength_add = 11,
                      add_min = 19,
                      add_max = 29,
                      strength_add_min = 15,
                      strength_add_max = 23,
                    },
              ["1_4"] = {
                      star = 1,
                      attri = 4,
                      base_value = 0.02,
                      strength_add = 0.006,
                      add_min = 0.01,
                      add_max = 0.01,
                      strength_add_min = 0.01,
                      strength_add_max = 0.01,
                    },
              ["2_4"] = {
                      star = 2,
                      attri = 4,
                      base_value = 0.02,
                      strength_add = 0.009,
                      add_min = 0.01,
                      add_max = 0.02,
                      strength_add_min = 0.01,
                      strength_add_max = 0.01,
                    },
              ["3_4"] = {
                      star = 3,
                      attri = 4,
                      base_value = 0.03,
                      strength_add = 0.011,
                      add_min = 0.02,
                      add_max = 0.02,
                      strength_add_min = 0.01,
                      strength_add_max = 0.02,
                    },
              ["4_4"] = {
                      star = 4,
                      attri = 4,
                      base_value = 0.05,
                      strength_add = 0.017,
                      add_min = 0.02,
                      add_max = 0.04,
                      strength_add_min = 0.02,
                      strength_add_max = 0.03,
                    },
              ["5_4"] = {
                      star = 5,
                      attri = 4,
                      base_value = 0.06,
                      strength_add = 0.023,
                      add_min = 0.03,
                      add_max = 0.05,
                      strength_add_min = 0.03,
                      strength_add_max = 0.04,
                    },
              ["6_4"] = {
                      star = 6,
                      attri = 4,
                      base_value = 0.08,
                      strength_add = 0.029,
                      add_min = 0.04,
                      add_max = 0.06,
                      strength_add_min = 0.03,
                      strength_add_max = 0.05,
                    },
              ["1_5"] = {
                      star = 1,
                      attri = 5,
                      base_value = 0.02,
                      strength_add = 0.009,
                      add_min = 0.01,
                      add_max = 0.02,
                      strength_add_min = 0.01,
                      strength_add_max = 0.01,
                    },
              ["2_5"] = {
                      star = 2,
                      attri = 5,
                      base_value = 0.04,
                      strength_add = 0.014,
                      add_min = 0.02,
                      add_max = 0.03,
                      strength_add_min = 0.01,
                      strength_add_max = 0.02,
                    },
              ["3_5"] = {
                      star = 3,
                      attri = 5,
                      base_value = 0.05,
                      strength_add = 0.018,
                      add_min = 0.02,
                      add_max = 0.03,
                      strength_add_min = 0.02,
                      strength_add_max = 0.03,
                    },
              ["4_5"] = {
                      star = 4,
                      attri = 5,
                      base_value = 0.07,
                      strength_add = 0.027,
                      add_min = 0.03,
                      add_max = 0.05,
                      strength_add_min = 0.03,
                      strength_add_max = 0.04,
                    },
              ["5_5"] = {
                      star = 5,
                      attri = 5,
                      base_value = 0.1,
                      strength_add = 0.036,
                      add_min = 0.05,
                      add_max = 0.07,
                      strength_add_min = 0.04,
                      strength_add_max = 0.05,
                    },
              ["6_5"] = {
                      star = 6,
                      attri = 5,
                      base_value = 0.12,
                      strength_add = 0.045,
                      add_min = 0.06,
                      add_max = 0.09,
                      strength_add_min = 0.04,
                      strength_add_max = 0.07,
                    },
              ["1_6"] = {
                      star = 1,
                      attri = 6,
                      base_value = 0.02,
                      strength_add = 0.007,
                      add_min = 0.01,
                      add_max = 0.01,
                      strength_add_min = 0.01,
                      strength_add_max = 0.01,
                    },
              ["2_6"] = {
                      star = 2,
                      attri = 6,
                      base_value = 0.03,
                      strength_add = 0.01,
                      add_min = 0.01,
                      add_max = 0.02,
                      strength_add_min = 0.01,
                      strength_add_max = 0.02,
                    },
              ["3_6"] = {
                      star = 3,
                      attri = 6,
                      base_value = 0.04,
                      strength_add = 0.014,
                      add_min = 0.02,
                      add_max = 0.03,
                      strength_add_min = 0.02,
                      strength_add_max = 0.02,
                    },
              ["4_6"] = {
                      star = 4,
                      attri = 6,
                      base_value = 0.05,
                      strength_add = 0.02,
                      add_min = 0.03,
                      add_max = 0.04,
                      strength_add_min = 0.02,
                      strength_add_max = 0.03,
                    },
              ["5_6"] = {
                      star = 5,
                      attri = 6,
                      base_value = 0.07,
                      strength_add = 0.027,
                      add_min = 0.04,
                      add_max = 0.06,
                      strength_add_min = 0.03,
                      strength_add_max = 0.04,
                    },
              ["6_6"] = {
                      star = 6,
                      attri = 6,
                      base_value = 0.09,
                      strength_add = 0.034,
                      add_min = 0.05,
                      add_max = 0.07,
                      strength_add_min = 0.04,
                      strength_add_max = 0.06,
                    },
              ["1_7"] = {
                      star = 1,
                      attri = 7,
                      base_value = 0.02,
                      strength_add = 0.007,
                      add_min = 0.01,
                      add_max = 0.01,
                      strength_add_min = 0.01,
                      strength_add_max = 0.01,
                    },
              ["2_7"] = {
                      star = 2,
                      attri = 7,
                      base_value = 0.03,
                      strength_add = 0.01,
                      add_min = 0.01,
                      add_max = 0.02,
                      strength_add_min = 0.01,
                      strength_add_max = 0.02,
                    },
              ["3_7"] = {
                      star = 3,
                      attri = 7,
                      base_value = 0.04,
                      strength_add = 0.014,
                      add_min = 0.02,
                      add_max = 0.03,
                      strength_add_min = 0.02,
                      strength_add_max = 0.02,
                    },
              ["4_7"] = {
                      star = 4,
                      attri = 7,
                      base_value = 0.05,
                      strength_add = 0.02,
                      add_min = 0.03,
                      add_max = 0.04,
                      strength_add_min = 0.02,
                      strength_add_max = 0.03,
                    },
              ["5_7"] = {
                      star = 5,
                      attri = 7,
                      base_value = 0.07,
                      strength_add = 0.027,
                      add_min = 0.04,
                      add_max = 0.06,
                      strength_add_min = 0.03,
                      strength_add_max = 0.04,
                    },
              ["6_7"] = {
                      star = 6,
                      attri = 7,
                      base_value = 0.09,
                      strength_add = 0.034,
                      add_min = 0.05,
                      add_max = 0.07,
                      strength_add_min = 0.04,
                      strength_add_max = 0.06,
                    },
              ["1_8"] = {
                      star = 1,
                      attri = 8,
                      base_value = 2,
                      strength_add = 0.6,
                      add_min = 1,
                      add_max = 2,
                      strength_add_min = 1,
                      strength_add_max = 1,
                    },
              ["2_8"] = {
                      star = 2,
                      attri = 8,
                      base_value = 2,
                      strength_add = 0.8,
                      add_min = 2,
                      add_max = 4,
                      strength_add_min = 2,
                      strength_add_max = 2,
                    },
              ["3_8"] = {
                      star = 3,
                      attri = 8,
                      base_value = 3,
                      strength_add = 1.1,
                      add_min = 3,
                      add_max = 5,
                      strength_add_min = 2,
                      strength_add_max = 4,
                    },
              ["4_8"] = {
                      star = 4,
                      attri = 8,
                      base_value = 5,
                      strength_add = 1.7,
                      add_min = 4,
                      add_max = 6,
                      strength_add_min = 3,
                      strength_add_max = 5,
                    },
              ["5_8"] = {
                      star = 5,
                      attri = 8,
                      base_value = 6,
                      strength_add = 2.2,
                      add_min = 5,
                      add_max = 8,
                      strength_add_min = 5,
                      strength_add_max = 7,
                    },
              ["6_8"] = {
                      star = 6,
                      attri = 8,
                      base_value = 8,
                      strength_add = 2.8,
                      add_min = 7,
                      add_max = 11,
                      strength_add_min = 6,
                      strength_add_max = 8,
                    },
              ["1_9"] = {
                      star = 1,
                      attri = 9,
                      base_value = 0.02,
                      strength_add = 0.007,
                      add_min = 0.01,
                      add_max = 0.02,
                      strength_add_min = 0.01,
                      strength_add_max = 0.02,
                    },
              ["2_9"] = {
                      star = 2,
                      attri = 9,
                      base_value = 0.03,
                      strength_add = 0.011,
                      add_min = 0.02,
                      add_max = 0.03,
                      strength_add_min = 0.02,
                      strength_add_max = 0.03,
                    },
              ["3_9"] = {
                      star = 3,
                      attri = 9,
                      base_value = 0.04,
                      strength_add = 0.014,
                      add_min = 0.02,
                      add_max = 0.04,
                      strength_add_min = 0.02,
                      strength_add_max = 0.03,
                    },
              ["4_9"] = {
                      star = 4,
                      attri = 9,
                      base_value = 0.05,
                      strength_add = 0.022,
                      add_min = 0.04,
                      add_max = 0.06,
                      strength_add_min = 0.03,
                      strength_add_max = 0.05,
                    },
              ["5_9"] = {
                      star = 5,
                      attri = 9,
                      base_value = 0.07,
                      strength_add = 0.029,
                      add_min = 0.05,
                      add_max = 0.09,
                      strength_add_min = 0.04,
                      strength_add_max = 0.07,
                    },
              ["6_9"] = {
                      star = 6,
                      attri = 9,
                      base_value = 0.09,
                      strength_add = 0.036,
                      add_min = 0.07,
                      add_max = 0.11,
                      strength_add_min = 0.06,
                      strength_add_max = 0.08,
                    },
              ["1_10"] = {
                      star = 1,
                      attri = 10,
                      base_value = 0.02,
                      strength_add = 0.007,
                      add_min = 0.01,
                      add_max = 0.02,
                      strength_add_min = 0.01,
                      strength_add_max = 0.02,
                    },
              ["2_10"] = {
                      star = 2,
                      attri = 10,
                      base_value = 0.03,
                      strength_add = 0.011,
                      add_min = 0.02,
                      add_max = 0.03,
                      strength_add_min = 0.02,
                      strength_add_max = 0.03,
                    },
              ["3_10"] = {
                      star = 3,
                      attri = 10,
                      base_value = 0.04,
                      strength_add = 0.014,
                      add_min = 0.02,
                      add_max = 0.04,
                      strength_add_min = 0.02,
                      strength_add_max = 0.03,
                    },
              ["4_10"] = {
                      star = 4,
                      attri = 10,
                      base_value = 0.05,
                      strength_add = 0.022,
                      add_min = 0.04,
                      add_max = 0.06,
                      strength_add_min = 0.03,
                      strength_add_max = 0.05,
                    },
              ["5_10"] = {
                      star = 5,
                      attri = 10,
                      base_value = 0.07,
                      strength_add = 0.029,
                      add_min = 0.05,
                      add_max = 0.09,
                      strength_add_min = 0.04,
                      strength_add_max = 0.07,
                    },
              ["6_10"] = {
                      star = 6,
                      attri = 10,
                      base_value = 0.09,
                      strength_add = 0.036,
                      add_min = 0.07,
                      add_max = 0.11,
                      strength_add_min = 0.06,
                      strength_add_max = 0.08,
                    },
              ["1_11"] = {
                      star = 1,
                      attri = 11,
                      base_value = 0.02,
                      strength_add = 0.007,
                      add_min = 0.01,
                      add_max = 0.02,
                      strength_add_min = 0.01,
                      strength_add_max = 0.02,
                    },
              ["2_11"] = {
                      star = 2,
                      attri = 11,
                      base_value = 0.03,
                      strength_add = 0.011,
                      add_min = 0.02,
                      add_max = 0.03,
                      strength_add_min = 0.02,
                      strength_add_max = 0.03,
                    },
              ["3_11"] = {
                      star = 3,
                      attri = 11,
                      base_value = 0.04,
                      strength_add = 0.014,
                      add_min = 0.02,
                      add_max = 0.04,
                      strength_add_min = 0.02,
                      strength_add_max = 0.03,
                    },
              ["4_11"] = {
                      star = 4,
                      attri = 11,
                      base_value = 0.05,
                      strength_add = 0.022,
                      add_min = 0.04,
                      add_max = 0.06,
                      strength_add_min = 0.03,
                      strength_add_max = 0.05,
                    },
              ["5_11"] = {
                      star = 5,
                      attri = 11,
                      base_value = 0.07,
                      strength_add = 0.029,
                      add_min = 0.05,
                      add_max = 0.09,
                      strength_add_min = 0.04,
                      strength_add_max = 0.07,
                    },
              ["6_11"] = {
                      star = 6,
                      attri = 11,
                      base_value = 0.09,
                      strength_add = 0.036,
                      add_min = 0.07,
                      add_max = 0.11,
                      strength_add_min = 0.06,
                      strength_add_max = 0.08,
                    },
            }
return ConfigSystalent_attribute;