local endless_chapter1=[[map_010]]
local endless_chapter2=[[ui_203311]]
local endless_chapter3=[[ui_203411]]
local endless_chapter4=[[ui_203321]]
local endless_chapter5=[[ui_203331]]
local endless_chapter6=[[ui_203341]]
local endless_chapter7=[[ui_203351]]
local endless_chapter8=[[ui_203421]]
local endless_chapter9=[[ui_203431]]
local endless_chapter10=[[ui_203441]]

local ConfigSysendless_chapter={
              [1] = {
                      palace_name = [[景阳宫]],
                      map = endless_chapter1,
                      buff_id = 9001001,
                      attribute = 0,
                      level_buff = {
                              9001001,
                              9001002,
                              9001003,
                              9001004,
                              9001005,
                              9001006,
                              9001007,
                              9001008,
                              9001009,
                              9001010,
                            },
                      model_data = {
                              model_id = {
                                      [[ui_200111]],
                                      [[ui_200211]],
                                      [[ui_200311]],
                                      [[ui_200411]],
                                      [[ui_200511]],
                                      [[ui_200611]],
                                      [[ui_200711]],
                                      [[ui_200811]],
                                    },
                              pos_x = {
                                      -350,
                                      -250,
                                      -150,
                                      -50,
                                      50,
                                      150,
                                      250,
                                      350,
                                    },
                              pos_y = {
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                    },
                              size = {
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                    },
                            },
                    },
              [2] = {
                      palace_name = [[景仁宫]],
                      map = endless_chapter1,
                      buff_id = 9001002,
                      attribute = 0,
                      level_buff = {
                              9001001,
                              9001002,
                              9001003,
                              9001004,
                              9001005,
                              9001006,
                              9001007,
                              9001008,
                              9001009,
                              9001010,
                            },
                      model_data = {
                              model_id = {
                                      [[ui_200911]],
                                      [[ui_201211]],
                                      [[ui_201511]],
                                      [[ui_201611]],
                                      [[ui_201911]],
                                      [[ui_202311]],
                                      [[ui_202411]],
                                      [[ui_202711]],
                                    },
                              pos_x = {
                                      -350,
                                      -250,
                                      -150,
                                      -50,
                                      50,
                                      150,
                                      250,
                                      350,
                                    },
                              pos_y = {
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                    },
                              size = {
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                    },
                            },
                    },
              [3] = {
                      palace_name = [[钟粹宫]],
                      map = endless_chapter1,
                      buff_id = 9001003,
                      attribute = 0,
                      level_buff = {
                              9001001,
                              9001002,
                              9001003,
                              9001004,
                              9001005,
                              9001006,
                              9001007,
                              9001008,
                              9001009,
                              9001010,
                            },
                      model_data = {
                              model_id = {
                                      [[ui_202811]],
                                      [[ui_202911]],
                                      [[ui_203011]],
                                      endless_chapter2,
                                      endless_chapter3,
                                      [[ui_203611]],
                                      [[ui_203711]],
                                      [[ui_203811]],
                                    },
                              pos_x = {
                                      -350,
                                      -250,
                                      -150,
                                      -50,
                                      50,
                                      150,
                                      250,
                                      350,
                                    },
                              pos_y = {
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                    },
                              size = {
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                    },
                            },
                    },
              [4] = {
                      palace_name = [[承乾宫]],
                      map = endless_chapter1,
                      buff_id = 9001004,
                      attribute = 0,
                      level_buff = {
                              9001001,
                              9001002,
                              9001003,
                              9001004,
                              9001005,
                              9001006,
                              9001007,
                              9001008,
                              9001009,
                              9001010,
                            },
                      model_data = {
                              model_id = {
                                      [[ui_203911]],
                                      [[ui_203921]],
                                      [[ui_203931]],
                                      [[ui_203941]],
                                      [[ui_203951]],
                                      [[ui_204011]],
                                      [[ui_204041]],
                                      [[ui_204051]],
                                    },
                              pos_x = {
                                      -350,
                                      -250,
                                      -150,
                                      -50,
                                      50,
                                      150,
                                      250,
                                      350,
                                    },
                              pos_y = {
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                    },
                              size = {
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                    },
                            },
                    },
              [5] = {
                      palace_name = [[延禧宫]],
                      map = endless_chapter1,
                      buff_id = 9001005,
                      attribute = 0,
                      level_buff = {
                              9001001,
                              9001002,
                              9001003,
                              9001004,
                              9001005,
                              9001006,
                              9001007,
                              9001008,
                              9001009,
                              9001010,
                            },
                      model_data = {
                              model_id = {
                                      [[ui_204411]],
                                      endless_chapter4,
                                      endless_chapter5,
                                      endless_chapter6,
                                      endless_chapter7,
                                      endless_chapter3,
                                      endless_chapter8,
                                      endless_chapter9,
                                    },
                              pos_x = {
                                      -350,
                                      -250,
                                      -150,
                                      -50,
                                      50,
                                      150,
                                      250,
                                      350,
                                    },
                              pos_y = {
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                    },
                              size = {
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                    },
                            },
                    },
              [6] = {
                      palace_name = [[永和宫]],
                      map = endless_chapter1,
                      buff_id = 9001006,
                      attribute = 0,
                      level_buff = {
                              9001001,
                              9001002,
                              9001003,
                              9001004,
                              9001005,
                              9001006,
                              9001007,
                              9001008,
                              9001009,
                              9001010,
                            },
                      model_data = {
                              model_id = {
                                      endless_chapter2,
                                      endless_chapter4,
                                      endless_chapter5,
                                      endless_chapter6,
                                      endless_chapter7,
                                      endless_chapter3,
                                      endless_chapter8,
                                      endless_chapter9,
                                    },
                              pos_x = {
                                      -350,
                                      -250,
                                      -150,
                                      -50,
                                      50,
                                      150,
                                      250,
                                      350,
                                    },
                              pos_y = {
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                    },
                              size = {
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                    },
                            },
                    },
              [7] = {
                      palace_name = [[长春宫]],
                      map = endless_chapter1,
                      buff_id = 9001007,
                      attribute = 0,
                      level_buff = {
                              9001001,
                              9001002,
                              9001003,
                              9001004,
                              9001005,
                              9001006,
                              9001007,
                              9001008,
                              9001009,
                              9001010,
                            },
                      model_data = {
                              model_id = {
                                      endless_chapter2,
                                      endless_chapter4,
                                      endless_chapter5,
                                      endless_chapter6,
                                      endless_chapter7,
                                      endless_chapter3,
                                      endless_chapter8,
                                      endless_chapter9,
                                    },
                              pos_x = {
                                      -350,
                                      -250,
                                      -150,
                                      -50,
                                      50,
                                      150,
                                      250,
                                      350,
                                    },
                              pos_y = {
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                    },
                              size = {
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                    },
                            },
                    },
              [8] = {
                      palace_name = [[启祥宫]],
                      map = endless_chapter1,
                      buff_id = 9001008,
                      attribute = 0,
                      level_buff = {
                              9001001,
                              9001002,
                              9001003,
                              9001004,
                              9001005,
                              9001006,
                              9001007,
                              9001008,
                              9001009,
                              9001010,
                            },
                      model_data = {
                              model_id = {
                                      endless_chapter2,
                                      endless_chapter4,
                                      endless_chapter5,
                                      endless_chapter6,
                                      endless_chapter7,
                                      endless_chapter3,
                                      endless_chapter8,
                                      endless_chapter9,
                                    },
                              pos_x = {
                                      -350,
                                      -250,
                                      -150,
                                      -50,
                                      50,
                                      150,
                                      250,
                                      350,
                                    },
                              pos_y = {
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                    },
                              size = {
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                    },
                            },
                    },
              [9] = {
                      palace_name = [[咸福宫]],
                      map = endless_chapter1,
                      buff_id = 9001009,
                      attribute = 0,
                      level_buff = {
                              9001001,
                              9001002,
                              9001003,
                              9001004,
                              9001005,
                              9001006,
                              9001007,
                              9001008,
                              9001009,
                              9001010,
                            },
                      model_data = {
                              model_id = {
                                      endless_chapter2,
                                      endless_chapter4,
                                      endless_chapter5,
                                      endless_chapter6,
                                      endless_chapter7,
                                      endless_chapter3,
                                      endless_chapter8,
                                      endless_chapter9,
                                    },
                              pos_x = {
                                      -350,
                                      -250,
                                      -150,
                                      -50,
                                      50,
                                      150,
                                      250,
                                      350,
                                    },
                              pos_y = {
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                    },
                              size = {
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                    },
                            },
                    },
              [10] = {
                      palace_name = [[翊坤宫]],
                      map = endless_chapter1,
                      buff_id = 9001010,
                      attribute = 0,
                      level_buff = {
                              9001001,
                              9001002,
                              9001003,
                              9001004,
                              9001005,
                              9001006,
                              9001007,
                              9001008,
                              9001009,
                              9001010,
                            },
                      model_data = {
                              model_id = {
                                      endless_chapter2,
                                      endless_chapter4,
                                      endless_chapter5,
                                      endless_chapter6,
                                      endless_chapter7,
                                      endless_chapter3,
                                      endless_chapter8,
                                      endless_chapter9,
                                    },
                              pos_x = {
                                      -350,
                                      -250,
                                      -150,
                                      -50,
                                      50,
                                      150,
                                      250,
                                      350,
                                    },
                              pos_y = {
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                    },
                              size = {
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                    },
                            },
                    },
              [11] = {
                      palace_name = [[永寿宫]],
                      map = endless_chapter1,
                      buff_id = 9001001,
                      attribute = 0,
                      level_buff = {
                              9001001,
                              9001002,
                              9001003,
                              9001004,
                              9001005,
                              9001006,
                              9001007,
                              9001008,
                              9001009,
                              9001010,
                            },
                      model_data = {
                              model_id = {
                                      endless_chapter2,
                                      endless_chapter4,
                                      endless_chapter5,
                                      endless_chapter6,
                                      endless_chapter7,
                                      endless_chapter3,
                                      endless_chapter8,
                                      endless_chapter10,
                                    },
                              pos_x = {
                                      -350,
                                      -250,
                                      -150,
                                      -50,
                                      50,
                                      150,
                                      250,
                                      350,
                                    },
                              pos_y = {
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                    },
                              size = {
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                    },
                            },
                    },
              [12] = {
                      palace_name = [[储秀宫]],
                      map = endless_chapter1,
                      buff_id = 9001002,
                      attribute = 0,
                      level_buff = {
                              9001001,
                              9001002,
                              9001003,
                              9001004,
                              9001005,
                              9001006,
                              9001007,
                              9001008,
                              9001009,
                              9001010,
                            },
                      model_data = {
                              model_id = {
                                      endless_chapter2,
                                      endless_chapter4,
                                      endless_chapter5,
                                      endless_chapter6,
                                      endless_chapter7,
                                      endless_chapter3,
                                      endless_chapter8,
                                      endless_chapter10,
                                    },
                              pos_x = {
                                      -350,
                                      -250,
                                      -150,
                                      -50,
                                      50,
                                      150,
                                      250,
                                      350,
                                    },
                              pos_y = {
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                      -200,
                                      -20,
                                    },
                              size = {
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                      30,
                                      25,
                                    },
                            },
                    },
            }
return ConfigSysendless_chapter;