--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local pb_common_pb = require("Protol.pb_common_pb")
module('Protol.pb_21_pb')

PBRANK = protobuf.Descriptor();
PBRANK_TYPE_FIELD = protobuf.FieldDescriptor();
PBRANK_PAGE_FIELD = protobuf.FieldDescriptor();
PBRANK_NUM_FIELD = protobuf.FieldDescriptor();
PBRANKDATA = protobuf.Descriptor();
PBRANKDATA_RANK_LIST_FIELD = protobuf.FieldDescriptor();
PBRANKDATA_TYPE_FIELD = protobuf.FieldDescriptor();
PBRANKDATA_TOTAL_PAGE_FIELD = protobuf.FieldDescriptor();
PBRANKDATA_SELF_RANK_FIELD = protobuf.FieldDescriptor();
PBRANKDATA_SELF_VALUE_FIELD = protobuf.FieldDescriptor();
PBRANKLIST = protobuf.Descriptor();
PBRANKLIST_RANK_FIELD = protobuf.FieldDescriptor();
PBRANKLIST_ID_FIELD = protobuf.FieldDescriptor();
PBRANKLIST_NAME_FIELD = protobuf.FieldDescriptor();
PBRANKLIST_SEX_FIELD = protobuf.FieldDescriptor();
PBRANKLIST_LV_FIELD = protobuf.FieldDescriptor();
PBRANKLIST_VALUE_FIELD = protobuf.FieldDescriptor();
PBRANKLIST_POSITION_FIELD = protobuf.FieldDescriptor();
PBRANKLIST_HEAD_FIELD = protobuf.FieldDescriptor();

PBRANK_TYPE_FIELD.name = "type"
PBRANK_TYPE_FIELD.full_name = ".pbRank.type"
PBRANK_TYPE_FIELD.number = 1
PBRANK_TYPE_FIELD.index = 0
PBRANK_TYPE_FIELD.label = 1
PBRANK_TYPE_FIELD.has_default_value = false
PBRANK_TYPE_FIELD.default_value = 0
PBRANK_TYPE_FIELD.type = 5
PBRANK_TYPE_FIELD.cpp_type = 1

PBRANK_PAGE_FIELD.name = "page"
PBRANK_PAGE_FIELD.full_name = ".pbRank.page"
PBRANK_PAGE_FIELD.number = 2
PBRANK_PAGE_FIELD.index = 1
PBRANK_PAGE_FIELD.label = 1
PBRANK_PAGE_FIELD.has_default_value = false
PBRANK_PAGE_FIELD.default_value = 0
PBRANK_PAGE_FIELD.type = 5
PBRANK_PAGE_FIELD.cpp_type = 1

PBRANK_NUM_FIELD.name = "num"
PBRANK_NUM_FIELD.full_name = ".pbRank.num"
PBRANK_NUM_FIELD.number = 3
PBRANK_NUM_FIELD.index = 2
PBRANK_NUM_FIELD.label = 1
PBRANK_NUM_FIELD.has_default_value = false
PBRANK_NUM_FIELD.default_value = 0
PBRANK_NUM_FIELD.type = 5
PBRANK_NUM_FIELD.cpp_type = 1

PBRANK.name = "pbRank"
PBRANK.full_name = ".pbRank"
PBRANK.nested_types = {}
PBRANK.enum_types = {}
PBRANK.fields = {PBRANK_TYPE_FIELD, PBRANK_PAGE_FIELD, PBRANK_NUM_FIELD}
PBRANK.is_extendable = false
PBRANK.extensions = {}
PBRANKDATA_RANK_LIST_FIELD.name = "rank_list"
PBRANKDATA_RANK_LIST_FIELD.full_name = ".pbRankData.rank_list"
PBRANKDATA_RANK_LIST_FIELD.number = 1
PBRANKDATA_RANK_LIST_FIELD.index = 0
PBRANKDATA_RANK_LIST_FIELD.label = 3
PBRANKDATA_RANK_LIST_FIELD.has_default_value = false
PBRANKDATA_RANK_LIST_FIELD.default_value = {}
PBRANKDATA_RANK_LIST_FIELD.message_type = PBRANKLIST
PBRANKDATA_RANK_LIST_FIELD.type = 11
PBRANKDATA_RANK_LIST_FIELD.cpp_type = 10

PBRANKDATA_TYPE_FIELD.name = "type"
PBRANKDATA_TYPE_FIELD.full_name = ".pbRankData.type"
PBRANKDATA_TYPE_FIELD.number = 2
PBRANKDATA_TYPE_FIELD.index = 1
PBRANKDATA_TYPE_FIELD.label = 1
PBRANKDATA_TYPE_FIELD.has_default_value = false
PBRANKDATA_TYPE_FIELD.default_value = 0
PBRANKDATA_TYPE_FIELD.type = 5
PBRANKDATA_TYPE_FIELD.cpp_type = 1

PBRANKDATA_TOTAL_PAGE_FIELD.name = "total_page"
PBRANKDATA_TOTAL_PAGE_FIELD.full_name = ".pbRankData.total_page"
PBRANKDATA_TOTAL_PAGE_FIELD.number = 3
PBRANKDATA_TOTAL_PAGE_FIELD.index = 2
PBRANKDATA_TOTAL_PAGE_FIELD.label = 1
PBRANKDATA_TOTAL_PAGE_FIELD.has_default_value = false
PBRANKDATA_TOTAL_PAGE_FIELD.default_value = 0
PBRANKDATA_TOTAL_PAGE_FIELD.type = 5
PBRANKDATA_TOTAL_PAGE_FIELD.cpp_type = 1

PBRANKDATA_SELF_RANK_FIELD.name = "self_rank"
PBRANKDATA_SELF_RANK_FIELD.full_name = ".pbRankData.self_rank"
PBRANKDATA_SELF_RANK_FIELD.number = 4
PBRANKDATA_SELF_RANK_FIELD.index = 3
PBRANKDATA_SELF_RANK_FIELD.label = 1
PBRANKDATA_SELF_RANK_FIELD.has_default_value = false
PBRANKDATA_SELF_RANK_FIELD.default_value = 0
PBRANKDATA_SELF_RANK_FIELD.type = 5
PBRANKDATA_SELF_RANK_FIELD.cpp_type = 1

PBRANKDATA_SELF_VALUE_FIELD.name = "self_value"
PBRANKDATA_SELF_VALUE_FIELD.full_name = ".pbRankData.self_value"
PBRANKDATA_SELF_VALUE_FIELD.number = 5
PBRANKDATA_SELF_VALUE_FIELD.index = 4
PBRANKDATA_SELF_VALUE_FIELD.label = 1
PBRANKDATA_SELF_VALUE_FIELD.has_default_value = false
PBRANKDATA_SELF_VALUE_FIELD.default_value = 0
PBRANKDATA_SELF_VALUE_FIELD.type = 5
PBRANKDATA_SELF_VALUE_FIELD.cpp_type = 1

PBRANKDATA.name = "pbRankData"
PBRANKDATA.full_name = ".pbRankData"
PBRANKDATA.nested_types = {}
PBRANKDATA.enum_types = {}
PBRANKDATA.fields = {PBRANKDATA_RANK_LIST_FIELD, PBRANKDATA_TYPE_FIELD, PBRANKDATA_TOTAL_PAGE_FIELD, PBRANKDATA_SELF_RANK_FIELD, PBRANKDATA_SELF_VALUE_FIELD}
PBRANKDATA.is_extendable = false
PBRANKDATA.extensions = {}
PBRANKLIST_RANK_FIELD.name = "rank"
PBRANKLIST_RANK_FIELD.full_name = ".pbRankList.rank"
PBRANKLIST_RANK_FIELD.number = 1
PBRANKLIST_RANK_FIELD.index = 0
PBRANKLIST_RANK_FIELD.label = 1
PBRANKLIST_RANK_FIELD.has_default_value = false
PBRANKLIST_RANK_FIELD.default_value = 0
PBRANKLIST_RANK_FIELD.type = 5
PBRANKLIST_RANK_FIELD.cpp_type = 1

PBRANKLIST_ID_FIELD.name = "id"
PBRANKLIST_ID_FIELD.full_name = ".pbRankList.id"
PBRANKLIST_ID_FIELD.number = 2
PBRANKLIST_ID_FIELD.index = 1
PBRANKLIST_ID_FIELD.label = 1
PBRANKLIST_ID_FIELD.has_default_value = false
PBRANKLIST_ID_FIELD.default_value = 0
PBRANKLIST_ID_FIELD.type = 5
PBRANKLIST_ID_FIELD.cpp_type = 1

PBRANKLIST_NAME_FIELD.name = "name"
PBRANKLIST_NAME_FIELD.full_name = ".pbRankList.name"
PBRANKLIST_NAME_FIELD.number = 3
PBRANKLIST_NAME_FIELD.index = 2
PBRANKLIST_NAME_FIELD.label = 1
PBRANKLIST_NAME_FIELD.has_default_value = false
PBRANKLIST_NAME_FIELD.default_value = ""
PBRANKLIST_NAME_FIELD.type = 9
PBRANKLIST_NAME_FIELD.cpp_type = 9

PBRANKLIST_SEX_FIELD.name = "sex"
PBRANKLIST_SEX_FIELD.full_name = ".pbRankList.sex"
PBRANKLIST_SEX_FIELD.number = 4
PBRANKLIST_SEX_FIELD.index = 3
PBRANKLIST_SEX_FIELD.label = 1
PBRANKLIST_SEX_FIELD.has_default_value = false
PBRANKLIST_SEX_FIELD.default_value = 0
PBRANKLIST_SEX_FIELD.type = 5
PBRANKLIST_SEX_FIELD.cpp_type = 1

PBRANKLIST_LV_FIELD.name = "lv"
PBRANKLIST_LV_FIELD.full_name = ".pbRankList.lv"
PBRANKLIST_LV_FIELD.number = 5
PBRANKLIST_LV_FIELD.index = 4
PBRANKLIST_LV_FIELD.label = 1
PBRANKLIST_LV_FIELD.has_default_value = false
PBRANKLIST_LV_FIELD.default_value = 0
PBRANKLIST_LV_FIELD.type = 5
PBRANKLIST_LV_FIELD.cpp_type = 1

PBRANKLIST_VALUE_FIELD.name = "value"
PBRANKLIST_VALUE_FIELD.full_name = ".pbRankList.value"
PBRANKLIST_VALUE_FIELD.number = 6
PBRANKLIST_VALUE_FIELD.index = 5
PBRANKLIST_VALUE_FIELD.label = 1
PBRANKLIST_VALUE_FIELD.has_default_value = false
PBRANKLIST_VALUE_FIELD.default_value = 0
PBRANKLIST_VALUE_FIELD.type = 5
PBRANKLIST_VALUE_FIELD.cpp_type = 1

PBRANKLIST_POSITION_FIELD.name = "position"
PBRANKLIST_POSITION_FIELD.full_name = ".pbRankList.position"
PBRANKLIST_POSITION_FIELD.number = 7
PBRANKLIST_POSITION_FIELD.index = 6
PBRANKLIST_POSITION_FIELD.label = 1
PBRANKLIST_POSITION_FIELD.has_default_value = false
PBRANKLIST_POSITION_FIELD.default_value = 0
PBRANKLIST_POSITION_FIELD.type = 5
PBRANKLIST_POSITION_FIELD.cpp_type = 1

PBRANKLIST_HEAD_FIELD.name = "head"
PBRANKLIST_HEAD_FIELD.full_name = ".pbRankList.head"
PBRANKLIST_HEAD_FIELD.number = 8
PBRANKLIST_HEAD_FIELD.index = 7
PBRANKLIST_HEAD_FIELD.label = 1
PBRANKLIST_HEAD_FIELD.has_default_value = false
PBRANKLIST_HEAD_FIELD.default_value = 0
PBRANKLIST_HEAD_FIELD.type = 5
PBRANKLIST_HEAD_FIELD.cpp_type = 1

PBRANKLIST.name = "pbRankList"
PBRANKLIST.full_name = ".pbRankList"
PBRANKLIST.nested_types = {}
PBRANKLIST.enum_types = {}
PBRANKLIST.fields = {PBRANKLIST_RANK_FIELD, PBRANKLIST_ID_FIELD, PBRANKLIST_NAME_FIELD, PBRANKLIST_SEX_FIELD, PBRANKLIST_LV_FIELD, PBRANKLIST_VALUE_FIELD, PBRANKLIST_POSITION_FIELD, PBRANKLIST_HEAD_FIELD}
PBRANKLIST.is_extendable = false
PBRANKLIST.extensions = {}

pbRank = protobuf.Message(PBRANK)
pbRankData = protobuf.Message(PBRANKDATA)
pbRankList = protobuf.Message(PBRANKLIST)

