local fashion_suit1=[[礼服]]
local fashion_suit2=[[icon_003700]]
local fashion_suit3=[[]]
local fashion_suit4=[[学士服]]
local fashion_suit5=[[侠客服]]
local fashion_suit6=[[军装]]
local fashion_suit7=[[居家]]
local fashion_suit8=[[赏梅]]
local fashion_suit9=[[舞蹈服]]
local fashion_suit10=[[戏水]]
local fashion_suit11=[[婚礼]]
local fashion_suit12=[[官服]]
local fashion_suit13=[[意气风发]]
local fashion_suit14=[[番邦]]

local ConfigSysfashion_suit={
              [101] = {
                      suit = 101,
                      name = fashion_suit1,
                      describe = fashion_suit1,
                      skill_describe = fashion_suit1,
                      affect_describe = fashion_suit1,
                      icon = fashion_suit2,
                      components = {
                              1011,
                              1012,
                              1013,
                              1014,
                            },
                      effect = fashion_suit3,
                      type = 1,
                      sex = 1,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20001,
                    },
              [102] = {
                      suit = 102,
                      name = fashion_suit4,
                      describe = fashion_suit4,
                      skill_describe = fashion_suit4,
                      affect_describe = fashion_suit4,
                      icon = fashion_suit2,
                      components = {
                              1021,
                              1022,
                              1023,
                              1024,
                            },
                      effect = fashion_suit3,
                      type = 2,
                      sex = 1,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20002,
                    },
              [103] = {
                      suit = 103,
                      name = fashion_suit5,
                      describe = fashion_suit5,
                      skill_describe = fashion_suit5,
                      affect_describe = fashion_suit5,
                      icon = fashion_suit2,
                      components = {
                              1031,
                              1032,
                              1033,
                              1034,
                            },
                      effect = fashion_suit3,
                      type = 3,
                      sex = 1,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20003,
                    },
              [104] = {
                      suit = 104,
                      name = fashion_suit6,
                      describe = fashion_suit6,
                      skill_describe = fashion_suit6,
                      affect_describe = fashion_suit6,
                      icon = fashion_suit2,
                      components = {
                              1041,
                              1042,
                              1043,
                              1044,
                            },
                      effect = fashion_suit3,
                      type = 4,
                      sex = 1,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20004,
                    },
              [105] = {
                      suit = 105,
                      name = fashion_suit7,
                      describe = fashion_suit7,
                      skill_describe = fashion_suit7,
                      affect_describe = fashion_suit7,
                      icon = fashion_suit2,
                      components = {
                              1051,
                              1052,
                              1053,
                              1054,
                            },
                      effect = fashion_suit3,
                      type = 5,
                      sex = 1,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20001,
                    },
              [106] = {
                      suit = 106,
                      name = fashion_suit8,
                      describe = fashion_suit8,
                      skill_describe = fashion_suit8,
                      affect_describe = fashion_suit8,
                      icon = fashion_suit2,
                      components = {
                              1061,
                              1062,
                              1063,
                              1064,
                            },
                      effect = fashion_suit3,
                      type = 1,
                      sex = 1,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20002,
                    },
              [107] = {
                      suit = 107,
                      name = fashion_suit9,
                      describe = fashion_suit9,
                      skill_describe = fashion_suit9,
                      affect_describe = fashion_suit9,
                      icon = fashion_suit2,
                      components = {
                              1071,
                              1072,
                              1073,
                              1074,
                            },
                      effect = fashion_suit3,
                      type = 2,
                      sex = 1,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20003,
                    },
              [108] = {
                      suit = 108,
                      name = fashion_suit10,
                      describe = fashion_suit10,
                      skill_describe = fashion_suit10,
                      affect_describe = fashion_suit10,
                      icon = fashion_suit2,
                      components = {
                              1081,
                              1082,
                              1083,
                              1084,
                            },
                      effect = fashion_suit3,
                      type = 3,
                      sex = 1,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20004,
                    },
              [109] = {
                      suit = 109,
                      name = fashion_suit11,
                      describe = fashion_suit11,
                      skill_describe = fashion_suit11,
                      affect_describe = fashion_suit11,
                      icon = fashion_suit2,
                      components = {
                              1091,
                              1092,
                              1093,
                              1094,
                            },
                      effect = fashion_suit3,
                      type = 4,
                      sex = 1,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20001,
                    },
              [110] = {
                      suit = 110,
                      name = fashion_suit12,
                      describe = fashion_suit12,
                      skill_describe = fashion_suit12,
                      affect_describe = fashion_suit12,
                      icon = fashion_suit2,
                      components = {
                              1101,
                              1102,
                              1103,
                              1104,
                            },
                      effect = fashion_suit3,
                      type = 5,
                      sex = 1,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20002,
                    },
              [111] = {
                      suit = 111,
                      name = fashion_suit13,
                      describe = fashion_suit13,
                      skill_describe = fashion_suit13,
                      affect_describe = fashion_suit13,
                      icon = fashion_suit2,
                      components = {
                              1111,
                              1112,
                              1113,
                              1114,
                            },
                      effect = fashion_suit3,
                      type = 1,
                      sex = 1,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20003,
                    },
              [112] = {
                      suit = 112,
                      name = fashion_suit14,
                      describe = fashion_suit14,
                      skill_describe = fashion_suit14,
                      affect_describe = fashion_suit14,
                      icon = fashion_suit2,
                      components = {
                              1121,
                              1122,
                              1123,
                              1124,
                            },
                      effect = fashion_suit3,
                      type = 2,
                      sex = 1,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20004,
                    },
              [201] = {
                      suit = 201,
                      name = fashion_suit1,
                      describe = fashion_suit1,
                      skill_describe = fashion_suit1,
                      affect_describe = fashion_suit1,
                      icon = fashion_suit2,
                      components = {
                              2011,
                              2012,
                              2013,
                              2014,
                            },
                      effect = fashion_suit3,
                      type = 1,
                      sex = 2,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20001,
                    },
              [202] = {
                      suit = 202,
                      name = fashion_suit4,
                      describe = fashion_suit4,
                      skill_describe = fashion_suit4,
                      affect_describe = fashion_suit4,
                      icon = fashion_suit2,
                      components = {
                              2021,
                              2022,
                              2023,
                              2024,
                            },
                      effect = fashion_suit3,
                      type = 2,
                      sex = 2,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20002,
                    },
              [203] = {
                      suit = 203,
                      name = fashion_suit5,
                      describe = fashion_suit5,
                      skill_describe = fashion_suit5,
                      affect_describe = fashion_suit5,
                      icon = fashion_suit2,
                      components = {
                              2031,
                              2032,
                              2033,
                              2034,
                            },
                      effect = fashion_suit3,
                      type = 3,
                      sex = 2,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20003,
                    },
              [204] = {
                      suit = 204,
                      name = fashion_suit6,
                      describe = fashion_suit6,
                      skill_describe = fashion_suit6,
                      affect_describe = fashion_suit6,
                      icon = fashion_suit2,
                      components = {
                              2041,
                              2042,
                              2043,
                              2044,
                            },
                      effect = fashion_suit3,
                      type = 4,
                      sex = 2,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20004,
                    },
              [205] = {
                      suit = 205,
                      name = fashion_suit7,
                      describe = fashion_suit7,
                      skill_describe = fashion_suit7,
                      affect_describe = fashion_suit7,
                      icon = fashion_suit2,
                      components = {
                              2051,
                              2052,
                              2053,
                              2054,
                            },
                      effect = fashion_suit3,
                      type = 5,
                      sex = 2,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20001,
                    },
              [206] = {
                      suit = 206,
                      name = fashion_suit8,
                      describe = fashion_suit8,
                      skill_describe = fashion_suit8,
                      affect_describe = fashion_suit8,
                      icon = fashion_suit2,
                      components = {
                              2061,
                              2062,
                              2063,
                              2064,
                            },
                      effect = fashion_suit3,
                      type = 1,
                      sex = 2,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20002,
                    },
              [207] = {
                      suit = 207,
                      name = fashion_suit9,
                      describe = fashion_suit9,
                      skill_describe = fashion_suit9,
                      affect_describe = fashion_suit9,
                      icon = fashion_suit2,
                      components = {
                              2071,
                              2072,
                              2073,
                              2074,
                            },
                      effect = fashion_suit3,
                      type = 2,
                      sex = 2,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20003,
                    },
              [208] = {
                      suit = 208,
                      name = fashion_suit10,
                      describe = fashion_suit10,
                      skill_describe = fashion_suit10,
                      affect_describe = fashion_suit10,
                      icon = fashion_suit2,
                      components = {
                              2081,
                              2082,
                              2083,
                              2084,
                            },
                      effect = fashion_suit3,
                      type = 3,
                      sex = 2,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20004,
                    },
              [209] = {
                      suit = 209,
                      name = fashion_suit11,
                      describe = fashion_suit11,
                      skill_describe = fashion_suit11,
                      affect_describe = fashion_suit11,
                      icon = fashion_suit2,
                      components = {
                              2091,
                              2092,
                              2093,
                              2094,
                            },
                      effect = fashion_suit3,
                      type = 4,
                      sex = 2,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20001,
                    },
              [210] = {
                      suit = 210,
                      name = fashion_suit12,
                      describe = fashion_suit12,
                      skill_describe = fashion_suit12,
                      affect_describe = fashion_suit12,
                      icon = fashion_suit2,
                      components = {
                              2101,
                              2102,
                              2103,
                              2104,
                            },
                      effect = fashion_suit3,
                      type = 5,
                      sex = 2,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20002,
                    },
              [211] = {
                      suit = 211,
                      name = fashion_suit13,
                      describe = fashion_suit13,
                      skill_describe = fashion_suit13,
                      affect_describe = fashion_suit13,
                      icon = fashion_suit2,
                      components = {
                              2111,
                              2112,
                              2113,
                              2114,
                            },
                      effect = fashion_suit3,
                      type = 1,
                      sex = 2,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20003,
                    },
              [212] = {
                      suit = 212,
                      name = fashion_suit14,
                      describe = fashion_suit14,
                      skill_describe = fashion_suit14,
                      affect_describe = fashion_suit14,
                      icon = fashion_suit2,
                      components = {
                              2121,
                              2122,
                              2123,
                              2124,
                            },
                      effect = fashion_suit3,
                      type = 2,
                      sex = 2,
                      modification = {
                              100,
                              100,
                              100,
                              100,
                            },
                      affect = {
                              1,
                              2,
                              3,
                            },
                      skill = 20004,
                    },
            }
return ConfigSysfashion_suit;