--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local pb_common_pb = require("Protol.pb_common_pb")
module('Protol.pb_27_pb')

PBITEM = protobuf.Descriptor();
PBITEM_ID_FIELD = protobuf.FieldDescriptor();
PBITEM_ITEM_ID_FIELD = protobuf.FieldDescriptor();
PBITEM_COUNT_FIELD = protobuf.FieldDescriptor();
PBITEMLIST = protobuf.Descriptor();
PBITEMLIST_TYPE_FIELD = protobuf.FieldDescriptor();
PBITEMLIST_LIST_FIELD = protobuf.FieldDescriptor();
PBITEMSELL = protobuf.Descriptor();
PBITEMSELL_TYPE_FIELD = protobuf.FieldDescriptor();
PBITEMSELL_ID_FIELD = protobuf.FieldDescriptor();
PBITEMSELL_COUNT_FIELD = protobuf.FieldDescriptor();

PBITEM_ID_FIELD.name = "id"
PBITEM_ID_FIELD.full_name = ".pbItem.id"
PBITEM_ID_FIELD.number = 1
PBITEM_ID_FIELD.index = 0
PBITEM_ID_FIELD.label = 2
PBITEM_ID_FIELD.has_default_value = false
PBITEM_ID_FIELD.default_value = 0
PBITEM_ID_FIELD.type = 5
PBITEM_ID_FIELD.cpp_type = 1

PBITEM_ITEM_ID_FIELD.name = "item_id"
PBITEM_ITEM_ID_FIELD.full_name = ".pbItem.item_id"
PBITEM_ITEM_ID_FIELD.number = 2
PBITEM_ITEM_ID_FIELD.index = 1
PBITEM_ITEM_ID_FIELD.label = 2
PBITEM_ITEM_ID_FIELD.has_default_value = false
PBITEM_ITEM_ID_FIELD.default_value = 0
PBITEM_ITEM_ID_FIELD.type = 5
PBITEM_ITEM_ID_FIELD.cpp_type = 1

PBITEM_COUNT_FIELD.name = "count"
PBITEM_COUNT_FIELD.full_name = ".pbItem.count"
PBITEM_COUNT_FIELD.number = 3
PBITEM_COUNT_FIELD.index = 2
PBITEM_COUNT_FIELD.label = 2
PBITEM_COUNT_FIELD.has_default_value = false
PBITEM_COUNT_FIELD.default_value = 0
PBITEM_COUNT_FIELD.type = 5
PBITEM_COUNT_FIELD.cpp_type = 1

PBITEM.name = "pbItem"
PBITEM.full_name = ".pbItem"
PBITEM.nested_types = {}
PBITEM.enum_types = {}
PBITEM.fields = {PBITEM_ID_FIELD, PBITEM_ITEM_ID_FIELD, PBITEM_COUNT_FIELD}
PBITEM.is_extendable = false
PBITEM.extensions = {}
PBITEMLIST_TYPE_FIELD.name = "type"
PBITEMLIST_TYPE_FIELD.full_name = ".pbItemList.type"
PBITEMLIST_TYPE_FIELD.number = 1
PBITEMLIST_TYPE_FIELD.index = 0
PBITEMLIST_TYPE_FIELD.label = 2
PBITEMLIST_TYPE_FIELD.has_default_value = false
PBITEMLIST_TYPE_FIELD.default_value = 0
PBITEMLIST_TYPE_FIELD.type = 5
PBITEMLIST_TYPE_FIELD.cpp_type = 1

PBITEMLIST_LIST_FIELD.name = "list"
PBITEMLIST_LIST_FIELD.full_name = ".pbItemList.list"
PBITEMLIST_LIST_FIELD.number = 2
PBITEMLIST_LIST_FIELD.index = 1
PBITEMLIST_LIST_FIELD.label = 3
PBITEMLIST_LIST_FIELD.has_default_value = false
PBITEMLIST_LIST_FIELD.default_value = {}
PBITEMLIST_LIST_FIELD.message_type = PBITEM
PBITEMLIST_LIST_FIELD.type = 11
PBITEMLIST_LIST_FIELD.cpp_type = 10

PBITEMLIST.name = "pbItemList"
PBITEMLIST.full_name = ".pbItemList"
PBITEMLIST.nested_types = {}
PBITEMLIST.enum_types = {}
PBITEMLIST.fields = {PBITEMLIST_TYPE_FIELD, PBITEMLIST_LIST_FIELD}
PBITEMLIST.is_extendable = false
PBITEMLIST.extensions = {}
PBITEMSELL_TYPE_FIELD.name = "type"
PBITEMSELL_TYPE_FIELD.full_name = ".pbItemSell.type"
PBITEMSELL_TYPE_FIELD.number = 1
PBITEMSELL_TYPE_FIELD.index = 0
PBITEMSELL_TYPE_FIELD.label = 2
PBITEMSELL_TYPE_FIELD.has_default_value = false
PBITEMSELL_TYPE_FIELD.default_value = 0
PBITEMSELL_TYPE_FIELD.type = 5
PBITEMSELL_TYPE_FIELD.cpp_type = 1

PBITEMSELL_ID_FIELD.name = "id"
PBITEMSELL_ID_FIELD.full_name = ".pbItemSell.id"
PBITEMSELL_ID_FIELD.number = 2
PBITEMSELL_ID_FIELD.index = 1
PBITEMSELL_ID_FIELD.label = 2
PBITEMSELL_ID_FIELD.has_default_value = false
PBITEMSELL_ID_FIELD.default_value = 0
PBITEMSELL_ID_FIELD.type = 5
PBITEMSELL_ID_FIELD.cpp_type = 1

PBITEMSELL_COUNT_FIELD.name = "count"
PBITEMSELL_COUNT_FIELD.full_name = ".pbItemSell.count"
PBITEMSELL_COUNT_FIELD.number = 3
PBITEMSELL_COUNT_FIELD.index = 2
PBITEMSELL_COUNT_FIELD.label = 2
PBITEMSELL_COUNT_FIELD.has_default_value = false
PBITEMSELL_COUNT_FIELD.default_value = 0
PBITEMSELL_COUNT_FIELD.type = 5
PBITEMSELL_COUNT_FIELD.cpp_type = 1

PBITEMSELL.name = "pbItemSell"
PBITEMSELL.full_name = ".pbItemSell"
PBITEMSELL.nested_types = {}
PBITEMSELL.enum_types = {}
PBITEMSELL.fields = {PBITEMSELL_TYPE_FIELD, PBITEMSELL_ID_FIELD, PBITEMSELL_COUNT_FIELD}
PBITEMSELL.is_extendable = false
PBITEMSELL.extensions = {}

pbItem = protobuf.Message(PBITEM)
pbItemList = protobuf.Message(PBITEMLIST)
pbItemSell = protobuf.Message(PBITEMSELL)

