local proto_data1=[[null]]
local proto_data2=[[]]
local proto_data3=[[pbId32]]
local proto_data4=[[pbResult]]
local proto_data5=[[pbId64]]
local proto_data6=[[pbPartnerSkillUp]]
local proto_data7=[[pbId32R]]
local proto_data8=[[pbGoodList]]
local proto_data9=[[pbEqipModelStrength]]
local proto_data10=[[强化]]
local proto_data11=[[pbAttributeWash]]
local proto_data12=[[pbEqipModelRe]]
local proto_data13=[[pbDungeonBattleResult]]
local proto_data14=[[pbDungeonBattle]]
local proto_data15=[[pbMailInfo]]
local proto_data16=[[pbFriendList]]
local proto_data17=[[pbFriend]]
local proto_data18=[[pbPlotDungeonBattleResult]]
local proto_data19=[[pbNpc]]
local proto_data20=[[pbArenaVsPlayerDefense]]
local proto_data21=[[pbVsPlayer]]
local proto_data22=[[pbPromoteArena]]
local proto_data23=[[pbDefensePos]]
local proto_data24=[[pbReward]]
local proto_data25=[[pbVsResult]]
local proto_data26=[[pbDraftResult]]
local proto_data27=[[pbArena]]
local proto_data28=[[pbArenaDefensePos]]
local proto_data29=[[pbArenaVsPlayer]]
local proto_data30=[[pbArenaReward]]
local proto_data31=[[pbArenaVsResult]]
local proto_data32=[[pbShopList]]
local proto_data33=[[pbMonarchGetSkills]]
local proto_data34=[[pbTaskList]]
local proto_data35=[[pbMansion]]
local proto_data36=[[pbString]]
local proto_data37=[[pbMansionServantList]]
local proto_data38=[[pbMansionServantChangeName]]
local proto_data39=[[pbMansionPlantPlanlist]]
local proto_data40=[[pbItemList]]
local proto_data41=[[pbEliteDungeonBattleResult]]
local proto_data42=[[pbEliteDungeonBattle]]
local proto_data43=[[pbGuide]]
local proto_data44=[[pbFashionList]]
local proto_data45=[[pbFashion]]
local proto_data46=[[pbWorshipReward]]
local proto_data47=[[pbTalentList]]
local proto_data48=[[pbTalent]]
local proto_data49=[[pbTalentModelStrength]]
local proto_data50=[[pbTalentAttributeAdd]]
local proto_data51=[[pbChildList]]
local proto_data52=[[pbChildModel]]

local ConfigSysproto_data={
              [9001] = {
                      s2c = [[pbError]],
                      c2s = proto_data1,
                      memo = [[错误提示代号]],
                      constStr = [[ERROR_CODE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [9002] = {
                      s2c = [[pbPlayerBase]],
                      c2s = proto_data1,
                      memo = [[人物属性数据]],
                      constStr = [[PLAYER_BASE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [9003] = {
                      s2c = [[pbOtherPlayerBase]],
                      c2s = proto_data3,
                      memo = [[查看其他玩家信息]],
                      constStr = [[PLAYER_OTHER_BASE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [9005] = {
                      s2c = proto_data3,
                      c2s = proto_data3,
                      memo = [[更改主角头像]],
                      constStr = [[PLAYER_CHANGE_HEAD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [9006] = {
                      s2c = [[pbPlayerChange]],
                      c2s = proto_data1,
                      memo = [[玩家信息更新]],
                      constStr = [[PLAYER_CHANGE_INFO]],
                      arg = proto_data2,
                      back = 1,
                    },
              [10000] = {
                      s2c = [[pbAccountInit]],
                      c2s = [[pbAccount]],
                      memo = [[登录和创角]],
                      constStr = [[LOGIN]],
                      arg = proto_data2,
                      back = 1,
                    },
              [10001] = {
                      s2c = proto_data4,
                      c2s = proto_data4,
                      memo = [[心跳包]],
                      constStr = [[KEEP_HEART]],
                      arg = proto_data2,
                      back = 0,
                    },
              [10002] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[新进程开启需要到登陆界面]],
                      constStr = [[LOGIN_OK_SERVER]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11001] = {
                      s2c = [[pbPartnerList]],
                      c2s = proto_data1,
                      memo = [[获取随从信息]],
                      constStr = [[PARTNER_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11002] = {
                      s2c = proto_data4,
                      c2s = proto_data5,
                      memo = [[随从升级]],
                      constStr = [[PARTNER_LV_UP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11003] = {
                      s2c = proto_data4,
                      c2s = [[pbPartnerModel]],
                      memo = [[随从切换形象]],
                      constStr = [[PARTNER_MODEL_CHANGE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11004] = {
                      s2c = proto_data6,
                      c2s = [[pbPartnerSkillUpOp]],
                      memo = [[随从技能升级]],
                      constStr = [[PARTNER_SKILL_UP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11005] = {
                      s2c = proto_data4,
                      c2s = proto_data5,
                      memo = [[随从晋封]],
                      constStr = [[PARTNER_POSITION_UP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11006] = {
                      s2c = [[pbId64R]],
                      c2s = proto_data1,
                      memo = [[随从上阵列表]],
                      constStr = [[PARTNER_IN_CAMP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11007] = {
                      s2c = proto_data4,
                      c2s = [[pbPartnerBreakOut]],
                      memo = [[随从突破]],
                      constStr = [[PARTNER_BREAK_OUT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11008] = {
                      s2c = proto_data1,
                      c2s = [[pbPartnerMemoir]],
                      memo = [[随从通关传记]],
                      constStr = [[PARTNER_PASS_MEMOIR]],
                      arg = proto_data2,
                      back = 0,
                    },
              [11010] = {
                      s2c = proto_data6,
                      c2s = proto_data3,
                      memo = [[主角技能激活/升级]],
                      constStr = [[PARTNER_MAIN_SKILL_UP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11011] = {
                      s2c = proto_data1,
                      c2s = proto_data3,
                      memo = [[主角培养放弃/保存]],
                      constStr = [[PARTNER_TRAIN_OP]],
                      arg = proto_data2,
                      back = 0,
                    },
              [11012] = {
                      s2c = proto_data4,
                      c2s = [[pbPartnerSkillUse]],
                      memo = [[主角技能使用]],
                      constStr = [[PARTNER_MAIN_SKILL_USE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11013] = {
                      s2c = [[pbPartnerAdd]],
                      c2s = proto_data1,
                      memo = [[新增随从]],
                      constStr = [[PARTNER_ADD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11014] = {
                      s2c = proto_data4,
                      c2s = [[pbPartnerChangeName]],
                      memo = [[修改随从昵称]],
                      constStr = [[PARTNER_CHANGE_NAME]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11015] = {
                      s2c = proto_data4,
                      c2s = proto_data5,
                      memo = [[随从删除]],
                      constStr = [[PARTNER_DELETE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11016] = {
                      s2c = proto_data4,
                      c2s = [[pbPartnerLock]],
                      memo = [[锁定/解锁随从]],
                      constStr = [[PARTNER_LOCK]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11017] = {
                      s2c = proto_data7,
                      c2s = proto_data3,
                      memo = [[主角培养]],
                      constStr = [[PARTNER_TRAIN]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11018] = {
                      s2c = [[pbPartnerCommentList]],
                      c2s = proto_data3,
                      memo = [[请求随从评价]],
                      constStr = [[PARTNER_COMMENT_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11019] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[随从评价点赞]],
                      constStr = [[PARTNER_COMMENT_VOTE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11020] = {
                      s2c = proto_data4,
                      c2s = [[pbPartnerCommentAdd]],
                      memo = [[新增随从评价]],
                      constStr = [[PARTNER_COMMENT_ADD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [11021] = {
                      s2c = [[pbPartner]],
                      c2s = [[pbPartnerLook]],
                      memo = [[查看随从]],
                      constStr = [[PARTNER_COMMENT_LOOK]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12000] = {
                      s2c = proto_data8,
                      c2s = proto_data1,
                      memo = [[背包]],
                      constStr = [[PLAYER_BAG]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12001] = {
                      s2c = proto_data8,
                      c2s = proto_data1,
                      memo = [[背包物品刷新]],
                      constStr = [[PLAYER_BAG_REFRESH]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12002] = {
                      s2c = proto_data4,
                      c2s = [[pbGoodSell]],
                      memo = [[出售物品]],
                      constStr = [[PLAYER_SELL_GOOD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12003] = {
                      s2c = proto_data4,
                      c2s = [[pbGoodModel]],
                      memo = [[使用物品]],
                      constStr = [[PLAYER_USE_GOOD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12011] = {
                      s2c = [[pbEquip]],
                      c2s = [[pbEqipModel]],
                      memo = [[穿戴]],
                      constStr = [[PLAYER_WEAR_EQUIP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12012] = {
                      s2c = proto_data4,
                      c2s = [[pbEqipModelRemove]],
                      memo = [[卸下]],
                      constStr = [[PLAYER_REMOVE_EQUIP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12013] = {
                      s2c = proto_data4,
                      c2s = proto_data9,
                      memo = proto_data10,
                      constStr = [[PLAYER_STRENGTH_EQUIP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12014] = {
                      s2c = proto_data11,
                      c2s = proto_data9,
                      memo = [[鉴定]],
                      constStr = [[PLAYER_IDENTYFY_EQUIP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12015] = {
                      s2c = proto_data11,
                      c2s = proto_data12,
                      memo = [[重琢]],
                      constStr = [[PLAYER_REDENTYFY_EQUIP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12016] = {
                      s2c = proto_data11,
                      c2s = proto_data12,
                      memo = [[精雕]],
                      constStr = [[PLAYER_UPDENTYFY_EQUIP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12017] = {
                      s2c = proto_data4,
                      c2s = [[pbEqipModelUp]],
                      memo = [[打磨]],
                      constStr = [[PLAYER_UPGRADE_STAR_EQUIP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12018] = {
                      s2c = [[pbNewAddAttribute]],
                      c2s = proto_data9,
                      memo = [[抛光]],
                      constStr = [[PLAYER_UPGRADE_COLOR_EQUIP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [12019] = {
                      s2c = proto_data4,
                      c2s = proto_data9,
                      memo = [[一键强化]],
                      constStr = [[PLAYER_STRENGTH_TOP_EQUIP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [13000] = {
                      s2c = [[pbDungeonList]],
                      c2s = proto_data1,
                      memo = [[请求挑战副本信息]],
                      constStr = [[DUNGEON_INFO]],
                      arg = proto_data2,
                      back = 1,
                    },
              [13001] = {
                      s2c = proto_data13,
                      c2s = proto_data14,
                      memo = [[请求挑战副本]],
                      constStr = [[DUNGEON_START_BATTLE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [13002] = {
                      s2c = proto_data13,
                      c2s = [[pbDungeonOver]],
                      memo = [[挑战副本结果]],
                      constStr = [[DUNGEON_BATTLE_RESULT]],
                      arg = proto_data2,
                      back = 0,
                    },
              [13003] = {
                      s2c = proto_data4,
                      c2s = proto_data14,
                      memo = [[复活再战]],
                      constStr = [[DUNGEON_REBORN_BATTLE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [13004] = {
                      s2c = [[pbDungeonPartnerInfo]],
                      c2s = proto_data3,
                      memo = [[请求随从通关出场率]],
                      constStr = [[DUNGEON_PARTNER_INFO]],
                      arg = proto_data2,
                      back = 1,
                    },
              [14000] = {
                      s2c = [[pbClimbTowers]],
                      c2s = proto_data7,
                      memo = [[获取爬塔信息]],
                      constStr = [[CLIMB_TOWERS]],
                      arg = proto_data2,
                      back = 1,
                    },
              [14001] = {
                      s2c = [[pbEnterResult]],
                      c2s = [[pbEnter]],
                      memo = [[进入爬塔关卡]],
                      constStr = [[CLIMB_TOWER_ENTER]],
                      arg = proto_data2,
                      back = 1,
                    },
              [14002] = {
                      s2c = [[pbClimbTowerResult]],
                      c2s = [[pbClimbTowerOver]],
                      memo = [[爬塔战斗结果]],
                      constStr = [[CLIMB_TOWER_RESULT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [14003] = {
                      s2c = proto_data1,
                      c2s = [[pbClimbTowerUpdateStory]],
                      memo = [[更新剧情]],
                      constStr = [[CLIMB_TOWER_UPDATE_STORY]],
                      arg = proto_data2,
                      back = 0,
                    },
              [15000] = {
                      s2c = [[pbMailsInfo]],
                      c2s = proto_data1,
                      memo = [[请求邮件列表]],
                      constStr = [[MAIL_MAILS_INFO]],
                      arg = proto_data2,
                      back = 1,
                    },
              [15001] = {
                      s2c = proto_data15,
                      c2s = proto_data3,
                      memo = [[查看邮件]],
                      constStr = [[MAIL_READ]],
                      arg = proto_data2,
                      back = 1,
                    },
              [15002] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[删除邮件]],
                      constStr = [[MAIL_DEL]],
                      arg = proto_data2,
                      back = 1,
                    },
              [15003] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[一键删除]],
                      constStr = [[MAIL_DEL_ALL]],
                      arg = proto_data2,
                      back = 1,
                    },
              [15004] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[一键领取]],
                      constStr = [[MAIL_GET_AWARD_ALL]],
                      arg = proto_data2,
                      back = 1,
                    },
              [15005] = {
                      s2c = proto_data15,
                      c2s = proto_data3,
                      memo = [[领取邮件]],
                      constStr = [[MAIL_GET_AWARD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [15006] = {
                      s2c = [[pbMailIntro]],
                      c2s = proto_data1,
                      memo = [[增加邮件]],
                      constStr = [[MAIL_ADD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [17000] = {
                      s2c = proto_data1,
                      c2s = [[pbChat]],
                      memo = [[发送聊天消息]],
                      constStr = [[CHAT_SEND]],
                      arg = proto_data2,
                      back = 1,
                    },
              [17001] = {
                      s2c = [[pbReturnChat]],
                      c2s = proto_data1,
                      memo = [[收到聊天消息]],
                      constStr = [[CHAT_RECEIVE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [17002] = {
                      s2c = [[pbContactPersons]],
                      c2s = proto_data1,
                      memo = [[请求最近联系人]],
                      constStr = [[CHAT_CONTACT_PERSONS]],
                      arg = proto_data2,
                      back = 1,
                    },
              [17003] = {
                      s2c = [[pbReturnChats]],
                      c2s = proto_data3,
                      memo = [[查询与某人的私聊信息]],
                      constStr = [[CHAT_PRIVATE_MESSAGE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [17004] = {
                      s2c = [[pbContactPerson]],
                      c2s = proto_data1,
                      memo = [[更新最新联系人]],
                      constStr = [[CHAT_UPDATE_CONTACT_PERSON]],
                      arg = proto_data2,
                      back = 1,
                    },
              [17005] = {
                      s2c = [[pbBroadcastNotice]],
                      c2s = proto_data1,
                      memo = [[收到公告消息]],
                      constStr = [[CHAT_NOTICE_MESSAGE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [17009] = {
                      s2c = [[pbChatGmList]],
                      c2s = proto_data1,
                      memo = [[获取GAME MASTER]],
                      constStr = [[CHAT_GM_MASTER]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16000] = {
                      s2c = proto_data16,
                      c2s = proto_data1,
                      memo = [[好友列表]],
                      constStr = [[PLAYER_FRIENDS_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16001] = {
                      s2c = proto_data4,
                      c2s = proto_data17,
                      memo = [[接收体力]],
                      constStr = [[PLAYER_RECEIVE_ENERGY]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16002] = {
                      s2c = proto_data4,
                      c2s = proto_data17,
                      memo = [[发送体力]],
                      constStr = [[PLAYER_SEND_ENERGY]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16003] = {
                      s2c = proto_data4,
                      c2s = proto_data17,
                      memo = [[删除好友]],
                      constStr = [[PLAYER_DELETE_FRIEND]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16004] = {
                      s2c = proto_data16,
                      c2s = [[pbFriendS]],
                      memo = [[查找]],
                      constStr = [[PLAYER_SEARCH_FRIEND]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16005] = {
                      s2c = proto_data4,
                      c2s = proto_data17,
                      memo = [[加好友]],
                      constStr = [[PLAYER_ADD_FRIEND]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16006] = {
                      s2c = proto_data16,
                      c2s = proto_data1,
                      memo = [[申请列表]],
                      constStr = [[PLAYER_FRIEND_REQUEST_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16007] = {
                      s2c = proto_data4,
                      c2s = [[pbFriendR]],
                      memo = [[接受/拒接]],
                      constStr = [[PLAYER_FRIEND_REQUEST_HANDLE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16008] = {
                      s2c = proto_data16,
                      c2s = proto_data1,
                      memo = [[黑名单列表]],
                      constStr = [[PLAYER_FRIEND_BLACK_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16009] = {
                      s2c = proto_data4,
                      c2s = proto_data17,
                      memo = [[解禁黑名单]],
                      constStr = [[PLAYER_FRIEND_UNBLOCK_BLACK]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16010] = {
                      s2c = proto_data16,
                      c2s = proto_data1,
                      memo = [[仇敌列表]],
                      constStr = [[PLAYER_FRIEND_ENEMY_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16011] = {
                      s2c = proto_data4,
                      c2s = proto_data17,
                      memo = [[删除仇敌]],
                      constStr = [[PLAYER_FRIEND_DELETE_ENEMY]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16012] = {
                      s2c = proto_data4,
                      c2s = proto_data17,
                      memo = [[加入黑名单]],
                      constStr = [[PLAYER_FRIEND_ADD_TO_BLACK]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16013] = {
                      s2c = [[pbOtherPlayer]],
                      c2s = proto_data17,
                      memo = [[查看玩家]],
                      constStr = [[PLAYER_FRIEND_OTHER_PLAYER_INFO]],
                      arg = proto_data2,
                      back = 1,
                    },
              [16014] = {
                      s2c = proto_data16,
                      c2s = proto_data1,
                      memo = [[推荐列表]],
                      constStr = [[PLAYER_FRIEND_RECOMMEND_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [18000] = {
                      s2c = [[pbPlotDungeonInfo]],
                      c2s = proto_data1,
                      memo = [[请求主线副本信息]],
                      constStr = [[DUNGEON_PLOT_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [18001] = {
                      s2c = proto_data18,
                      c2s = proto_data3,
                      memo = [[请求挑战主线副本]],
                      constStr = [[DUNGEON_PLOT_BATTLE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [18002] = {
                      s2c = proto_data18,
                      c2s = [[pbPlotDungeonOver]],
                      memo = [[挑战主线副本结果]],
                      constStr = [[DUNGEON_PLOT_BATTLE_OVER]],
                      arg = proto_data2,
                      back = 1,
                    },
              [18003] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[通知播放完前置剧情]],
                      constStr = [[DUNGEON_PLOT_PLAY]],
                      arg = proto_data2,
                      back = 1,
                    },
              [18004] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[主线副本复活再战]],
                      constStr = [[DUNGEON_PLOT_REBORN]],
                      arg = proto_data2,
                      back = 1,
                    },
              [18005] = {
                      s2c = [[pbPlotDungeonSweepResult]],
                      c2s = proto_data3,
                      memo = [[剧情副本章节扫荡]],
                      constStr = [[DUNGEON_PLOT_SWEEP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19000] = {
                      s2c = [[pbSignInfo]],
                      c2s = proto_data19,
                      memo = [[报考界面]],
                      constStr = [[PLAYER_PROMOTE_INFO]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19001] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[报考]],
                      constStr = [[PLAYER_PROMOTE_SIGN]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19002] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[开始考试]],
                      constStr = [[PLAYER_PROMOTE_START]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19003] = {
                      s2c = proto_data4,
                      c2s = [[pbAnswer]],
                      memo = [[提交答案]],
                      constStr = [[PLAYER_PROMOTE_ANSWER]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19004] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[重考当前阶段]],
                      constStr = [[PLAYER_PROMOTE_RESTART]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19005] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[进入下一阶段]],
                      constStr = [[PLAYER_PROMOTE_NEXT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19006] = {
                      s2c = [[pbNpcResultList]],
                      c2s = proto_data1,
                      memo = [[评判结果]],
                      constStr = [[PLAYER_PROMOTE_RESULT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19007] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[放弃重考]],
                      constStr = [[PLAYER_PROMOTE_RESET]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19008] = {
                      s2c = [[pbNpcFreind]],
                      c2s = proto_data19,
                      memo = [[友好界面]],
                      constStr = [[PLAYER_PROMOTE_FRIEND]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19009] = {
                      s2c = proto_data4,
                      c2s = proto_data19,
                      memo = [[友好]],
                      constStr = [[PLAYER_PROMOTE_FRIEND_TO_CHANGE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19010] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[晋升]],
                      constStr = [[PLAYER_PROMOTE_PROMOTE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19011] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[提前结束]],
                      constStr = [[PLAYER_PROMOTE_STOP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19012] = {
                      s2c = proto_data20,
                      c2s = proto_data21,
                      memo = [[晋封战斗考试准备]],
                      constStr = [[PLAYER_PROMOTE_FIGHT_PREPARE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19013] = {
                      s2c = proto_data4,
                      c2s = proto_data21,
                      memo = [[晋封战斗考试]],
                      constStr = [[PLAYER_PROMOTE_FIGHT_START]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19014] = {
                      s2c = proto_data4,
                      c2s = [[pbPromoteVsResult]],
                      memo = [[晋封战斗考试结果]],
                      constStr = [[PLAYER_PROMOTE_FIGHT_RESULT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19015] = {
                      s2c = proto_data21,
                      c2s = proto_data1,
                      memo = [[晋封战斗玩家返回]],
                      constStr = [[PLAYER_PROMOTE_FIGHT_PLAYER]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19020] = {
                      s2c = proto_data22,
                      c2s = proto_data1,
                      memo = [[巅峰宫斗]],
                      constStr = [[PLAYER_PROMOTE_ARENA]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19021] = {
                      s2c = proto_data22,
                      c2s = proto_data1,
                      memo = [[刷新列表]],
                      constStr = [[PLAYER_PROMOTE_ARENA_REFRESH]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19022] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[购买次数]],
                      constStr = [[PLAYER_PROMOTE_ARENA_BUY_TIMES]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19023] = {
                      s2c = proto_data23,
                      c2s = proto_data1,
                      memo = [[防守阵容]],
                      constStr = [[PLAYER_PROMOTE_ARENA_DEFENSE_POS]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19024] = {
                      s2c = proto_data4,
                      c2s = proto_data23,
                      memo = [[保存防守阵容]],
                      constStr = [[PLAYER_PROMOTE_ARENA_DEFENSE_SAVE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19025] = {
                      s2c = proto_data20,
                      c2s = proto_data21,
                      memo = [[准备挑战]],
                      constStr = [[PLAYER_PROMOTE_ARENA_PREPARE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19026] = {
                      s2c = proto_data24,
                      c2s = proto_data25,
                      memo = [[挑战结果]],
                      constStr = [[PLAYER_PROMOTE_ARENA_RESULT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19027] = {
                      s2c = [[pbEnemyList]],
                      c2s = proto_data1,
                      memo = [[仇人列表]],
                      constStr = [[PLAYER_PROMOTE_ARENA_ENEMY_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19028] = {
                      s2c = proto_data20,
                      c2s = proto_data21,
                      memo = [[准备复仇挑战]],
                      constStr = [[PLAYER_PROMOTE_ARENA_ENEMY_PREPARE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19029] = {
                      s2c = proto_data24,
                      c2s = proto_data25,
                      memo = [[复仇挑战结果]],
                      constStr = [[PLAYER_PROMOTE_ARENA_ENEMY_RESULT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19030] = {
                      s2c = proto_data4,
                      c2s = proto_data21,
                      memo = [[开始挑战]],
                      constStr = [[PLAYER_PROMOTE_ARENA_FIGHT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19031] = {
                      s2c = proto_data4,
                      c2s = proto_data21,
                      memo = [[复仇挑战]],
                      constStr = [[PLAYER_PROMOTE_ARENA_ENEMY_FIGHT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [19032] = {
                      s2c = [[pbRankRe]],
                      c2s = [[pbRankPram]],
                      memo = [[巅峰宫斗排行榜]],
                      constStr = [[PLAYER_PROMOTE_ARENA_RANK]],
                      arg = proto_data2,
                      back = 1,
                    },
              [20000] = {
                      s2c = proto_data26,
                      c2s = [[pbDraftType]],
                      memo = [[请求召唤]],
                      constStr = [[DRAFT_REQUEST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [20001] = {
                      s2c = proto_data26,
                      c2s = [[pbDraftChip]],
                      memo = [[碎片召唤]],
                      constStr = [[DRAFT_WITH_CHIP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [20002] = {
                      s2c = [[pbDraftGroup]],
                      c2s = proto_data1,
                      memo = [[请求特殊召唤列表]],
                      constStr = [[DRAFT_GROUP_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [20003] = {
                      s2c = [[pbDraftShow]],
                      c2s = proto_data1,
                      memo = [[请求图鉴列表]],
                      constStr = [[DRAFT_SHOW_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [21000] = {
                      s2c = [[pbRankData]],
                      c2s = [[pbRank]],
                      memo = [[排行榜]],
                      constStr = [[PLAYER_RANK]],
                      arg = proto_data2,
                      back = 1,
                    },
              [22000] = {
                      s2c = proto_data27,
                      c2s = proto_data1,
                      memo = [[竞技场]],
                      constStr = [[PLAYER_ARENA]],
                      arg = proto_data2,
                      back = 1,
                    },
              [22001] = {
                      s2c = proto_data27,
                      c2s = proto_data1,
                      memo = [[竞技场刷新列表]],
                      constStr = [[PLAYER_ARENA_REFRESH]],
                      arg = proto_data2,
                      back = 1,
                    },
              [22002] = {
                      s2c = proto_data28,
                      c2s = proto_data1,
                      memo = [[竞技场防守阵容]],
                      constStr = [[PLAYER_ARENA_DEFENSE_POS]],
                      arg = proto_data2,
                      back = 1,
                    },
              [22003] = {
                      s2c = proto_data4,
                      c2s = proto_data28,
                      memo = [[竞技场保存防守阵容]],
                      constStr = [[PLAYER_ARENA_DEFENSE_POS_SAVE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [22004] = {
                      s2c = proto_data20,
                      c2s = proto_data29,
                      memo = [[竞技场挑战准备]],
                      constStr = [[PLAYER_ARENA_PREPARE_FIGHT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [22005] = {
                      s2c = proto_data4,
                      c2s = proto_data29,
                      memo = [[竞技场挑战]],
                      constStr = [[PLAYER_ARENA_FIGHT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [22006] = {
                      s2c = proto_data30,
                      c2s = proto_data31,
                      memo = [[竞技场挑战结果]],
                      constStr = [[PLAYER_ARENA_FIGHT_RESULT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [22007] = {
                      s2c = [[pbArenaEnemyList]],
                      c2s = proto_data1,
                      memo = [[竞技场仇人列表]],
                      constStr = [[PLAYER_ARENA_ENEMY]],
                      arg = proto_data2,
                      back = 1,
                    },
              [22008] = {
                      s2c = proto_data20,
                      c2s = proto_data29,
                      memo = [[竞技场复仇挑战准备]],
                      constStr = [[PLAYER_ARENA_PREPARE_FIGHT_ENEMY]],
                      arg = proto_data2,
                      back = 1,
                    },
              [22009] = {
                      s2c = proto_data4,
                      c2s = proto_data29,
                      memo = [[竞技场复仇挑战]],
                      constStr = [[PLAYER_ARENA_FIGHT_ENEMY]],
                      arg = proto_data2,
                      back = 1,
                    },
              [22010] = {
                      s2c = proto_data30,
                      c2s = proto_data31,
                      memo = [[竞技场复仇挑战结果]],
                      constStr = [[PLAYER_ARENA_FIGHT_RESULT_ENEMY]],
                      arg = proto_data2,
                      back = 1,
                    },
              [22011] = {
                      s2c = [[pbArenaRankRe]],
                      c2s = [[pbArenaRankPram]],
                      memo = [[竞技场排行榜]],
                      constStr = [[PLAYER_ARENA_RANK]],
                      arg = proto_data2,
                      back = 1,
                    },
              [23000] = {
                      s2c = proto_data32,
                      c2s = [[pbShopGetList]],
                      memo = [[获取商城列表]],
                      constStr = [[SHOP_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [23001] = {
                      s2c = proto_data4,
                      c2s = [[pbShopBuy]],
                      memo = [[购买道具]],
                      constStr = [[SHOP_BUY]],
                      arg = proto_data2,
                      back = 1,
                    },
              [23002] = {
                      s2c = proto_data32,
                      c2s = proto_data1,
                      memo = [[更新道具]],
                      constStr = [[SHOP_UPDATE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [24000] = {
                      s2c = proto_data3,
                      c2s = proto_data1,
                      memo = [[获取觐见剧情]],
                      constStr = [[MONRACH_AUDIENCE_GET]],
                      arg = proto_data2,
                      back = 1,
                    },
              [24001] = {
                      s2c = [[pbMonarchAudience]],
                      c2s = proto_data3,
                      memo = [[更新觐见剧情]],
                      constStr = [[MONRACH_AUDIENCE_UPDATE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [24002] = {
                      s2c = [[pbMonarchAudienceResult]],
                      c2s = proto_data1,
                      memo = [[觐见结束获得奖励]],
                      constStr = [[MONRACH_AUDIENCE_RESULT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [24003] = {
                      s2c = proto_data33,
                      c2s = proto_data3,
                      memo = [[获取邀宠或承恩技能列表]],
                      constStr = [[MONRACH_GET_SKILL_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [24004] = {
                      s2c = proto_data33,
                      c2s = [[pbMonarchRun]],
                      memo = [[开始邀宠或承恩]],
                      constStr = [[MONRACH_START]],
                      arg = proto_data2,
                      back = 1,
                    },
              [25000] = {
                      s2c = proto_data34,
                      c2s = proto_data1,
                      memo = [[获取任务列表]],
                      constStr = [[TASK_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [25001] = {
                      s2c = proto_data34,
                      c2s = proto_data1,
                      memo = [[更新任务]],
                      constStr = [[TASK_UPDATE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [25002] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[删除任务]],
                      constStr = [[TASK_DEL]],
                      arg = proto_data2,
                      back = 1,
                    },
              [25003] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[领取任务奖励]],
                      constStr = [[TASK_GET_REWARD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26000] = {
                      s2c = proto_data35,
                      c2s = proto_data1,
                      memo = [[府邸信息]],
                      constStr = [[MANSION_INFO]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26001] = {
                      s2c = proto_data36,
                      c2s = proto_data36,
                      memo = [[府邸改名]],
                      constStr = [[MANSION_CHNAGE_NAME]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26002] = {
                      s2c = [[pbMansionVisitList]],
                      c2s = proto_data3,
                      memo = [[府邸串门]],
                      constStr = [[MANSION_VISIT_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26003] = {
                      s2c = [[pbMansionEvents]],
                      c2s = proto_data3,
                      memo = [[府邸事件]],
                      constStr = [[MANSION_EVENTS]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26004] = {
                      s2c = proto_data35,
                      c2s = proto_data3,
                      memo = [[府邸串门进行]],
                      constStr = [[MANSION_VISIT_START]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26005] = {
                      s2c = proto_data37,
                      c2s = proto_data1,
                      memo = [[府邸仆人列表]],
                      constStr = [[MANSION_SERVANT_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26006] = {
                      s2c = proto_data38,
                      c2s = proto_data38,
                      memo = [[府邸仆人改名]],
                      constStr = [[MANSION_SERVANT_CHANGE_NAME]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26007] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[府邸仆人打赏]],
                      constStr = [[MANSION_SERVANT_REWARD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26008] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[府邸仆人发放通宝]],
                      constStr = [[MANSION_SERVANT_REWARD_HOUSE_COIN]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26009] = {
                      s2c = proto_data37,
                      c2s = proto_data3,
                      memo = [[府邸仆人雇佣]],
                      constStr = [[MANSION_SERVANT_CALL]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26010] = {
                      s2c = [[pbMansionServant]],
                      c2s = proto_data1,
                      memo = [[府邸仆人信息更新]],
                      constStr = [[MANSION_SERVANT_UPDATE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26011] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[府邸仆人清洁度]],
                      constStr = [[MANSION_SERVANT_CLEANUP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26012] = {
                      s2c = proto_data35,
                      c2s = proto_data1,
                      memo = [[府邸信息更新]],
                      constStr = [[MANSION_UPDATE_INFO]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26013] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[府邸开垦土地]],
                      constStr = [[MANSION_OPEN_LAND]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26014] = {
                      s2c = [[pbMansionPlantingResult]],
                      c2s = [[pbMansionPlanting]],
                      memo = [[府邸种子操作]],
                      constStr = [[MANSION_SEED_OPERATION]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26015] = {
                      s2c = proto_data39,
                      c2s = proto_data1,
                      memo = [[府邸请求种子种植顺序]],
                      constStr = [[MANSION_SEED_ORDER_REQUEST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26016] = {
                      s2c = proto_data39,
                      c2s = proto_data39,
                      memo = [[府邸更新种子种植顺序]],
                      constStr = [[MANSION_SEED_ORDER_UPDATE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26017] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[府邸更新npc事件]],
                      constStr = [[MANSION_NPC_EVENT_UPDATE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26018] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[府邸npc事件领取奖励]],
                      constStr = [[MANSION_NPC_EVENT_REWARD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26019] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[府邸npc事件删除]],
                      constStr = [[MANSION_NPC_EVENT_DEL]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26020] = {
                      s2c = [[pbMansionOfflineInfo]],
                      c2s = proto_data1,
                      memo = [[府邸离线获得信息]],
                      constStr = [[MANSION_OFFLINE_GET_INFO]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26021] = {
                      s2c = proto_data1,
                      c2s = proto_data1,
                      memo = [[府邸关闭]],
                      constStr = [[MANSION_CLOSE]],
                      arg = proto_data2,
                      back = 0,
                    },
              [26030] = {
                      s2c = [[pbMansionFeastInfo]],
                      c2s = proto_data1,
                      memo = [[府邸打开宴会界面]],
                      constStr = [[MANSION_FEAST_OPEN_WINDOWS]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26031] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[府邸开启宴会]],
                      constStr = [[MANSION_FEAST_OPEN]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26032] = {
                      s2c = [[pbMansionFeastList]],
                      c2s = proto_data1,
                      memo = [[府邸获取宴会列表]],
                      constStr = [[MANSION_FESAT_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26033] = {
                      s2c = proto_data4,
                      c2s = [[pbMansionFeastAdd]],
                      memo = [[府邸赴宴]],
                      constStr = [[MANSION_FEAST_ADD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26034] = {
                      s2c = [[pbMansionFeastDetail]],
                      c2s = proto_data3,
                      memo = [[府邸宴会详细信息]],
                      constStr = [[MANSION_FEAST_DETAIL]],
                      arg = proto_data2,
                      back = 1,
                    },
              [26035] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[府邸宴会邀请]],
                      constStr = [[MANSION_FEAST_INVITE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [27000] = {
                      s2c = proto_data40,
                      c2s = proto_data3,
                      memo = [[府邸背包列表]],
                      constStr = [[MANSION_ITEM_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [27001] = {
                      s2c = proto_data40,
                      c2s = proto_data1,
                      memo = [[府邸背包更新]],
                      constStr = [[MANSION_ITEM_UPDATE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [27002] = {
                      s2c = proto_data4,
                      c2s = [[pbItemSell]],
                      memo = [[府邸背包出售]],
                      constStr = [[MANSION_ITEM_SELL]],
                      arg = proto_data2,
                      back = 1,
                    },
              [27003] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[府邸背包材料合成]],
                      constStr = [[MANSION_ITEM_COMPOSITION]],
                      arg = proto_data2,
                      back = 1,
                    },
              [28000] = {
                      s2c = [[pbEliteDungeonList]],
                      c2s = proto_data1,
                      memo = [[请求精英副本信息]],
                      constStr = [[ELITE_DUNGEON_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [28001] = {
                      s2c = proto_data41,
                      c2s = proto_data42,
                      memo = [[请求挑战精英副本]],
                      constStr = [[ELITE_DUNGEON_BATTLE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [28002] = {
                      s2c = proto_data41,
                      c2s = [[pbEliteDungeonOver]],
                      memo = [[挑战精英副本结果]],
                      constStr = [[ELITE_DUNGEON_BATTLE_RESULT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [28003] = {
                      s2c = proto_data4,
                      c2s = proto_data42,
                      memo = [[精英副本复活再战]],
                      constStr = [[ELITE_DUNGEON_REBORN]],
                      arg = proto_data2,
                      back = 1,
                    },
              [29000] = {
                      s2c = [[pbGuideInfo]],
                      c2s = proto_data1,
                      memo = [[获取完成引导的id信息]],
                      constStr = [[GUIDE_INFO]],
                      arg = proto_data2,
                      back = 1,
                    },
              [29001] = {
                      s2c = proto_data43,
                      c2s = proto_data43,
                      memo = [[通知完成引导]],
                      constStr = [[GUIDE_NOTICE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [30000] = {
                      s2c = proto_data44,
                      c2s = proto_data1,
                      memo = [[时装列表]],
                      constStr = [[PLAYER_FASHION_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [30001] = {
                      s2c = proto_data4,
                      c2s = [[pbWearFashionList]],
                      memo = [[保存]],
                      constStr = [[PLAYER_FASHION_SAVE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [30002] = {
                      s2c = proto_data4,
                      c2s = proto_data45,
                      memo = [[合成]],
                      constStr = [[PLAYER_FASHION_COMBINE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [30003] = {
                      s2c = proto_data4,
                      c2s = [[pbFashionStrength]],
                      memo = proto_data10,
                      constStr = [[PLAYER_FASHION_STRENGTH]],
                      arg = proto_data2,
                      back = 1,
                    },
              [30004] = {
                      s2c = proto_data4,
                      c2s = proto_data45,
                      memo = [[进阶]],
                      constStr = [[PLAYER_FASHION_PROMOTE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [30005] = {
                      s2c = proto_data4,
                      c2s = proto_data45,
                      memo = [[升星]],
                      constStr = [[PLAYER_FASHION_UPRGADE_STAR]],
                      arg = proto_data2,
                      back = 1,
                    },
              [30006] = {
                      s2c = proto_data4,
                      c2s = proto_data45,
                      memo = [[渲光]],
                      constStr = [[PLAYER_FASHION_UPGRADE_COLOR]],
                      arg = proto_data2,
                      back = 1,
                    },
              [30007] = {
                      s2c = proto_data4,
                      c2s = [[pbFashionSuit]],
                      memo = [[一键穿戴]],
                      constStr = [[PLAYER_FASHION_SAVE_ALL]],
                      arg = proto_data2,
                      back = 1,
                    },
              [30008] = {
                      s2c = proto_data4,
                      c2s = proto_data45,
                      memo = [[洗练]],
                      constStr = [[PLAYER_FASHION_WASH]],
                      arg = proto_data2,
                      back = 1,
                    },
              [30009] = {
                      s2c = proto_data4,
                      c2s = [[pbFashionSave]],
                      memo = [[洗练保存]],
                      constStr = [[PLAYER_FASHION_WASH_SAVE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [30010] = {
                      s2c = proto_data44,
                      c2s = proto_data1,
                      memo = [[刷新的时装列表]],
                      constStr = [[PLAYER_FASHION_REFRESH]],
                      arg = proto_data2,
                      back = 1,
                    },
              [31000] = {
                      s2c = [[pbWorshipInfo]],
                      c2s = proto_data1,
                      memo = [[获取祭拜先祖信息]],
                      constStr = [[WORSHIP_ANCESTOR_INFO]],
                      arg = proto_data2,
                      back = 1,
                    },
              [31001] = {
                      s2c = proto_data46,
                      c2s = proto_data1,
                      memo = [[请求祭拜先祖]],
                      constStr = [[WORSHIP_ANCESTOR]],
                      arg = proto_data2,
                      back = 1,
                    },
              [31002] = {
                      s2c = proto_data46,
                      c2s = proto_data1,
                      memo = [[太后请安]],
                      constStr = [[QUEEN_WISH]],
                      arg = proto_data2,
                      back = 1,
                    },
              [31003] = {
                      s2c = proto_data46,
                      c2s = proto_data1,
                      memo = [[太后献礼]],
                      constStr = [[QUEEN_GIFT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [31004] = {
                      s2c = [[pbQueenInfo]],
                      c2s = proto_data1,
                      memo = [[太后请安/献礼次数]],
                      constStr = [[QUEEN_INFO]],
                      arg = proto_data2,
                      back = 1,
                    },
              [32000] = {
                      s2c = proto_data47,
                      c2s = proto_data1,
                      memo = [[才艺背包]],
                      constStr = [[PLAYER_TALENT_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [32001] = {
                      s2c = proto_data47,
                      c2s = proto_data1,
                      memo = [[才艺背包刷新]],
                      constStr = [[PLAYER_TALENT_REFRSH]],
                      arg = proto_data2,
                      back = 1,
                    },
              [32002] = {
                      s2c = proto_data4,
                      c2s = [[pbTalentSell]],
                      memo = [[才艺出售]],
                      constStr = [[PLAYER_TALENT_SELL]],
                      arg = proto_data2,
                      back = 1,
                    },
              [32003] = {
                      s2c = proto_data48,
                      c2s = [[pbTalentModelWear]],
                      memo = [[才艺穿戴]],
                      constStr = [[PLAYER_TALENT_WEAR]],
                      arg = proto_data2,
                      back = 1,
                    },
              [32004] = {
                      s2c = proto_data4,
                      c2s = [[pbTalentModelRemove]],
                      memo = [[才艺卸下]],
                      constStr = [[PLAYER_TALENT_REMOVE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [32005] = {
                      s2c = proto_data48,
                      c2s = proto_data49,
                      memo = [[才艺强化]],
                      constStr = [[PLAYER_TALENT_STRENGTH]],
                      arg = proto_data2,
                      back = 1,
                    },
              [32006] = {
                      s2c = proto_data50,
                      c2s = [[pbTalentModelUp]],
                      memo = [[才艺研习]],
                      constStr = [[PLAYER_TALENT_UP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [32007] = {
                      s2c = proto_data50,
                      c2s = proto_data49,
                      memo = [[才艺精研]],
                      constStr = [[PLAYER_TALENT_WASH]],
                      arg = proto_data2,
                      back = 1,
                    },
              [32008] = {
                      s2c = proto_data48,
                      c2s = [[pbTalentModelSave]],
                      memo = [[才艺精研保存]],
                      constStr = [[PLAYER_TALENT_WASH_SAVE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33000] = {
                      s2c = proto_data51,
                      c2s = proto_data1,
                      memo = [[子女列表]],
                      constStr = [[PLAYER_CHILD_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33001] = {
                      s2c = proto_data51,
                      c2s = proto_data1,
                      memo = [[子女列表刷新]],
                      constStr = [[PLAYER_CHILD_REFRESH]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33002] = {
                      s2c = proto_data4,
                      c2s = [[pbChildModelFeed]],
                      memo = [[子女喂养]],
                      constStr = [[PLAYER_CHILD_FEED]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33003] = {
                      s2c = proto_data4,
                      c2s = [[pbChildModelUp]],
                      memo = [[子女进阶]],
                      constStr = [[PLAYER_CHILD_UP]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33004] = {
                      s2c = [[pbChildTest]],
                      c2s = proto_data52,
                      memo = [[子女考核]],
                      constStr = [[PLAYER_CHILD_TEST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33005] = {
                      s2c = proto_data4,
                      c2s = [[pbChildAnswer]],
                      memo = [[子女考核答题]],
                      constStr = [[PLAYER_CHILD_TEST_ANSWER]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33006] = {
                      s2c = proto_data4,
                      c2s = proto_data52,
                      memo = [[子女委任/召回]],
                      constStr = [[PLAYER_CHILD_USE]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33007] = {
                      s2c = [[pbChildPosList]],
                      c2s = proto_data1,
                      memo = [[子女上阵列表]],
                      constStr = [[PLAYER_CHILD_POS_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33008] = {
                      s2c = proto_data4,
                      c2s = [[pbChildPos]],
                      memo = [[子女上阵下阵]],
                      constStr = [[PLAYER_CHILD_POS]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33009] = {
                      s2c = [[pbChildEventList]],
                      c2s = proto_data1,
                      memo = [[子女事件列表]],
                      constStr = [[PLAYER_CHILD_EVENT_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33010] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[子女事件奖励领取]],
                      constStr = [[PLAYER_CHILD_EVENT_AWARD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33011] = {
                      s2c = [[pbChildTaskList]],
                      c2s = proto_data1,
                      memo = [[子女任务列表]],
                      constStr = [[PLAYER_CHILD_TASK_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33012] = {
                      s2c = proto_data4,
                      c2s = [[pbTaskAcceptModel]],
                      memo = [[子女任务接取]],
                      constStr = [[PLAYER_CHILD_TASK_ACCEPT]],
                      arg = proto_data2,
                      back = 1,
                    },
              [33013] = {
                      s2c = proto_data4,
                      c2s = [[pbTaskModel]],
                      memo = [[子女任务奖励领取]],
                      constStr = [[PLAYER_CHILD_TASK_AWARD]],
                      arg = proto_data2,
                      back = 1,
                    },
              [34001] = {
                      s2c = [[pbShopMysteryList]],
                      c2s = proto_data1,
                      memo = [[获取神秘商店列表]],
                      constStr = [[PLAYER_SHOPS_MYSTERY_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [34002] = {
                      s2c = proto_data4,
                      c2s = proto_data3,
                      memo = [[购买神秘商店道具]],
                      constStr = [[PLAYER_SHOPS_MYSTERY_BUY]],
                      arg = proto_data2,
                      back = 1,
                    },
              [34003] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[元宝刷新神秘商店]],
                      constStr = [[PLAYER_SHOPS_MYSTERY_REFRESH]],
                      arg = proto_data2,
                      back = 1,
                    },
              [35001] = {
                      s2c = proto_data7,
                      c2s = proto_data1,
                      memo = [[请求每日领取体力]],
                      constStr = [[PLAYER_EVERY_DAY_SP_LIST]],
                      arg = proto_data2,
                      back = 1,
                    },
              [35002] = {
                      s2c = proto_data4,
                      c2s = proto_data1,
                      memo = [[每日领取体力]],
                      constStr = [[PLAYER_EVERY_DAY_SP_GET]],
                      arg = proto_data2,
                      back = 1,
                    },
              [35003] = {
                      s2c = [[pbTimeSpEnergy]],
                      c2s = proto_data1,
                      memo = [[定时回复体力，精力]],
                      constStr = [[PLAYER_EVERYDAY_SP_ENERGY_TIME]],
                      arg = proto_data2,
                      back = 1,
                    },
            }
return ConfigSysproto_data;