local monarch1=[[]]
local monarch2=[[是的]]
local monarch3=[[邀请皇上共进晚膳]]

local ConfigSysmonarch={
              [1] = {
                      monarch_id = 1,
                      story_type = 1,
                      story = 10001,
                      branch = {
                              2,
                              3,
                            },
                      mood = {
                              40,
                              60,
                            },
                      des = [[今年黄河洪水泛滥，沿岸百姓苦不堪言。皇上前头谴了2次人去，都未能很好的治水安民。今日前朝又在讨论再派人去赈灾的问题，皇上为了人选之事忧心不已，下了朝后就在养心殿思虑，连午膳都未怎么用就退了出来。]],
                      need_goods = {
                              {
                                      goods_id = 1010201,
                                      goods_num = 1,
                                      goods_rate = 0,
                                    },
                              {
                                      goods_id = 1010202,
                                      goods_num = 1,
                                      goods_rate = 0,
                                    },
                            },
                      get_goods = {
                              {
                                      goods_id = 1010401,
                                      goods_num = 1,
                                      goods_rate = 1000,
                                    },
                              {
                                      goods_id = 1010402,
                                      goods_num = 1,
                                      goods_rate = 100,
                                    },
                              {
                                      goods_id = 1010408,
                                      goods_num = 1,
                                      goods_rate = 1000,
                                    },
                              {
                                      goods_id = 1010701,
                                      goods_num = 1,
                                      goods_rate = 500,
                                    },
                              {
                                      goods_id = 1000002,
                                      goods_num = 1000,
                                      goods_rate = 500,
                                    },
                              {
                                      goods_id = 1000003,
                                      goods_num = 10,
                                      goods_rate = 100,
                                    },
                            },
                    },
              [2] = {
                      monarch_id = 2,
                      story_type = 4,
                      story = 0,
                      branch = {
                              4,
                              5,
                            },
                      mood = nil,
                      des = [[直奔主题]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [3] = {
                      monarch_id = 3,
                      story_type = 4,
                      story = 0,
                      branch = {
                              6,
                            },
                      mood = nil,
                      des = [[太后派我来的]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [4] = {
                      monarch_id = 4,
                      story_type = 2,
                      story = 10002,
                      branch = {
                              8,
                              9,
                            },
                      mood = {
                              0,
                              50,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [5] = {
                      monarch_id = 5,
                      story_type = 3,
                      story = 10003,
                      branch = nil,
                      mood = {
                              51,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [6] = {
                      monarch_id = 6,
                      story_type = 2,
                      story = 10004,
                      branch = {
                              7,
                              11,
                            },
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [7] = {
                      monarch_id = 7,
                      story_type = 4,
                      story = 0,
                      branch = {
                              12,
                            },
                      mood = nil,
                      des = [[拦下小桂子才知道的]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [8] = {
                      monarch_id = 8,
                      story_type = 4,
                      story = 0,
                      branch = {
                              13,
                            },
                      mood = nil,
                      des = [[推荐治水能臣高斌]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [9] = {
                      monarch_id = 9,
                      story_type = 4,
                      story = 0,
                      branch = {
                              14,
                              15,
                            },
                      mood = nil,
                      des = [[皇上辛劳，天佑大清]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [10] = {
                      monarch_id = 10,
                      story_type = 3,
                      story = 19999,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [11] = {
                      monarch_id = 11,
                      story_type = 4,
                      story = 0,
                      branch = {
                              43,
                            },
                      mood = nil,
                      des = monarch2,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [12] = {
                      monarch_id = 12,
                      story_type = 3,
                      story = 19998,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [13] = {
                      monarch_id = 13,
                      story_type = 3,
                      story = 10005,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [14] = {
                      monarch_id = 14,
                      story_type = 2,
                      story = 10006,
                      branch = {
                              16,
                              17,
                            },
                      mood = {
                              0,
                              50,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [15] = {
                      monarch_id = 15,
                      story_type = 2,
                      story = 10013,
                      branch = {
                              28,
                              29,
                              30,
                            },
                      mood = {
                              51,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [16] = {
                      monarch_id = 16,
                      story_type = 4,
                      story = 0,
                      branch = {
                              18,
                            },
                      mood = nil,
                      des = monarch3,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [17] = {
                      monarch_id = 17,
                      story_type = 4,
                      story = 0,
                      branch = {
                              19,
                            },
                      mood = nil,
                      des = [[先行告退]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [18] = {
                      monarch_id = 18,
                      story_type = 3,
                      story = 10007,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [19] = {
                      monarch_id = 19,
                      story_type = 2,
                      story = 10008,
                      branch = {
                              20,
                              21,
                            },
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [20] = {
                      monarch_id = 20,
                      story_type = 4,
                      story = 0,
                      branch = {
                              22,
                            },
                      mood = nil,
                      des = [[日日都去，臣妾亦随侍]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [21] = {
                      monarch_id = 21,
                      story_type = 4,
                      story = 0,
                      branch = {
                              23,
                            },
                      mood = nil,
                      des = [[日日都去]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [22] = {
                      monarch_id = 22,
                      story_type = 3,
                      story = 10009,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [23] = {
                      monarch_id = 23,
                      story_type = 2,
                      story = 10010,
                      branch = {
                              24,
                              25,
                            },
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [24] = {
                      monarch_id = 24,
                      story_type = 4,
                      story = 0,
                      branch = {
                              26,
                            },
                      mood = nil,
                      des = monarch2,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [25] = {
                      monarch_id = 25,
                      story_type = 4,
                      story = 0,
                      branch = {
                              27,
                            },
                      mood = nil,
                      des = [[臣妾无能，后知后觉]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [26] = {
                      monarch_id = 26,
                      story_type = 3,
                      story = 10011,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [27] = {
                      monarch_id = 27,
                      story_type = 3,
                      story = 10012,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [28] = {
                      monarch_id = 28,
                      story_type = 4,
                      story = 0,
                      branch = {
                              31,
                            },
                      mood = nil,
                      des = [[臣妾无能，只能随侍太后]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [29] = {
                      monarch_id = 29,
                      story_type = 4,
                      story = 0,
                      branch = {
                              32,
                            },
                      mood = nil,
                      des = [[皇上总不来看臣妾]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [30] = {
                      monarch_id = 30,
                      story_type = 4,
                      story = 0,
                      branch = {
                              33,
                              34,
                            },
                      mood = nil,
                      des = [[皇上国事繁忙，但慧贵妃总想着皇上]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [31] = {
                      monarch_id = 31,
                      story_type = 2,
                      story = 10014,
                      branch = {
                              20,
                              21,
                            },
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [32] = {
                      monarch_id = 32,
                      story_type = 3,
                      story = 10015,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [33] = {
                      monarch_id = 33,
                      story_type = 2,
                      story = 10016,
                      branch = {
                              35,
                              36,
                            },
                      mood = {
                              0,
                              50,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [34] = {
                      monarch_id = 34,
                      story_type = 2,
                      story = 10019,
                      branch = {
                              39,
                              40,
                            },
                      mood = {
                              51,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [35] = {
                      monarch_id = 35,
                      story_type = 4,
                      story = 0,
                      branch = {
                              37,
                            },
                      mood = nil,
                      des = [[想必是家学渊源]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [36] = {
                      monarch_id = 36,
                      story_type = 4,
                      story = 0,
                      branch = {
                              38,
                            },
                      mood = nil,
                      des = [[估计是母家的人送的法子]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [37] = {
                      monarch_id = 37,
                      story_type = 3,
                      story = 10017,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [38] = {
                      monarch_id = 38,
                      story_type = 3,
                      story = 10018,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [39] = {
                      monarch_id = 39,
                      story_type = 4,
                      story = 0,
                      branch = {
                              41,
                            },
                      mood = nil,
                      des = [[这才更显心中有皇上]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [40] = {
                      monarch_id = 40,
                      story_type = 4,
                      story = 0,
                      branch = {
                              42,
                            },
                      mood = nil,
                      des = [[这才是做妃子的本分]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [41] = {
                      monarch_id = 41,
                      story_type = 3,
                      story = 10021,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [42] = {
                      monarch_id = 42,
                      story_type = 3,
                      story = 10020,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [43] = {
                      monarch_id = 43,
                      story_type = 2,
                      story = 10023,
                      branch = {
                              44,
                              45,
                            },
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [44] = {
                      monarch_id = 44,
                      story_type = 4,
                      story = 0,
                      branch = {
                              46,
                            },
                      mood = nil,
                      des = [[为小桂子求情]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [45] = {
                      monarch_id = 45,
                      story_type = 4,
                      story = 0,
                      branch = {
                              47,
                            },
                      mood = nil,
                      des = [[皇上龙体要紧，切勿动怒]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [46] = {
                      monarch_id = 46,
                      story_type = 2,
                      story = 10025,
                      branch = {
                              48,
                              49,
                            },
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [47] = {
                      monarch_id = 47,
                      story_type = 3,
                      story = 10024,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [48] = {
                      monarch_id = 48,
                      story_type = 4,
                      story = 0,
                      branch = {
                              50,
                            },
                      mood = nil,
                      des = [[臣妾没有皇上说的那么好]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [49] = {
                      monarch_id = 49,
                      story_type = 4,
                      story = 0,
                      branch = {
                              51,
                              52,
                            },
                      mood = nil,
                      des = [[既知太后的好，就要听太后的话]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [50] = {
                      monarch_id = 50,
                      story_type = 3,
                      story = 10026,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [51] = {
                      monarch_id = 51,
                      story_type = 2,
                      story = 10027,
                      branch = {
                              53,
                              54,
                            },
                      mood = {
                              70,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [52] = {
                      monarch_id = 52,
                      story_type = 2,
                      story = 10038,
                      branch = {
                              55,
                              56,
                            },
                      mood = {
                              0,
                              69,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [53] = {
                      monarch_id = 53,
                      story_type = 4,
                      story = 0,
                      branch = {
                              57,
                            },
                      mood = nil,
                      des = [[去御花园散心]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [54] = {
                      monarch_id = 54,
                      story_type = 4,
                      story = 0,
                      branch = {
                              58,
                            },
                      mood = nil,
                      des = [[推举福康安]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [55] = {
                      monarch_id = 55,
                      story_type = 4,
                      story = 0,
                      branch = {
                              63,
                            },
                      mood = nil,
                      des = monarch3,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [56] = {
                      monarch_id = 56,
                      story_type = 4,
                      story = 0,
                      branch = {
                              64,
                            },
                      mood = nil,
                      des = [[这是做臣妾的本分]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [57] = {
                      monarch_id = 57,
                      story_type = 3,
                      story = 10028,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [58] = {
                      monarch_id = 58,
                      story_type = 2,
                      story = 10029,
                      branch = {
                              59,
                              60,
                            },
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [59] = {
                      monarch_id = 59,
                      story_type = 4,
                      story = 0,
                      branch = {
                              61,
                            },
                      mood = nil,
                      des = [[臣妾不该妄议朝政]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [60] = {
                      monarch_id = 60,
                      story_type = 4,
                      story = 0,
                      branch = {
                              62,
                            },
                      mood = nil,
                      des = [[执意推举福康安]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [61] = {
                      monarch_id = 61,
                      story_type = 3,
                      story = 10030,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [62] = {
                      monarch_id = 62,
                      story_type = 3,
                      story = 10031,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [63] = {
                      monarch_id = 63,
                      story_type = 3,
                      story = 10037,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [64] = {
                      monarch_id = 64,
                      story_type = 2,
                      story = 10033,
                      branch = {
                              65,
                              66,
                            },
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [65] = {
                      monarch_id = 65,
                      story_type = 4,
                      story = 0,
                      branch = {
                              67,
                            },
                      mood = nil,
                      des = [[率土之滨，莫非王臣]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [66] = {
                      monarch_id = 66,
                      story_type = 4,
                      story = 0,
                      branch = {
                              68,
                            },
                      mood = nil,
                      des = [[不敢妄言]],
                      need_goods = nil,
                      get_goods = nil,
                    },
              [67] = {
                      monarch_id = 67,
                      story_type = 3,
                      story = 10034,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [68] = {
                      monarch_id = 68,
                      story_type = 3,
                      story = 10035,
                      branch = nil,
                      mood = {
                              0,
                              100,
                            },
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
              [69] = {
                      monarch_id = 69,
                      story_type = 0,
                      story = 0,
                      branch = nil,
                      mood = nil,
                      des = monarch1,
                      need_goods = nil,
                      get_goods = nil,
                    },
            }
return ConfigSysmonarch;