local BattleEventEnum = {
	COMBAT_START = "COMBAT_START",
	COMBAT_STOP = "COMBAT_STOP",
	COMBAT_CLEAR_STAGE = "COMBAT_CLEAR_STAGE",

	ON_PLAYER_SET_SELECTED_TARGET = "ON_PLAYER_SET_SELECTED_TARGET",
	ON_PLAYER_SET_AUTO_COMBAT = "ON_PLAYER_SET_AUTO_COMBAT",
	ON_PLAYER_SELECT_SKILL = "ON_PLAYER_SELECT_SKILL",
	ON_PLAYER_PICK_ACTOR = "ON_PLAYER_PICK_ACTOR",

	ON_AI_DOROUND = "ON_AI_DOROUND",
	ON_AI_SELECT_SKILL = "ON_AI_SELECT_SKILL",
	ON_AI_SELECT_TARGET = "ON_AI_SELECT_TARGET",

	ON_ACTOR_DEAD = "ON_ACTOR_DEAD",
	ON_ACTOR_RELIVE = "ON_ACTOR_RELIVE",
	ON_ACTOR_SELECT_SKILL = "ON_ACTOR_SELECT_SKILL",
	ON_ACTOR_USE_SKILL = "ON_ACTOR_USE_SKILL",
	ON_ACTOR_CHECK_COMBAT_KILL = "ON_ACTOR_CHECK_COMBAT_KILL",

	BEFORE_ACTOR_ATTACK = "BEFORE_ACTOR_ATTACK",
	BEFORE_ACTOR_TREAT = "BEFORE_ACTOR_TREAT",
	BEFORE_ACTOR_POISON = "BEFORE_ACTOR_POISON",
	BEFORE_ACTOR_RECOVER_ATTACK_BAR = "BEFORE_ACTOR_RECOVER_ATTACK_BAR",

	AFTER_ACTOR_ATTACK = "AFTER_ACTOR_ATTACK",
	AFTER_ACTOR_TREAT = "AFTER_ACTOR_TREAT",
	
	ON_FINISH_ROUND = "ON_FINISH_ROUND",
	ON_START_ROUND = "ON_START_ROUND",

}

return BattleEventEnum;