local EventEnum = {
	MEMORY_DISPOSE = "MEMORY_DISPOSE",

	SET_FULL_COST_VIEW_VISIBLE = "SET_FULL_COST_VIEW_VISIBLE",
	
	--mainScene
	ON_ENTER_MAINSCENE = "ON_ENTER_MAINSCENE",
	ON_CHANGE_MAINSCENE_POS = "ON_CHANGE_MAINSCENE_POS",

	--sceneLoading
	SCENE_LOADING_SHOW = "SCENE_LOADING_SHOW",
	SCENE_LOADING_HIDE = "SCENE_LOADING_HIDE",
	SCENE_START_PRELOAD = "SCENE_START_PRELOAD",

	--login
	LOGIN_SUCCESS = "LOGIN_SUCCESS",
	LOGIN_SELECT_SERVER = "LOGIN_SELECT_SERVER",
	LOGIN_NEW_DAY = "LOGIN_NEW_DAY";

	--story
	STORY_PLAY = "STORY_PLAY",

	--combat
	BEFORE_HURT = "BEFORE_HURT",
	AFTER_HURT = "AFTER_HURT",
	COMBAT_KILL = "COMBAT_KILL",
	ON_SELECT_TARGET = "ON_SELECT_TARGET",
	ON_SELECT_SKILL = "ON_SELECT_SKILL",
	ON_PICK_ACTOR = "ON_PICK_ACTOR",
	ON_ACTOR_DEAD = "ON_ACTOR_DEAD",
	ON_ACTOR_RELIVE = "ON_ACTOR_RELIVE",
	ON_ACTOR_BORN = "ON_ACTOR_BORN",
	ON_COMBAT_PREPARE = "ON_COMBAT_PREPARE",
	ON_COMBAT_START = "ON_COMBAT_START",
	ON_COMBAT_OVER = "ON_COMBAT_OVER",
	ON_START_ROUND = "ON_START_ROUND",
	ON_FINISH_ROUND = "ON_FINISH_ROUND",
	ON_ACTOR_SELECT_SKILL = "ON_ACTOR_SELECT_SKILL",
	ON_ACTOR_USE_SKILL = "ON_ACTOR_USE_SKILL",
	ON_AUTO_COMBAT = "ON_AUTO_COMBAT",
	ON_SKILL_BLACK = "ON_SKILL_BLACK",
	SET_COMBAT_RESULT = "SET_COMBAT_RESULT",
	ON_MONSTER_WAVE_DIE = "ON_MONSTER_WAVE_DIE",
	ON_SHOW_NEXT_COMBAT_SCENE = "ON_SHOW_NEXT_BATTLE_SCENE",
	BEFORE_BEGIN_COMBAT = "ON_BEFORE_BEGIN_COMBAT",
	ON_CREATE_COMBAT = "ON_CREATE_COMBAT",
	ON_DESTROY_COMBAT = "ON_DESTROY_COMBAT",
	ON_SHOW_WIN_POSE = "ON_SHOW_WIN_POSE",
	ON_AI_DOROUND = "ON_AI_DOROUND",
	ON_PLAYER_SELECT_SKILL = "ON_PLAYER_SELECT_SKILL",
	ON_WAVE_ALL_DIE = "ON_WAVE_ALL_DIE",
	ON_CLEAR_ROUND = "ON_CLEAR_ROUND",
	--battle
	BATTLE_ADD_ACTOR = "BATTLE_ADD_ACTOR",
	BATTLE_REMOVE_ACTOR = "BATTLE_REMOVE_ACTOR",
	BATTLE_COMBAT_START = "BATTLE_COMBAT_START",
	BATTLE_COMBAT_STOP = "BATTLE_COMBAT_STOP",
	BATTLE_CLEAR_STAGE = "BATTLE_CLEAR_STAGE",
	BATTLE_SET_SELECTED_TARGET = "BATTLE_SET_SELECTED_TARGET",
	
	SHOW_SKILL_NAME = "SHOW_SKILL_NAME",
	SHAKE_CAMERA = "SHAKE_CAMERA",
	TOGGLE_SCREEN_BLACK = "TOGGLE_SCREEN_BLACK",
	
	--role
	ON_PLAYER_UPDATE_STRENGTH = "ON_PLAYER_UPDATE_STRENGTH",
	ON_PLAYER_UPDATE_ENERGY = "ON_PLAYER_UPDATE_ENERGY",
	ON_PLAYER_UPDATE_COIN = "ON_PLAYER_UPDATE_COIN",
	ON_PLAYER_UPDATE_GOLD = "ON_PLAYER_UPDATE_GOLD",
	ON_PLAYER_UPDATE_OFFICE = "ON_PLAYER_UPDATE_OFFICE",
	ON_PLAYER_UPDATE_LEVEL = "ON_PLAYER_UPDATE_LEVEL",
	ON_PLAYER_UPDATE_EXP = "ON_PLAYER_UPDATE_EXP",
	ON_PLAYER_UPDATE_YUELI = "ON_PLAYER_UPDATE_YUELI",
	ON_PLAYER_UPDATE_ARENA_COIN = "ON_PLAYER_UPDATE_ARENA_COIN",
	ON_PLAYER_UPDATE_DRESS_COIN = "ON_PLAYER_UPDATE_DRESS_COIN",
	ON_PLAYER_UPDATE_DEVOTE_COIN = "ON_PLAYER_UPDATE_DEVOTE_COIN",
	ON_PLAYER_UPDATE_HOUSE_COIN = "ON_PLAYER_UPDATE_HOUSE_COIN",
	ON_PLAYER_UPDATE_WISDOM_COIN = "ON_PLAYER_UPDATE_WISDOM_COIN",
	ON_PLAYER_UPDATE_BOOM_COIN = "ON_PLAYER_UPDATE_BOOM_COIN",

	--bag
	ON_SELECT_BAG_GOODS = "ON_SELECT_BAG_GOODS",
	ON_GET_GOODS_PATH = "ON_GET_GOODS_PATH",
	ON_SELL_GOODS_RESULT = "ON_SELL_GOODS_RESULT",
	ON_BAG_GOODS_REFRESH = "ON_BAG_GOODS_REFRESH",
	ON_GOODS_UPDATE = "ON_GOODS_UPDATE",
	ON_CANCEL_BAG_BATCH = "ON_CANCEL_BAG_BATCH",
	ON_CHANGE_BAG_SELECT_TO_BATCH = "ON_CHANGE_BAG_SELECT_TO_BATCH",
	ON_BAG_SHOW_INFO = "ON_BAG_SHOW_INFO",

	--sound
	PLAY_SOUND = "PLAY_SOUND",
	STOP_SOUND = "STOP_SOUND",
	SET_MUSIC = "SET_MUSIC",
	SET_SOUND_EFFECT = "SET_SOUND_EFFECT",

	--guide
	ON_RUN_NEXT_STEP = "ON_RUN_NEXT_STEP",
	ON_HIDE_GUIDE_DESC = "ON_HIDE_GUIDE_DESC",

	--campdungeon
	ON_GET_CAMPDUNGEON_DATA = "ON_GET_CAMPDUNGEON_DATA",
	ON_SELECT_CAMPBOSS_ITEM = "ON_SELECT_CAMPBOSS_ITEM",
	ON_CAMP_DUNGEON_PASS_LEVEL = "ON_CAMP_DUNGEON_PASS_LEVEL",
	ON_OPEN_CAMP_FORMATION = "ON_OPEN_CAMP_FORMATION",
	ON_SELECT_CAMP_TOGGLE = "ON_SELECT_CAMP_TOGGLE",
	ON_CAMP_DUNGEON_RESET_FOLLOWERLIST_SIZE = "ON_CAMP_DUNGEON_RESET_FOLLOWERLIST_SIZE",

	--endlessdungeon
	ON_GET_ENDLESS_DATA = "ON_GET_ENDLESS_DATA",
	ON_SHOW_MEIRENXINJI_ROTATION = "ON_SHOW_MEIRENXINJI_ROTATION",

	--king
	ON_GET_MONARCH_DATA = "ON_GET_MONARCH_DATA",
	ON_MONARCH_BEGIN = "ON_MONARCH_BEGIN",
	ON_RUN_NEXT_STORY = "ON_RUN_NEXT_STORY",
	ON_SKILL_UPDATE = "ON_SKILL_UPDATE",
	ON_SELECT_KING_SKILL = "ON_SELECT_KING_SKILL",

	--task
	ON_GET_TASK_LIST = "ON_GET_TASK_LIST",
	ON_SURPRISE_TASK_COMPLETE = "ON_SURPRISE_TASK_COMPLETE",
	ON_SURPRISE_TASK_GET = "ON_SURPRISE_TASK_GET",
	ON_SURPRISE_TASK_UPDATE = "ON_SURPRISE_TASK_UPDATE",
	ON_TASK_UPDATE = "ON_TASK_UPDATE",

	--draft
	ON_SELECT_DRAFT = "ON_SELECT_DRAFT",
	ON_GET_SPECIAL_GROUP = "ON_GET_SPECIAL_GROUP",
	ON_DRAFT_REMOVE_ITEM = "ON_DRAFT_REMOVE_ITEM",
	ON_DRAFT_SHOW_FOLLOWER = "ON_DRAFT_SHOW_FOLLOWER",

	--talent
	ON_WEAR_TALENT = "ON_WEAR_TALENT",
	ON_REMOVE_TALENT = "ON_REMOVE_TALENT",
	ON_UP_TALENT_SUCCEED = "ON_UP_TALENT_SUCCEED",
	ON_UP_TALENT_FAILED = "ON_UP_TALENT_FAILED",
	ON_SELECT_TYPE_TALENT = "ON_SELECT_TYPE_TALENT",
	ON_SELECT_EQUIP_ITEM = "ON_SELECT_EQUIP_ITEM",
	ON_SELECT_STUDY_ITEM = "ON_SELECT_STUDY_ITEM",
	ON_CLICK_STRENGTH_TALENT = "ON_CLICK_STRENGTH_TALENT",
	ON_SELECT_TALENT_ITEM = "ON_SELECT_TALENT_ITEM",
	ON_SELECT_SELL_ITEM = "ON_SELECT_SELL_ITEM",
	ON_RECV_STUDY_TALENT = "ON_RECV_STUDY_TALENT",
	ON_RECV_TALENT_UPDATE = "ON_RECV_TALENT_UPDATE",
	ON_RECV_WASH_TALENT = "ON_RECV_WASH_TALENT",
	ON_RECV_WASH_TALENT_SAVE = "ON_RECV_WASH_TALENT_SAVE",
	ON_RECV_WASH_TALENT_GIVE = "ON_RECV_WASH_TALENT_GIVE",

	--follower
	ON_FOLLOWER_LOCK = "ON_FOLLOWER_LOCK",
	ON_FOLLOWER_BREAK = "ON_FOLLOWER_BREAK",
	ON_SELECT_FOLLOWER = "ON_SELECT_FOLLOWER",
	ON_FOLLOWER_DELETE = "ON_FOLLOWER_DELETE",
	ON_FOLLOWER_UP_EXP = "ON_FOLLOWER_UP_EXP",
	ON_RECV_COMMENT_ADD = 'ON_RECV_COMMENT_ADD',
	ON_FOLLOWER_SKILL_UP = "ON_FOLLOWER_SKILL_UP",
	ON_RECV_COMMENT_LIST = "ON_RECV_COMMENT_LIST",
	ON_FOLLOWER_BIOGRAPHY = "ON_FOLLOWER_BIOGRAPHY",
	ON_CLICK_COMMENT_ITEM = "ON_CLICK_COMMENT_ITEM",
	ON_RECV_LOOK_FOLLOWER = "ON_RECV_LOOK_FOLLOWER",
	ON_RECV_COMMENT_PRAISE = "ON_RECV_COMMENT_PRAISE",
	ON_LEAD_COMBAT_UPDATE = "ON_LEAD_COMBAT_UPDATE",
	ON_FOLLOWER_OFFICE_UP = "ON_FOLLOWER_OFFICE_UP",
	ON_FOLLOWER_ALTER_NAME = "ON_FOLLOWER_ALTER_NAME",
	ON_FOLLOWER_MODEL_CHANE = "ON_FOLLOWER_MODEL_CHANE",
	ON_RECV_IN_CAMP_FOLLOWER = "ON_RECV_IN_CAMP_FOLLOWER",
	ON_SELECT_BREAK_FOLLOWER = "ON_SELECT_BREAK_FOLLOWER",
	ON_CANCEL_BREAK_FOLLOWER = "ON_CANCEL_BREAK_FOLLOWER",
	ON_SELECT_BATTLE_FOLLOWER = 'ON_SELECT_BATTLE_FOLLOWER',
	ON_SELECT_OTHERS_FOLLOWER = "ON_SELECT_OTHERS_FOLLOWER",
	ON_SELECT_UP_SKILL_COST = "ON_SELECT_UP_SKILL_COST",
	ON_REFRESH_FOLLOWER_SELECT = "ON_REFRESH_FOLLOWER_SELECT",
	ON_BATTLE_ARRAY_HIDE_VIEW = "ON_BATTLE_ARRAY_HIDE_VIEW",
	ON_BATTLE_ARRAY_SHOW_VIEW = "ON_BATTLE_ARRAY_SHOW_VIEW",

	--lead
	ON_LEAD_TRAIN = "ON_LEAD_TRAIN",
	ON_LEAD_TRAIN_OP = 'ON_LEAD_TRAIN_OP',
	ON_LEAD_SKILL_UP = "ON_LEAD_SKILL_UP",
	ON_LEAD_SKILL_CHANGE = "ON_LEAD_SKILL_CHANGE",

	--friend
	ON_GET_ENERGY = "ON_GET_ENERGY",
	ON_GIVE_ENERGY = "ON_GIVE_ENERGY",
	ON_CHANGE_FRIENDLIST_STATE = "ON_CHANGE_FRIENDLIST_STATE",
	ON_CALL_CHANGE_FRIENDLIST_STATE = "ON_CALL_CHANGE_FRIENDLIST_STATE",
	ON_RESET_ADD_TIPS = "ON_RESET_ADD_TIPS",
	ON_GET_PLAYER_DETAIL = "ON_GET_PLAYER_DETAIL",
	ON_OPEN_FRIEND_DELETE_POPUP = "ON_OPEN_FRIEND_DELETE_POPUP",
	ON_OPEN_BLACKLIST_DELETE_POPUP = "ON_OPEN_BLACKLIST_DELETE_POPUP",
	ON_OPEN_ENEMY_DELETE_POPUP = "ON_OPEN_ENEMY_DELETE_POPUP",
	ON_FRIENDADD_DELETE_FIND = "ON_FRIENDADD_DELETE_FIND",
	ON_FRIENDADD_DELETE_APPLY = "ON_FRIENDADD_DELETE_APPLY",
	ON_FRIENDADD_ADD = "ON_FRIENDADD_ADD",
	ON_FRIENDADD_AGREE = "ON_FRIENDADD_AGREE",
	ON_RECIVE_FRIEND_LIST = "ON_RECIVE_FRIEND_LIST",
	ON_RECIVE_GET_ENERGY = "ON_RECIVE_GET_ENERGY",
	ON_RECIVE_SEND_ENERGY = "ON_RECIVE_SEND_ENERGY",
	ON_RECIVE_DELETE_FRIEND = "ON_RECIVE_DELETE_FRIEND",
	ON_RECIVE_SEARCH_LIST = "ON_RECIVE_SEARCH_LIST",
	ON_RECIVE_ADD_FRIEND = "ON_RECIVE_ADD_FRIEND",
	ON_RECIVE_REQUEST_LIST = "ON_RECIVE_REQUEST_LIST",
	ON_RECIVE_REQUEST_HANDLE = "ON_RECIVE_REQUEST_HANDLE",
	ON_RECIVE_BLACKLIST = "ON_RECIVE_BLACKLIST",
	ON_RECIVE_DELETE_BLACKLIST = "ON_RECIVE_DELETE_BLACKLIST",
	ON_RECIVE_ENEMYLIST = "ON_RECIVE_ENEMYLIST",
	ON_RECIVE_DELETE_ENEMYLIST = "ON_RECIVE_DELETE_ENEMYLIST",
	ON_FRIEND_CHANGE_FLAG = "ON_FRIEND_CHANGE_FLAG",
	ON_CHECK_PLAYER = "ON_CHECK_PLAYER",
	ON_RECIVE_RECOMMEND_LIST = "ON_RECIVE_RECOMMEND_LIST",
	ON_SELECT_FRIEND = "ON_SELECT_FRIEND",
	ON_SELECT_FRIEND_ADD = "ON_SELECT_FRIEND_ADD",
	ON_SELECT_FRIEND_BLACKLIST = "ON_SELECT_FRIEND_BLACKLIST",
	ON_SET_FRIEND_EMPTY = "ON_SET_FRIEND_EMPTY",
	ON_SET_PLAYER_MODEL_STATE = "ON_SET_PLAYER_MODEL_STATE",

	--fashion
	ON_UPDATE_FASHION_INFO = "ON_UPDATE_FASHION_INFO",--更新时装信息
	ON_UPDATE_EQUIPED_FASHIONS = "ON_UPDATE_EQUIPED_FASHIONS",--更新已穿戴列表
	ON_REPLACE_SUIT = "ON_REPLACE_SUIT",--换套装
	ON_REPLACE_FASHION = "ON_REPLACE_FASHION",--换部件
	ON_CLOSE_FASHION_INFO = "ON_CLOSE_FASHION_INFO",
	ON_UPDATE_FASHION_RESULT = "ON_UPDATE_FASHION_RESULT",--进阶，强化等等返回结果
	ON_SELECT_BFASHION_ITEM = "ON_SELECT_BFASHION_ITEM",--选中主角界面背包的时装
	ON_CLICK_BFASHION_ITEM = "ON_CLICK_BFASHION_ITEM",--单击主角界面背包的时装时
	ON_SELECT_SFASHION_ITEM = "ON_SELECT_SFASHION_ITEM",--选中装界面背包的时装
	ON_HOLD_SFASHION_ITEM = "ON_HOLD_SFASHION_ITEM",--按住时装界面的时装时
	ON_SELECT_FASHION_SLOT_ITEM = "ON_SELECT_FASHION_SLOT_ITEM",--选中时装插槽
	ON_HOLD_FASHION_SLOT_ITEM = "ON_HOLD_FASHION_SLOT_ITEM",--按住时装插槽
	ON_SELECT_SUIT_COMPONENT = "ON_SELECT_SUIT_COMPONENT",--选中套装部件时
	ON_SELECT_SUIT_ITEM = "ON_SELECT_SUIT_ITEM",

	--mail
	ON_OPEN_MAIL = "ON_OPEN_MAIL",
	ON_ITEM_SELECT_MAIL = "ON_ITEM_SELECT_MAIL",
	ON_ITEM_DELETE_MAIL = "ON_ITEM_DELETE_MAIL",
	ON_SELECT_MAIL = "ON_SELECT_MAIL",
	ON_DELETE_MAIL = "ON_DELETE_MAIL",
	ON_DELETE_MAIL_ALL = "ON_DELETE_MAIL_ALL",
	ON_GET_MAIL_AWARD_ALL = "ON_GET_MAIL_AWARD_ALL",
	ON_GET_MAIL_AWARD = "ON_GET_MAIL_AWARD",
	ON_ADD_MAIL = "ON_ADD_MAIL",

	--gm
	ON_GM_GET_LIST = "ON_GM_GET_LIST";

	--chat
	ON_REFRESH_WORLD_CHAT = "ON_REFRESH_WORLD_CHAT",
	ON_REFRESH_SYSTEM_CHAT = "ON_REFRESH_SYSTEM_CHAT",
	ON_REFRESH_FAMILY_CHAT = "ON_REFRESH_FAMILY_CHAT",
	ON_REFRESH_TEAM_CHAT = "ON_REFRESH_TEAM_CHAT",
	ON_REFRESH_PRIVATE_CHAT = "ON_REFRESH_PRIVATE_CHAT",
	ON_GET_PLAYER_PRIVATE = "ON_GET_PLAYER_PRIVATE",
	ON_ITEM_SELECT_PRIVATE_PLAYER = "ON_ITEM_SELECT_PRIVATE_PLAYER",
	ON_CHAT_TO_PLAYER = "ON_CHAT_TO_PLAYER",
	ON_CHANGE_PRIVATE_LIST_SELECT = "ON_CHANGE_PRIVATE_LIST_SELECT",
	ON_CHANGE_PRIVATE_LIST_SELECT_NOTREAL = "ON_CHANGE_PRIVATE_LIST_SELECT_NOTREAL",
	ON_RECIVE_CHAT_PLAYER = "ON_RECIVE_CHAT_PLAYER",
	ON_CLICK_FACE = "ON_CLICK_FACE",
	ON_REFRESH_CHAT_FLAG = "ON_REFRESH_CHAT_FLAG",
	ON_ADD_CHATER = "ON_ADD_CHATER",
	ON_CHAT_MAIN_SYSTEM_ADD = "ON_CHAT_MAIN_SYSTEM_ADD",
	ON_CHANGE_CHAT_SCROLL_POS_AND_HEIGHT = "ON_CHANGE_CHAT_SCROLL_POS_AND_HEIGHT",
	ON_CHAT_CLICK_LINK = "ON_CHAT_CLICK_LINK",

	--store
	ON_CHANGE_STORE_PAGE = "ON_CHANGE_STORE_PAGE",
	ON_CREATE_STORE_ITEM = "ON_CREATE_STORE_ITEM",

	--promote
	ON_GIVE_UP_EXAM = "ON_GIVE_UP_EXAM",
	ON_ROLE_PROMOTE = "ON_ROLE_PROMOTE",
	ON_FRIENDLY_INIT = "ON_FRIENDLY_INIT",
	ON_RECV_NPC_RESULT = "ON_RECV_NPC_RESULT",
	ON_RECV_INFO_FIRST = "ON_RECV_INFO_FIRST",
	ON_FRIENDLY_RESULT = "ON_FRIENDLY_RESULT",
	ON_BEGIN_NEXT_EXAM = "ON_BEGIN_NEXT_EXAM",
	ON_UPDATE_EXAM_VIEW = "ON_UPDATE_EXAM_VIEW",
	ON_RECV_PROMOTE_RANK = "ON_RECV_PROMOTE_RANK",
	ON_RECV_PROMOTE_ARENA = "ON_RECV_PROMOTE_ARENA",
	ON_RECV_PROMOTE_ENEMT = "ON_RECV_PROMOTE_ENEMT",

	--dungeon
	ON_DUNGEON_SWEEP = "ON_DUNGEON_SWEEP",
	ON_MAIN_STORY_END = "ON_MAIN_STORY_END",
	ON_NEW_DUNGEON_PASS = "ON_NEW_DUNGEON_PASS",
	ON_GET_DUNGEON_DATA = "ON_GET_DUNGEON_DATA",
	ON_SELECT_CHAPTER_ITEM = "ON_SELECT_CHAPTER_ITEM",
	ON_SELECT_DUNGEON_ITEM = "ON_SELECT_DUNGEON_ITEM",

	--arena
	ON_RECV_ARENA_INIT = 'ON_RECV_ARENA_INIT',
	ON_RECV_ARENA_RANK = "ON_RECV_ARENA_RANK",
	ON_RECV_ARENA_ENEMT = "ON_RECV_ARENA_ENEMT",
	ON_RECV_ARENA_UPDATE = 'ON_RECV_ARENA_UPDATE',
	ON_SHOW_ARENA_FORMATION = "ON_SHOW_ARENA_FORMATION",
	
	--mansion
	ON_RECV_SELF_MANSION_DATA = "ON_RECV_SELF_MANSION_DATA",
	ON_RECV_VISIT_MANSION_DATA = "ON_RECV_VISIT_MANSION_DATA",
	ON_RECV_MANSION_CLEAN_UPDATE = "ON_RECV_MANSION_CLEAN_UPDATE",
	ON_RECV_ALTER_MANSION_NAME = "ON_RECV_ALTER_MANSION_NAME",
	ON_RECV_MANSION_EVENT_LIST = "ON_RECV_MANSION_EVENT_LIST",
	ON_RECV_SERVANT_HIRE_FIRST = "ON_RECV_SERVANT_HIRE_FIRST",
	ON_RECV_SERVANT_ALTER_NAME = "ON_RECV_SERVANT_ALTER_NAME",
	ON_RECV_SERVANT_AWARD_MONEY = "ON_RECV_SERVANT_AWARD_MONEY",
	ON_RECV_SERVANT_PAYOFF_MONEY = "ON_RECV_SERVANT_PAYOFF_MONEY",
	ON_RECV_CAN_VISIT_PLAYER_LIST = "ON_RECV_CAN_VISIT_PLAYER_LIST",
	ON_RECV_MANSION_PLANT_QUEUE = "ON_RECV_MANSION_PLANT_QUEUE",
	ON_SELECT_PLANT_SEED_ITEM = "ON_SELECT_PLANT_SEED_ITEM",
	ON_SELECT_PLANT_QUEUE_SEED = "ON_SELECT_PLANT_QUEUE_SEED",
	ON_RECV_MANSION_BUY_LAND = "ON_RECV_MANSION_BUY_LAND",
	ON_RECV_MANSION_PLANT_OP = "ON_RECV_MANSION_PLANT_OP",
	ON_RECV_NPC_EVENT_UPDATE = "ON_RECV_NPC_EVENT_UPDATE",
	ON_RECV_NPC_EVENT_REWARD = "ON_RECV_NPC_EVENT_REWARD",
	ON_RECV_NPC_EVENT_DELETE = "ON_RECV_NPC_EVENT_DELETE",
	ON_RECV_COMPOSE_MATERIAL = "ON_RECV_COMPOSE_MATERIAL",
	ON_SELECT_COMPOSE_GOODS = "ON_SELECT_COMPOSE_GOODS",
	ON_RECV_MANSION_FEAST_INFO = "ON_RECV_MANSION_FEAST_INFO",
	ON_RECV_MANSION_FEAST_LIST = "ON_RECV_MANSION_FEAST_LIST",
	ON_RECV_MANSION_FEAST_JOIN = "ON_RECV_MANSION_FEAST_JOIN",
	ON_RECV_MANSION_FEAST_DETAIL = "ON_RECV_MANSION_FEAST_DETAIL",
	ON_SELECT_FEAST_LIST_ITEM = "ON_SELECT_FEAST_LIST_ITEM",
	ON_SELECT_FEAST_COST_ITEM = "ON_SELECT_FEAST_COST_ITEM",

	--rank
	ON_CHANGE_SELF_RANK_VALUE = "ON_CHANGE_SELF_RANK_VALUE",
	ON_ITEM_SELECT_RANK = "ON_ITEM_SELECT_RANK",
	ON_BUTTON_SELECT_RANK = "ON_BUTTON_SELECT_RANK",

	--elite_dungeon
	ON_ELITE_DUNGEON_REFRESH_ALL = "ON_ELITE_DUNGEON_REFRESH_ALL",
	ON_ELITE_DUNGEON_REFRESH_ID = "ON_ELITE_DUNGEON_REFRESH_ID",
	ON_ELITE_DUNGEON_SHOW_ARRAY = "ON_ELITE_DUNGEON_SHOW_ARRAY",
	ON_ELITE_DUNGEON_SHOW_DETAIL = "ON_ELITE_DUNGEON_SHOW_DETAIL",
	ON_ELITE_DUNGEON_CLOSE_DETAIL = "ON_ELITE_DUNGEON_CLOSE_DETAIL",
	ON_ELITE_DUNGEON_SHOW_DIALOG = "ON_ELITE_DUNGEON_SHOW_DIALOG",
	ON_ELITE_DUNGEON_SHOW_DIALOG_NOW = "ON_ELITE_DUNGEON_SHOW_DIALOG_NOW",

	--worship_queen
	ON_WORSHIP_QUEEN_GET_INFO = "ON_WORSHIP_QUEEN_GET_INFO",
	ON_WORSHIP_QUEEN_GET_AWARD = "ON_WORSHIP_QUEEN_GET_AWARD",

	--worship_ancestor
	ON_WORSHIP_ANCESTOR_GET_INFO = "ON_WORSHIP_ANCESTOR_GET_INFO",
	ON_WORSHIP_ANCESTOR_GET_AWARD = "ON_WORSHIP_ANCESTOR_GET_AWARD",

	--child
	ON_CHILD_SELECT = "ON_CHILD_SELECT",

	--mystery
	ON_GET_MYSTERY_LIST = "ON_GET_MYSTERY_LIST",

	--recevie_power
	ON_GET_EVERY_DAY_POWER = "ON_GET_EVERY_DAY_POWER",
	ON_RECEIVE_POWER = "ON_RECEIVE_POWER",
	ON_RESTORE_TIME = "ON_RESTORE_TIME",
	ON_RESTORE_UPDATE_STRENGTH = "ON_RESTORE_UPDATE_STRENGTH",
	ON_RESTORE_UPDATE_ENERGY = "ON_RESTORE_UPDATE_ENERGY",

	--archive
	ON_GET_ARCHIVE_LIST = "ON_GET_ARCHIVE_LIST",
}


return EventEnum;