
local ConfigSysmansion_servant_exp={
              [1] = {
                      lv = 1,
                      exp_1 = 0,
                      exp_2 = 0,
                      exp_3 = 0,
                      feast = 0,
                      cleanup = 0,
                      house_coin = 200,
                      harvest = 0,
                    },
              [2] = {
                      lv = 2,
                      exp_1 = 78,
                      exp_2 = 62,
                      exp_3 = 14,
                      feast = 50,
                      cleanup = 1,
                      house_coin = 210,
                      harvest = 60,
                    },
              [3] = {
                      lv = 3,
                      exp_1 = 123,
                      exp_2 = 98,
                      exp_3 = 46,
                      feast = 100,
                      cleanup = 2,
                      house_coin = 220,
                      harvest = 120,
                    },
              [4] = {
                      lv = 4,
                      exp_1 = 182,
                      exp_2 = 146,
                      exp_3 = 103,
                      feast = 150,
                      cleanup = 3,
                      house_coin = 230,
                      harvest = 180,
                    },
              [5] = {
                      lv = 5,
                      exp_1 = 257,
                      exp_2 = 206,
                      exp_3 = 194,
                      feast = 200,
                      cleanup = 4,
                      house_coin = 240,
                      harvest = 240,
                    },
              [6] = {
                      lv = 6,
                      exp_1 = 348,
                      exp_2 = 278,
                      exp_3 = 327,
                      feast = 250,
                      cleanup = 5,
                      house_coin = 250,
                      harvest = 300,
                    },
              [7] = {
                      lv = 7,
                      exp_1 = 454,
                      exp_2 = 363,
                      exp_3 = 513,
                      feast = 300,
                      cleanup = 6,
                      house_coin = 260,
                      harvest = 360,
                    },
              [8] = {
                      lv = 8,
                      exp_1 = 575,
                      exp_2 = 460,
                      exp_3 = 758,
                      feast = 350,
                      cleanup = 7,
                      house_coin = 270,
                      harvest = 420,
                    },
              [9] = {
                      lv = 9,
                      exp_1 = 711,
                      exp_2 = 569,
                      exp_3 = 1072,
                      feast = 400,
                      cleanup = 8,
                      house_coin = 280,
                      harvest = 480,
                    },
              [10] = {
                      lv = 10,
                      exp_1 = 863,
                      exp_2 = 690,
                      exp_3 = 1463,
                      feast = 450,
                      cleanup = 9,
                      house_coin = 290,
                      harvest = 540,
                    },
              [11] = {
                      lv = 11,
                      exp_1 = 1031,
                      exp_2 = 825,
                      exp_3 = 1944,
                      feast = 500,
                      cleanup = 10,
                      house_coin = 300,
                      harvest = 600,
                    },
              [12] = {
                      lv = 12,
                      exp_1 = 1283,
                      exp_2 = 1026,
                      exp_3 = 2660,
                      feast = 550,
                      cleanup = 11,
                      house_coin = 310,
                      harvest = 660,
                    },
              [13] = {
                      lv = 13,
                      exp_1 = 1596,
                      exp_2 = 1277,
                      exp_3 = 3610,
                      feast = 600,
                      cleanup = 12,
                      house_coin = 320,
                      harvest = 720,
                    },
              [14] = {
                      lv = 14,
                      exp_1 = 1986,
                      exp_2 = 1588,
                      exp_3 = 4491,
                      feast = 650,
                      cleanup = 13,
                      house_coin = 330,
                      harvest = 780,
                    },
              [15] = {
                      lv = 15,
                      exp_1 = 2471,
                      exp_2 = 1976,
                      exp_3 = 5588,
                      feast = 700,
                      cleanup = 14,
                      house_coin = 340,
                      harvest = 840,
                    },
              [16] = {
                      lv = 16,
                      exp_1 = 3074,
                      exp_2 = 2459,
                      exp_3 = 6952,
                      feast = 750,
                      cleanup = 15,
                      house_coin = 350,
                      harvest = 900,
                    },
              [17] = {
                      lv = 17,
                      exp_1 = 3824,
                      exp_2 = 3059,
                      exp_3 = 8649,
                      feast = 800,
                      cleanup = 16,
                      house_coin = 360,
                      harvest = 960,
                    },
              [18] = {
                      lv = 18,
                      exp_1 = 4757,
                      exp_2 = 3806,
                      exp_3 = 10760,
                      feast = 850,
                      cleanup = 17,
                      house_coin = 370,
                      harvest = 1020,
                    },
              [19] = {
                      lv = 19,
                      exp_1 = 5919,
                      exp_2 = 4735,
                      exp_3 = 13387,
                      feast = 900,
                      cleanup = 18,
                      house_coin = 380,
                      harvest = 1080,
                    },
              [20] = {
                      lv = 20,
                      exp_1 = 7363,
                      exp_2 = 5890,
                      exp_3 = 16654,
                      feast = 950,
                      cleanup = 19,
                      house_coin = 390,
                      harvest = 1140,
                    },
            }
return ConfigSysmansion_servant_exp;