#!/usr/bin/env python

import sys, os.path

install_path = sys.argv[1]
target_platform = sys.argv[2]

if target_platform != "iPhone": sys.exit()

info_plist_path = os.path.join(install_path, 'Info.plist')

file = open(info_plist_path, 'r')
plist = file.read()
file.close()

elements_to_add = '''
<key>NSMicrophoneUsageDescription</key>
<string>Description</string>
<key>NSCameraUsageDescription</key>
<string>Description</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>Description</string>
<key>NSContactsUsageDescription</key>
<string>Description</string>
<key>NSBluetoothPeripheralUsageDescription</key>
<string>Description</string>
<key>NSSpeechRecognitionUsageDescription</key>
<string>Description</string>
<key>NSCalendarsUsageDescription</key>
<string>Description</string>
<key>NSLocationWhenInUseUsageDescription</key>
<string>Description</string>
<key>NSLocationAlwaysUsageDescription</key>
<string>Description</string>
<key>ITSAppUsesNonExemptEncryption</key><false/>
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
<key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>tjSchemeKeyStr+1538</string>
            </array>
        </dict>
    </array>
<key>LSApplicationQueriesSchemes</key>
    <array>
        <string>wechat</string>
        <string>weixin</string>
        <string>alipay</string>
        <string>alipayauth</string>
        <string>safepay</string>
    </array>


'''

plist = plist.replace('<key>', elements_to_add + '<key>', 1)

file = open(info_plist_path, 'w')
file.write(plist)
file.close()