
local ConfigSystalent_type={
              [1] = {
                      name = [[茶艺]],
                      icon = [[icon_004011]],
                      base_value = 100,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [2] = {
                      name = [[花艺]],
                      icon = [[icon_004021]],
                      base_value = 100,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [3] = {
                      name = [[戏曲]],
                      icon = [[icon_004031]],
                      base_value = 100,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [4] = {
                      name = [[骑术]],
                      icon = [[icon_004041]],
                      base_value = 120,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [5] = {
                      name = [[刺绣]],
                      icon = [[icon_004051]],
                      base_value = 120,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [6] = {
                      name = [[作画]],
                      icon = [[icon_004061]],
                      base_value = 100,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [7] = {
                      name = [[书法]],
                      icon = [[icon_004071]],
                      base_value = 100,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [8] = {
                      name = [[篆刻]],
                      icon = [[icon_004081]],
                      base_value = 100,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [9] = {
                      name = [[抚琴]],
                      icon = [[icon_004091]],
                      base_value = 160,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [10] = {
                      name = [[舞艺]],
                      icon = [[icon_004101]],
                      base_value = 160,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [11] = {
                      name = [[酿酒]],
                      icon = [[icon_004111]],
                      base_value = 175,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [12] = {
                      name = [[蹴鞠]],
                      icon = [[icon_004121]],
                      base_value = 180,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [13] = {
                      name = [[医术]],
                      icon = [[icon_004131]],
                      base_value = 175,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [14] = {
                      name = [[炼丹]],
                      icon = [[icon_004141]],
                      base_value = 160,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [15] = {
                      name = [[诗赋]],
                      icon = [[icon_004151]],
                      base_value = 150,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [16] = {
                      name = [[棋奕]],
                      icon = [[icon_004161]],
                      base_value = 150,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [17] = {
                      name = [[厨艺]],
                      icon = [[icon_004171]],
                      base_value = 150,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
              [18] = {
                      name = [[武术]],
                      icon = [[icon_004181]],
                      base_value = 175,
                      star_value = {
                              0.5,
                              0.6,
                              0.7,
                              0.9,
                              1.2,
                              2,
                            },
                      qulity_value = {
                              0.5,
                              0.7,
                              0.95,
                              1.2,
                              1.55,
                              2,
                            },
                    },
            }
return ConfigSystalent_type;